### ISSUE TITLE
Configuration dumper/debugger

### ISSUE THREAD

**Issue by mnapoli** [PHP-DI/PHP-DI#152]
A nice idea [from reddit](http://www.reddit.com/r/PHP/comments/1x0r2f/phpdi_40_released/cf7mz57):
- dumping the definition of an entry to help debug it (CLI tool probably)
- dumping all the definitions in the container
- logging debug info (how the container resolves an entry)

**Comment by holtkamp** [comment]
Just encountered this issue, we use separate definition files and then one can use (quite raw, but you get the idea):

```php
 $debugDicConfiguration = false;
    if ($debugDicConfiguration === true) {
        $registeredResources = array();
        foreach ($definitionsFiles as $definitionsFile) {
            $definitions = require $definitionsFile;
            foreach ($definitions as $registeredResource => $value) {
                if (in_array($registeredResource, $registeredResources)) {
                    echo "Error, duplicate Resource name $registeredResource";
                }
                $registeredResources[] = $registeredResource;
                $resource = $dicContainer->get($registeredResource);
                printf('<pre>Loading %s resulted in class: %s, last errors: %s</pre>', $registeredResource, is_object($resource) ? get_class($resource) : gettype($resource), print_r(error_get_last(), true));
            }
        }
        exit;
    }
```

**Comment by juliangut** [comment]
@mnapoli how would you integrate _definition dumpers_ into a CLI tool such as a Symfony/Console? 

Just a single command to dump container configuration like so:
```
php bin/console container:debug
```

**Comment by mnapoli** [comment]
@juliangut at the moment if you have a definition object, you can simply cast it to string and that will give you debug information. So you could write a CLI command that does that.

However the problem is getting the definition. There is no method on the container. And I'm not sure I want to add one :/ (because definitions are pretty "internal")

**Comment by juliangut** [comment]
@mnapoli have you changed your mind about exposing definitions in order to create something like I commented? maybe not expose "exactly" internal definitions but some sort of simple definition object

**Comment by mnapoli** [comment]
@juliangut yes I think that's a good idea. Since definitions are internal maybe we could have a `dumpDefinition($entryName) : string` method on the container. I could return the dumped definition as a string?

**Comment by juliangut** [comment]
With your proposed `dumpDefinition($entryName)` I'd need to know all $entryName I want to dump, but what I want is to show whole Container definitions. I guess I could have an array of definitions prior to give it to ContainerBuilder so I can get the keys and then call dumpDefinition for each

Now that I think about it... I haven't seen the new compiled definitions file, but could it be used to extract what I want?

**Comment by mnapoli** [comment]
Ah right this is indeed the same problem as the compiler (I've added [a `getDefinitions()` method on definition sources for that](https://github.com/PHP-DI/PHP-DI/blob/master/src/Compiler.php#L66)). The limitation is that the container cannot dump "unknown" definitions, i.e. all the classes that will be autowired. This is explained here: https://github.com/PHP-DI/PHP-DI/blob/master/doc/performances.md#optimizing-for-compilation

But that may be a good thing, that will help users realize which definitions are actually compiled (all those dumped in `bin/console container:debug`).

Here are methods to achieve what you suggest:

- `debugEntry($name) : string` : returns the dump/debug output for the given definition
- `getKnownEntryNames() : array` : returns the list of all entry names known by the container

That way you can do something like this:

```php
$entryNames = $container->getKnownEntryNames();

foreach ($entryNames as $name) {
    echo $container->debugEntry($name);
}
```

Would that be good?

**Comment by juliangut** [comment]
> But that may be a good thing, that will help users realize which definitions are actually compiled (all those dumped in bin/console container:debug).

That is exactly the case I'm aiming for, and yes it'd be covered by your proposal

**Comment by mnapoli** [comment]
Implemented by @juliangut, thanks!
