### ISSUE TITLE
Symfony2 Integration - Services with tags

### ISSUE THREAD

**Issue by mtotheikle** [PHP-DI/PHP-DI#175]
Has anyone used this library heavily with Symfony2? I like the looks of it but looking for some proven integrations for more advanced features such as service tags.

The use for this would be support with the form system, twig extension etc.

**Comment by mnapoli** [comment]
For those stumbling on this issue looking for tags in PHP-DI:

**if you are used to Symfony's tag feature and are using PHP-DI alone:**

- you can create lists using arrays: http://php-di.org/doc/php-definitions.html#arrays
- you can extend lists (if using a module system, or multiple config files) using arrays extensions: http://php-di.org/doc/definition-overriding.html#arrays

You can also learn more about it in PHP-DI 5.0 release article: http://php-di.org/news/15-php-di-5-0-released.html#features-for-modular-applications

**if you are using Symfony + PHP-DI together:**

- you can't use Symfony tags in PHP-DI
- services that need to be tagged should be defined in Symfony, but dependencies of this service can be in PHP-DI now that https://github.com/PHP-DI/Symfony-Bridge/pull/4 has been implemented
