### ISSUE TITLE
Support for DI\link() in factory definitions (arrays)

### ISSUE THREAD

**Issue by mnapoli** [PHP-DI/PHP-DI#179]
```php
return [
    'Foo' => DI\factory([DI\link('FooFactory'), 'create']),
];
```

**Comment by mnapoli** [comment]
Implemented in #308

**Comment by juliangut** [comment]
In https://github.com/PHP-DI/PHP-DI/blob/master/doc/migration/5.0.md it is stated that `DI\get` is preferred over link which still does the job

Shouldn't this ticket name be "Support for DI\get() in factory definitions (arrays)" and all references to link removed as much as possible even in tickets such like this?

**Comment by mnapoli** [comment]
@juliangut why not but in this case it wasn't implemented as described in the issue. Instead it works like this:

```php
return [
    'Foo' => DI\factory(['FooFactory', 'create']),
];
```

I'll a notice in the issue description.
