### ISSUE TITLE
Container::call() should allow to define dependencies a la AngularJS

### ISSUE THREAD

**Issue by mnapoli** [PHP-DI/PHP-DI#239]
Just like in AngularJS we can do:

``` js
angular.controller('MyController', ['$scope', 'dep1', 'dep2', function($scope, dep1, dep2) {
  // ...
}]);
```

It would be great to be able to explicitly ask for dependencies:

``` php
$container->call(['db.host', 'db.port', function ($host, $port) {
    // ...
}]);
```

Currently `Container::call()` guesses the objects to inject using type-hints, but this doesn't always work. By using AngularJS's pattern it's already well known and it solves the problem.

That could also be used (if #197 happens) in `DI\factory` too:

``` php
    'db' => DI\factory(['db.host', 'db.port', function ($host, $port) {
        return new Db($host, $port);
    }]);
```

**Comment by mnapoli** [comment]
I'm leaving that feature aside for now as I'm not 100% sure it's the right way. First it could be confusing to add yet another concept that people have to learn. Second, this doesn't allow to define *some* parameters only:

```php
$container->call(['Psr\Log\LoggerInterface', 'foo', function (LoggerInterface $logger, $foo) {
}]);
```

In the example above I have to redefine the `$logger` parameter even though it could be guessed using autowiring…

**Comment by mindplay-dk** [comment]
> this doesn't allow to define *some* parameters only

Well, it could:

```PHP
$container->call(['foo' => 'bar'], function (LoggerInterface $logger, $foo) {});
```

In other words, array values with numeric keys are applied in order, whereas array values with string keys are applied by name.

Putting the function inside the array is confusing btw, in my example I have the parameter array and function as separate arguments - so as for `DI\factory()`:

```PHP
    'db' => DI\factory(['db.host', 'db.port'], function ($host, $port) {
        return new Db($host, $port);
    });
```

This is backwards incompatible though? Since `DI\factory()` would see `['db.host', 'db.port']` as a `callable`, wouldn't it (?)

**Comment by mnapoli** [comment]
Yes it could work indeed, and your solution would be supported out of the box by `Container::call()` so that's nice.

> This is backwards incompatible though? Since DI\factory() would see ['db.host', 'db.port'] as a callable, wouldn't it (?)

It could simply check if there's a closure as a second parameter. In that case the array is an array of parameters.

However I like the idea of embedding the closure because I'm thinking of "defining" a concept of "extended callables".

E.g. `[new Foo, 'bar']` is a callable and `['Foo', 'bar']` is not (if the method is not static). However you can `->call(['Foo', 'bar'])` and the container will create Foo. So `['Foo', 'bar']` would be an "extended callable", i.e. not a PHP callable but one that a container can resolve. Having the array-closure callable defined here in the lot of "extended callable" would make it much more powerful (and familiar to those using AngularJS).

Introducing this concept, with proper documentation, would make it easier to document PHP-DI and make users understand those exotic features. Also it could spread to other containers, and (that's my hope) to frameworks. E.g. being able to define controllers as extended callables. That's something I tried to convince Slim of doing in its v3 but it was too confusing. If the concept is clearly defined and documented, and people start to learn about it, it could work.

Anyway, just an idea I need to set in motion and see how it works out…

**Comment by mnapoli** [comment]
Dropping this idea for now, most needs regarding callables are already addressed today.
