### ISSUE TITLE
Problems with APC 3.1.13 OPCODE cache on PHP 5.4.39

### ISSUE THREAD

**Issue by holtkamp** [PHP-DI/PHP-DI#266]
There seems to be a problem with the use of PHP-DI (both 4.4.7 and 5.0.0-RC1) in combination with APC 3.1.13 OPCODE caching in a PHP-FPM environment, using PHP 5.4.39. More specific, the [Pinky stack of CloudControl](https://github.com/cloudControl/buildpack-php).

The FPM process exits prematurely, probably due to SEGFAULT errors in APC:

```
[05-Jun-2015 12:15:23] WARNING: [pool www] child 62 exited on signal 11 (SIGSEGV - core dumped) after 65.286924 seconds from start

[Fri Jun 05 14:15:23 2015] error [error] [client 10.196.140.68] (104)Connection reset by peer: FastCGI: comm with server "/app/php/box/php-fpm" aborted: read failed
[Fri Jun 05 14:15:23 2015] error [error] [client 10.196.140.68] Handler for fastcgi-script returned invalid result code 1
```

This problem does not occur 'always', only for some specific Dependency injections. The process to find out exactly where it goes wrong is very time-consuming in is probably not caused by PHP-DI, but by APC OPCODE. We experienced problems with APC earlier, when adding / removing a space in a fail solved/created the problem. In summary: some weird bug :smile: 

*Disable APC OPCODE caching*
When disabling APC OPCODE "cache_by_default" and only allow some specific paths to be cached using a filter, the problem is resolved:

```
[APC]
apc.enabled = 1
apc.cache_by_default = 0
apc.filters = "+/srv/www/code/library/.*,+/srv/www/code/vendor/.*"
```

Disabling proxy generation and/or use of DIC caches, did not solve the problem. Note that using the ApcCache for the container does NOT cause any problems. Only the APC OPCODE cache causes a problem, not the APC user cache.

*APC is deprecated*
Since the use of APC is replaced with the bundled [Zend OPCache  as of PHP 5.5](http://php.net/manual/en/book.opcache.php) and an upgrade of our applications is imminent, I don't care to spend too much time on searching the cause, but just wanted to report this issue.

On a development environment with PHP 5.6, no errors occur, no error messages are generated, so APC seems to be the cause.

**Comment by mnapoli** [comment]
Thanks for the detailed info, this is indeed very specific ;)

> Since the use of APC is replaced with the bundled Zend OPCache as of PHP 5.5 and an upgrade of our applications is imminent, I don't care to spend too much time on searching the cause, but just wanted to report this issue.

+1, doesn't make sense to look too much into it if you have the possibility to upgrade. Given what you describe, I doubt there's much we can change in PHP-DI's code that will solve such problem, but having this description in an issue could be helpful if anybody else experiences the same thing so thank you.

> This problem does not occur 'always', only for some specific Dependency injections.

Was it using annotations?

**Comment by holtkamp** [comment]
we use both autowiring, annotations and (array based) configuration files.

The error occurred / disappeared when enabling / disabling the use of one
specific configuration file with around 15 simple Definitions using
DI\object().

Must/might be some strange memory thingy in APCs approach to OPCODE caching
we experienced this before, other PHP 5.4 users also report this...

**Comment by mnapoli** [comment]
OK, weird thing indeed. I'll be closing since there's nothing much to do here.
