### ISSUE TITLE
We cannot share pages on php-di.org

### ISSUE THREAD

**Issue by bgaillard** [PHP-DI/PHP-DI#270]
Hi Matthieu and thanks for this new PHP-DI 5.0 release (we'll use it on our next big project ;-) ),

By visiting the new Website at http://php-di.org it seems no page provides share buttons. 

I think a Twitter and a Facebook button would be very useful. Without that it does not encourage people to promote PHP-DI.

For me today this is not only a useful feature but more a must have.

Baptiste

**Comment by mnapoli** [comment]
Awesome!

> For me today this is not only a useful feature but more a must have.

Ah interesting I was thinking that it wouldn't be very useful today, so yes let's add them :)
