### ISSUE TITLE
Best practice to define (Doctrine) Repository Injections, which can be cached

### ISSUE THREAD

**Issue by holtkamp** [PHP-DI/PHP-DI#273]
I am are trying to inject our Doctrine Repositories into a private Service property using the ```@inject``` annotation. I see two options:
- fetch them using the (Doctrine) [EntityManager::getRepository()](http://www.doctrine-project.org/api/orm/2.4/class-Doctrine.ORM.EntityManager.html#_getRepository), using the Entity classname
- fetch them using the (Doctrine) [DefaultRepositoryFactory::getRepository()](http://www.doctrine-project.org/api/orm/2.4/class-Doctrine.ORM.Repository.DefaultRepositoryFactory.html#_getRepository), using the Entity classname

The current configuration works, but seems not so intelligent and not cacheable (? no Repository related entries show up in the cache, because this way it uses closures?):
```php
Project\Domain\Repository\Entity\ProductRepository::class => function (DI\Container $container) {
	return $container->get('EntityManager')->getRepository(Project\Domain\Entity\Product::class);
},
```
So I tried:
```php
Project\Domain\Repository\Entity\ProductRepository::class => DI\get('EntityManager')
    ->method('getRepository', Project\Domain\Entity\ProductType::class)
},
```

But the ```DI\get()``` alias does not support that kind of method chaining and the EntityManager can not be easily instantiated.

So what about the [DefaultRepositoryFactory::getRepository()](http://www.doctrine-project.org/api/orm/2.4/class-Doctrine.ORM.Repository.DefaultRepositoryFactory.html#_getRepository):
```php
Project\Domain\Repository\Entity\ProductTypeRepository::class => DI\object(Doctrine\ORM\Repository\DefaultRepositoryFactory::class)
    ->method('getRepository', DI\get('EntityManager'), Project\Domain\Entity\ProductType::class)
```

But this would still return an object of type ```Doctrine\ORM\Repository\DefaultRepositoryFactory``` instead of the intended ```Project\Domain\Repository\Entity\ProductTypeRepository```. While debugging I can see the ```DefaultRepositoryFactory::getRepository()``` creates the proper object, but I guess the methods should be only use as setters and does not return getter values...

My questions
- would it be possible to allow method chaining for the ```DI\get()``` and return the value of the invoked method?
- what is going wrong here, do I misinterpret the use of the ```DI\method()```? Should it be only used for setters?
- what would be a good approach? I can create a PR to submit to the documentation for this...

Note, this is the first step to using DIC for our repositories. Eventually we will use proper RepositoryInterfaces for them and hopefully wildcards to be able to configure all of them...

**Comment by mnapoli** [comment]
> do I misinterpret the use of the DI\method()?

I'm afraid yes. This allows to define a [setter injection](http://symfony.com/doc/current/components/dependency_injection/types.html#setter-injection), so the goal is not to return the result. In both cases (get() and object()) the object returned will be the one defined in `get(…)` or `object(…)`.

Currently the only way to do what you want to do is indeed to use a factory. I don't think performances will suffer a lot. Yes closures can't be cached, but the cache is mostly useful for reflection and annotations.

**Comment by mnapoli** [comment]
The ideal solution would be to find one in #81 and write a RepositoryFactory that uses the container.

**Comment by holtkamp** [comment]
Ok, thanks, and

>would it be possible to allow method chaining for the DI\get() and return the value of the invoked method?

This seems a useful enhancement to me? Maybe this can be realised by having the EntryReference class forward all incoming calls using ```__call``` to the actual Definition?

A naive approach, but you get the idea:

```php
    /**
     * Hand over all functions to the Definition object
     *
     * @param string $name
     * @param array $arguments
     * @return mixed
     */
    public function __call($name, $arguments)
    {
        $aliasDefinition = $this->getDefinition($this->getName());
        $objectDefinition = new \DI\Definition\Helper\ObjectDefinitionHelper($aliasDefinition->getTargetEntryName());
        $callable = array($objectDefinition, $name);

        return call_user_func_array($callable, $arguments);
    }
```

**Comment by mnapoli** [comment]
This wouldn't work on the definition object because the definition isn't able to create the objects (definition resolvers do that). Anyway, it could be possible I think but that would be wrong: `get()` just allows to do an alias to another entry. We would complicate a lot the usage of PHP-DI and the core concepts, and my goal is to keep it a simple as possible. That doesn't mean not implementing complex needs, but rather find solutions that are natural for users and easy to understand.

`DI\factory()` could do this, e.g.

```php
    UserRepository::class => factory([EntityManager::class, 'getRepository'])
```

That would call `EntityManager::getRepository()`, but that would provide a parameter so that wouldn't work. To provide the name of the entity #197 might be able to help with a syntax to pass parameters to the factory (after all, `->getRepository()` is a factory).

Anyway #81 is the best solution, it would be much more practical.

**Comment by holtkamp** [comment]
Understood, closing issue, thanks for the detailed responses :+1:

**Comment by holtkamp** [comment]
Final comment, your last comment triggered me to use :

```
UserRepository::class => DI\factory(UserRepository::class, 'getInstance')
```

The static ```getInstance``` fetches the EntityManager from the container, determines the Entity name and fetches a Repository from the EntityManager.

**Comment by holtkamp** [comment]
Final comment, your last comment triggered me to use :

```
UserRepository::class => DI\factory([UserRepository::class, 'getInstance'])
```

The static ```getInstance``` fetches the EntityManager from the container, determines the Entity name and fetches a Repository from the EntityManager.

**Comment by holtkamp** [comment]
@mnapoli, the problem with my last comment using DI\factory with a callable like:

```
UserRepository::class => DI\factory([UserRepository::class, 'getInstance'])
```

seems to be that the resulting instance of the Repository does not get injected with dependencies itself. Trying to do this manually using ```Container::injectOn()``` fails because [only ObjectDefinitions will be considered for injection](https://github.com/PHP-DI/PHP-DI/blob/91c8b9bb2e2e059b17bc5e1cea5b534c4ec8b710/src/DI/Container.php#L212-L215), while this is a FactoryDefinition. 

With the risk of completely missing the point here: would it be possible to have the **resulting instance** of a FactoryDefinition also to be injected with dependencies as defined using annotations?

Example:

```php
class UserRepository
{
    /**
     * Property is NOT injected when this class is registered at the DI using DI\factory()
     *
     * @Inject
     * @var \Some\Nice\EventBus
     */
    private $eventBus;
}
```

**Comment by holtkamp** [comment]
Mm, good point ;)

My eventual approach uses the simplest PHP-DI config:
```php
UserRepository::class => DI\object(),
OtherEntityRepository::class => DI\object(),
```

Then the repository constructor which assumes a naming convention of the Repository / Entities:

```php
   /**
     * Override Doctrine's EntityRepository constructor to intercept calls that do not have looked up the metadata yet.
     *
     * @param \Doctrine\ORM\EntityManager $entityManager
     * @param ClassMetadata | string      $metadata
     */
    public function __construct($entityManager, $metadata = null)
    {
        if (is_null($metadata)) {
            $entityClassName = $this->getEntityClassNameFromRepositoryName();
            $metadata = $entityManager->getClassMetadata($entityClassName);
        }

        parent::__construct($entityManager, $metadata);
    }

    /**
     * Convert current RepositoryName to EntityName
     *
     *  - 'Project\Domain\Repository\UserRepository' => 'Project\Domain\Entity\User'.
     *
     * @return string
     */
    private function getEntityClassNameFromRepositoryName()
    {
        return str_replace(array('Repository', '\\\\'), array('', '\\'), get_class($this));
    }
```

Thanks ;)

**Comment by vegbrasil** [comment]
Hi, sorry to dig this old issue.

I'm a bit lost in this world of DI... Is there a recommended method for injections that can (and should) be cached? Caching actual classes, not definitions/annotations.

Maybe there's a chance that I'm understanding some wrong concepts of PHP-DI. If I have a class that loads some heavy resource, it should't be injected a new instance every time, right? I could load once for the first injection and reuse it in the next injections.

Sorry if this is the wrong place, tried to find the solution in the documentation or in other issues and this is closest I got.

**Comment by holtkamp** [comment]
Have a look at this section: http://php-di.org/doc/php-definitions.html#factories

The instance will be re-used by default. Maybe you can open a separate issue and provide your definitions / example code of how that "heavy" dependency is injected?

**Comment by vegbrasil** [comment]
Thanks for the answer and sorry I missed the fact that factories are re-used.

Thank you!

**Comment by fenric** [comment]
See how PHP-DI can be linked to Doctrine repositories:
https://github.com/autorusltd/doctrine-repository-factory

**Comment by mnapoli** [comment]
@fenric very nice job!

**Comment by holtkamp** [comment]
@fenric nice, maybe you can extend the documentation a bit? How would you instantiate / get a certain Repository now? Maybe an example? 🤓

**Comment by shadowhand** [comment]
This was my solution:

```php
<?php
declare(strict_types=1);

namespace Acme\Factory;

use DI\Factory\RequestedEntry;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;

class RepositoryFactory
{
    public function __invoke(EntityManager $em, RequestedEntry $entry): EntityRepository
    {
        $className = preg_replace('/Repository$/', '', $entry->getName());

        return $em->getRepository($className);
    }
}
```

Usage, assuming PHP definitions:

```php
Acme\Entity\UserRepository::class => DI\factory(Acme\Factory\RepositoryFactory::class),
// repeat for other repository classes
```
