### ISSUE TITLE
[doc] Broken link, couscous bug ?

### ISSUE THREAD

**Issue by RayRutjes** [PHP-DI/PHP-DI#281]
Simply to let you know that the link to the best practices is broken on this documentation page: https://github.com/PHP-DI/PHP-DI/blob/master/doc/getting-started.md

See here http://php-di.org/doc/getting-started.html

The link redirects to a non existing .md file instead of the html one.

Could this be a coucous issue?

**Comment by mnapoli** [comment]
Thank you for the report I will look into it :)

**Comment by mnapoli** [comment]
It was indeed a Couscous issue :) https://github.com/CouscousPHP/Couscous/issues/112

**Comment by RayRutjes** [comment]
Well done!

**Comment by mnapoli** [comment]
Fixed!
