### ISSUE TITLE
Unable to install dist of version 4.4.7 due to mnapoli/phpdocreader dependency

### ISSUE THREAD

**Issue by jankramer** [PHP-DI/PHP-DI#283]
A composer install of `php-di/php-di@4.4.7` fails on downloading `mnapoli/phpdoc-reader` when passing `--prefer-dist` as it tries to download a ZIP-package from the old repository (`mnapoli/phpdocreader`).

Could you publish a 4.4.8 version which requires `php-di/phpdoc-reader` instead of `mnapoli/phpdocreader`? I think that would fix the problem.

**Comment by mnapoli** [comment]
Thank you for the report! I indeed reproduced it (in a VM, on my machine Composer's cache was hiding the problem…).

However can you confirm that PHP-DI is still installed with success and that the phpdocreader package is cloned using git? (as a fallback)

**Comment by jankramer** [comment]
Yes, it does perform a git clone of the phpdocreader package instead. This did not happen before which was the reason I opened this issue, but I think that was an issue on my end with an outdated composer version or something.

Having a dist version available would still be preferable of course :)

**Comment by mnapoli** [comment]
I have released 4.4.8 with the updated dependency: https://github.com/PHP-DI/PHP-DI/releases/tag/4.4.8

However this will only work for people requiring `php-di/php-di` (and not `mnapoli/php-di`). But it's still better than nothing :)

Thanks!

**Comment by jankramer** [comment]
Great, thanks!
