### ISSUE TITLE
PHP-DI 4.4.9

### ISSUE THREAD

**Issue by szarik88** [PHP-DI/PHP-DI#286]
Hello,

I have question about tag 4.4.9. I noticed that after update to this version PHP-DI stop working correct. Comparing changes I see that 5.0.0 was merged to 4.4.9.

changelog: https://github.com/PHP-DI/PHP-DI/compare/4.4.8...4.4.9

**Comment by bluescreen** [comment]
I can confirm. 4.4.9 is not reading the doc block injects.

**Comment by mnapoli** [comment]
Wow what did I do! So sorry, I think I tagged 4.4.9 on the master branch :/

I'll create a new release right now, sorry guys :(

**Comment by mnapoli** [comment]
I've released 4.4.10: https://github.com/PHP-DI/PHP-DI/releases/tag/4.4.10

This time it should be alright, please let me know if not.

**Comment by drealecs** [comment]
Can you create 4.4.10 on mnapoli/php-di also?

**Comment by mnapoli** [comment]
@drealecs unfortunately I moved the project to php-di/php-di on composer, going back seems impossible. How about I delete the version on Packagist? I think that's the best that can be done.
