### ISSUE TITLE
Support annotations through Traits

### ISSUE THREAD

**Issue by wdalmut** [PHP-DI/PHP-DI#288]
Hi,

with version ~4 the project supports annotations also via traits. In v5 is no longer available?

```php
$builder = new ContainerBuilder();

$container = $builder->build();
$obj = $container->get("ViaTrait");
```

The trait definition

```php
class MyClass {}

trait Classable
{
    /**
     * @Inject
     * @var MyClass
     */
    private $myClass;

    public function getMyClass()
    {
        return $this->myClass;
    }
}

class ViaTrait
{
    use Classable;
}
```

But

```php
$clazz = $container->get("ViaTrait");
$myClazz = $clazz->getMyClass(); //NULL
```

Here is the real failing test: https://travis-ci.org/wdalmut/frankie/jobs/74774839  - https://travis-ci.org/wdalmut/frankie/jobs/74774839

**Comment by mnapoli** [comment]
Hi, in v5.0 annotations are disabled by default, could it be the problem? Because not much has changed in the annotation system.

See [the migration guide](http://php-di.org/doc/migration/5.0.html).

**Comment by wdalmut** [comment]
Yep, i forgot to enable annotations. Sorry

Walter
