### ISSUE TITLE
Allow dependency injection in factory closures (?)

### ISSUE THREAD

**Issue by mindplay-dk** [PHP-DI/PHP-DI#292]
Just a thought...

Would it be possible to change [this](https://github.com/PHP-DI/PHP-DI/blob/master/src/DI/Definition/Resolver/FactoryResolver.php#L63):

    return call_user_func($callable, $this->container);

Into this:

    return $this->container->call($callable);

Thus enabling dependency injection in factory closures?

Allowing for much more expressive factory functions, e.g.:

```PHP
$container->addDefinitions([
    UserRepository::class => function (Connection $db) {
        return new UserRepository($db);
    },
    // ...
]);
```

Would that work?

Would save a lot of boilerplate in some of the more complex factory functions :-)

**Comment by mnapoli** [comment]
Hi! Absolutely a good idea, the only problem I'm afraid of is performances (maybe it's worth benchmarking it since the change would be fairly easy). This is reported and discussed in #197.
