### ISSUE TITLE
A non-serializable definition could be nested in a CacheableDefinition

### ISSUE THREAD

**Issue by mnapoli** [PHP-DI/PHP-DI#297]
Example:

``` php
    'foo' => \DI\object()
        ->constructor(DI\factory(
                function (ContainerInterface $c) {
                    return ...;
                }
            ));
```

`DI\object()` is cacheable, but it contains a non-serializable nested definition.

[`CacheableDefinition`](https://github.com/PHP-DI/PHP-DI/blob/master/src/DI/Definition/CacheableDefinition.php) will probably need to be removed and replaced with an method in Definition, e.g. `isCacheable()`.

**Comment by sagikazarmark** [comment]
I experienced the same with an env definition:

``` php
    'debug' => \DI\env(
        'APP_DEBUG',
        \DI\factory(function (string $env) { return 'dev' === $env; })
            ->parameter('env', \DI\get('env'))
    ),
```

Used a trick instead (which turned out to be better after all):

``` php
    'debug' => \DI\factory(function (string $env, ?string $debug): bool {
        if (null !== $debug) {
            return 'true' === $debug ? true : false;
        }

        return 'dev' === $env;
    })
        ->parameter('env', \DI\get('env'))
        ->parameter('debug', \DI\env('APP_DEBUG', null))
    ,
```

**Comment by mnapoli** [comment]
Thanks for the report, I haven't prioritized this issue so much until now because nobody reported any issue with that (and it's complex to solve ^^). I'll probably give it another look for v6!

**Comment by mnapoli** [comment]
Made obsolete by #494 (compiled container -> the cache is gone). The compiler also checks for these kinds of scenarios and correctly report them.
