### ISSUE TITLE
Class imports in traits are not considered when parsing annotations

### ISSUE THREAD

**Issue by holtkamp** [PHP-DI/PHP-DI#335]
When using annotation based dependency injection on a property of a Trait (accessibility does not matter: private, protected, public), it seems no aliases can be used:

With the FQCN, it works

```php
namespace Project\Traits;

trait MyTrait
{
  /**
   * @Inject
   * @var \Fully\Quallified\Class\Name
   */
  private $propertyName;
}
```

When using an alias, an error message is generated:

```php
namespace Project\Traits;

use Fully\Quallified\Class\Name as AliasName

trait MyTrait
{
  /**
   * @Inject
   * @var AliasName
   */
  private $propertyName;
}
```

Error-message: ```The @var annotation on Class::propertyName contains a non existent class "AliasName". Did you maybe forget to add a "use" statement for this annotation?"```, which seem to origin [here](https://github.com/PHP-DI/PhpDocReader/blob/21dce5e29f640d655e7b4583ecfb7d166127a5da/src/PhpDocReader/PhpDocReader.php#L128-L129)

I "guess" the parsing of use statements of the declaring class does not consider stuff that are defined in a trait?

https://github.com/PHP-DI/PhpDocReader/blob/21dce5e29f640d655e7b4583ecfb7d166127a5da/src/PhpDocReader/PhpDocReader.php#L102

I think not only the declaring class of the property should be considered, but also the traits that are used by that class with [ReflectionClass.getTraits()](http://php.net/manual/en/reflectionclass.gettraits.php)

**Comment by mnapoli** [comment]
Ah right, that's probably not a case handled by PhpDocReader… It might be worth looking into using https://github.com/phpDocumentor/TypeResolver or else that's something to fix in PhpDocReader :/

**Comment by holtkamp** [comment]
Mm, interesting package indeed. Might be useful. But I would say to first try to stay with native PHP, recursively iterate over all used Traits (potential performance thingie?). Note that [ReflectionClass.getTraitNames()](http://php.net/manual/en/reflectionclass.gettraitnames.php) can be used to determine the used Traits, but that it is not recursive by default, see 1st comment. 

Anyhow, not a bug issue, but good to report ;)

**Comment by mnapoli** [comment]
It has been fixed in https://github.com/PHP-DI/PhpDocReader/pull/7

**Comment by holtkamp** [comment]
confirmed, got it working now, thanks!

**Comment by mnapoli** [comment]
Thank you for testing, and thanks @thebigb for fixing this :)
