### ISSUE TITLE
Exclude classes from auto-wiring

### ISSUE THREAD

**Issue by ghost** [PHP-DI/PHP-DI#338]
Is it possible to define class strings in the container that should be ignored by the auto-wiring?

I have this annoying case where I have ZF2's container and PHP-DI together via Acclimate as one container, and there's a third party Zend module that's acting weird for `has()` returning true for a class I don't even use, then killing my script due to failure to actually instantiate that object.

I would like a bit of control and be able to tell PHP-DI that it shouldn't use auto-wiring for a certain class so that `has()` would return FALSE.

**Comment by mnapoli** [comment]
Unfortunately no it's currently not possible, this is something that is definitely worth adding.

**Comment by mnapoli** [comment]
After thinking about it I'd rather not add an additional option for such a specific need. I think that can be solved today by not using autowiring, or in v6 (if it contains the features I want to) by using `DI\autowire()` or something similar.
