### ISSUE TITLE
Method 'Container::call()' is not working for not indexed parameters

### ISSUE THREAD

**Issue by jaacoder** [PHP-DI/PHP-DI#339]
Hello, I am using PHP-DI version 4.4 and it seems that method **Container::call()** is not working for not indexed parameters. For example the code below is not injecting values for the two parameters **$a** and **$b**:

```php
$return = $container->call(function($a, $b) {
            return $a + $b;
        }, [10, 20]);
```

I did a patch that apparently solved the problem.
File: **ParameterResolver.php**
Lines: ~58 - 90

```php
$indexForNotIndexedParameter = 0; // PATCH VARIABLE INITIALIZATION
foreach ($functionReflection->getParameters() as $index => $parameter) {
            if (array_key_exists($parameter->getName(), $parameters)) {
                // Look in the $parameters array
                $value = $parameters[$parameter->getName()];
            } elseif ($definition && $definition->hasParameter($index)) {
                // Look in the definition
                $value = $definition->getParameter($index);
            } else {
               // PATCH STARTS HERE
               // If the parameter is not indexed by name, try to retrieve by position
                if (array_key_exists($indexForNotIndexedParameter, $parameters)) {
                    $args[] = $parameters[$indexForNotIndexedParameter++];
                    continue;
                }
                // PATCH FINISHES HERE

                // If the parameter is optional and wasn't specified, we take its default value
                if ($parameter->isOptional()) {
                    $args[] = $this->getParameterDefaultValue($parameter, $functionReflection);
                    continue;
                }

                throw new DefinitionException(sprintf(
                    "The parameter '%s' of %s has no value defined or guessable",
                    $parameter->getName(),
                    $this->getFunctionName($functionReflection)
                ));
            }

            if ($value instanceof EntryReference) {
                // If the container cannot produce the entry, we can use the default parameter value
                if (!$this->container->has($value->getName()) && $parameter->isOptional()) {
                    $value = $this->getParameterDefaultValue($parameter, $functionReflection);
                } else {
                    $value = $this->container->get($value->getName());
                }
            }

            $args[] = $value;
        }
```

Please, take a look at the code at **// PATCH VARIABLE INITIALIZATION** and code between **// PATCH STARTS HERE** and **// PATCH FINISHES HERE**.

I'd appreciate your attention in fixing this or telling me if I'm doing something wrong for this is not working with me. Thanks in advance.

**Comment by mnapoli** [comment]
Hi, this is good if it's working for you but this feature was implemented in 5.0. You can upgrade to the new version and it will be working without the patch.

Cheers!

**Comment by jaacoder** [comment]
I guess the not indexed parameter should be injected after all other parameters be injected except for the default parameter. If this is the meaning of not indexed parameters, I did a patch that apparently solved the problem:

**File:** NumericArrayResolver.php
**Lines:** 19-51
```php
class NumericArrayResolver implements ParameterResolver
{
    public function getParameters(
        ReflectionFunctionAbstract $reflection,
        array $providedParameters,
        array $resolvedParameters
    ) {
        // Skip parameters already resolved
        $notResolvedParameters = array_diff_key($reflection->getParameters(), $resolvedParameters);
        
        foreach ($providedParameters as $key => $value) {
            if (is_int($key)) {
                $resolvedParametersKey = key($notResolvedParameters);
                next($notResolvedParameters);
                
                $resolvedParameters[$resolvedParametersKey] = $value;
            }
        }
        reset($notResolvedParameters);

        return $resolvedParameters;
    }
}
```


**File:** Container.php
**Lines:** 328-334
```php
$parameterResolver = new ResolverChain([
                new DefinitionParameterResolver($this->definitionResolver),
                new AssociativeArrayResolver,
                new TypeHintContainerResolver($this->wrapperContainer),
                new NumericArrayResolver,
                new DefaultValueResolver,
            ]);
```

**File:** Invoker.php
**Lines:** 90-96
```php
private function createParameterResolver()
    {
        return new ResolverChain(array(
            new AssociativeArrayResolver,
            new NumericArrayResolver,
            new DefaultValueResolver,
        ));
    }
```

I'd like to receive your comments about...

**Comment by jaacoder** [comment]
I did update to version 5.1.0, but the order of the not indexed parameters still gerenate error. So, i did this patch above for you to comment about.

**Comment by jdreesen** [comment]
There are no non-indexed arrays in PHP. If you don't index them explicitely, they will be implicitely indexed by number and the `NumericArrayResolver` uses this integer index as the parameter position. 

So in your second example
```php
$container->call(function($n1, Application $app, $n2, Person $person) {
    return $a + $b;
}, [10, 20]);
```
the given arguments array `[10, 20]` equals `[0 => 10, 1 => 20]` which means `10` will be injected into `$n1` and `20` into `$app` (which will not work, because it is not of type `Application`). The third parameter `$n2` is not defined and `$person` will be resolved by its type hint.

Thus, the correct arguments array for this call would be: `[0 => 10, 2 => 20]`

**Comment by mnapoli** [comment]
Exactly what @jdreesen said. PHP-DI can't guess where you would want to inject `10` and `20` in `$n1, Application $app, $n2, Person $person`. Actually it could compare types and all but this would be wayyy too magical and unpredictable. It's much better to use parameter names or `[0 => 10, 2 => 20]` as mentioned above.

(for the record it seems you edited the original issue to replace PHP-DI "4.4" with "5.1.0", I'm just mentioning that so that any future reader isn't confused by the discussion)

**Comment by jaacoder** [comment]
Nice to see your comments. I agree with you both and @mnapoli got the main idea of this issue: PHP-DI can't guess if I meant [10, 20] or [0 => 10, 1 => 20] because, as @jdreesen said, PHP automatically index it numerically. So I wanna explain why I post this issue and make a suggestion for the framework.

I've used the term **not indexed** to reflect the same term PHP-DI documentation used in this [page] (http://php-di.org/doc/container.html) under the topic **call()** and to make myself clear when explaining my problem.

When we use DI one of the beauty is of course get our dependencies injected for us. And at the same time, I do not have to worry about the position of my parameters as in:

```php
$container->call(function (Logger $logger, EntityManager $em) {
    // ...
});
```

It will also work if I change parameters position:

```php
$container->call(function (EntityManager $em, Logger $logger) {
    // ...
});
```

Even if I pass some parameters in an associative array, the order doesn't matter:

```php
$container->call(function (Logger $logger, $dbHost, $operation) {
    // ...
}, [
    'operation' => 'delete',
    'dbHost'    => \DI\get('db.host'),
]);
```

It's a cool feature. But it's not working the same way with numerically indexed arrays, because PHP-DI can't guess what one meant. So I would like to suggest it to be configured globally or as another parameter in the **call()** function. I think the use of passing the position of the parameter as the index of the array should be rare and used in very few cases. Using the numeric array as a seed to inject values that can't be guessed other way by the cainter, I believe should be the general case and provides more flexibility.

For example, consider the code:
```php
$container->call(function (Application $app, $n1, $n2) {
    // ...
}, [10, 20]);
```

If the indexes of the array are not used as their position (and the patch above is a possible solution), I can call this like:

```php
$container->call(function ($n1, $n2, Application $app) {
    // ...
}, [10, 20]);
```

and also:

```php
$container->call(function ($n1, Application $app, $n2) {
    // ...
}, [10, 20]);
```

You may wonder it's not as a real case, but consider this array **[10, 20]** is not passed manually but it came from request or other means. If the index means the position, I have to always do a boilerplate in the code before calling that method to shift values in the array **n** positions forward. Consider another example:

```php
class MyController {
    public function sum(Application $app, Request $req, ...$numbers) {
        // ...
    }
}
```

And in my Rest API:

```php
$container->call([$controller, $method], $params);

```
It's just easier to use it without shifting the values. And if the function I'm calling is a method that I didn't previously known as if I was creating some sort of controller framework (as in the example), no matter if the user who create the method **sum** change it later to:

```php
class MyController {
    public function sum(Request $req, ...$numbers) {
        // ...
    }
}
```

It still doesn't break the calling. In this example, my API is calling a generic function that other user will create. I don't have control of creation or maintenance of the called function. This would provide more flexibility and requires less code than if I had to always do reflection to predict position before using **$container->call()** method.

What about using **options** to configure the container so that it might be possible without breaking existing code using **call()** ?

(Sorry for have editing the first comment. At that time, I haven't seen your reply)

**Comment by mnapoli** [comment]
I see what you mean and why you would need it. The thing is I'm not convinced of a solution that would be 100% reliable.

Take that example:

```php
$container->call(function (Foo $n1, Logger $logger, Foo $n2) {
    // ...
}, [new Foo(123), new Foo(456)]);
```

How can PHP-DI guess where to inject what? It's starting to become quite complex logic if we want to make it reliable. If you have an idea of how to implement it so that it's 100% reliable and predictable for users, then let's discuss it.

Also the logic of `Container::call()` is implemented in the [Invoker](https://github.com/PHP-DI/Invoker) library. If you want to add such behavior, you have to think of how to implement that [as a parameter resolver](https://github.com/PHP-DI/Invoker/tree/master/src/ParameterResolver). And by the way if you do implement it as a parameter resolver, you can also use that behavior in your code. I.e. the code is meant to be extensible, you are free to use it right now, maybe it's not worth adding it to core immediately.

**Comment by jaacoder** [comment]
Good point!

I'll try to implement it via parameter resolver (as you suggested) to solve the problem right now and think about a possible solution more general. If I achieve that (general solution), I'll show to you so you can think if it'll worth to add to core in future versions.

Thanks for your attention.
