### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by naneri** [PHP-DI/PHP-DI#340]
could you please create a repo with examples and put a link in the description.

**Comment by mnapoli** [comment]
There is https://github.com/PHP-DI/demo is that what you need? Also maybe you haven't noticed but the documentation is on a separate website: http://php-di.org/

**Comment by naneri** [comment]
Yes, I just could not find an example with a full aplication, now I see how it works. I could not understand how to use the variable $container until I saw this file - https://github.com/PHP-DI/demo/blob/master/web/index.php.  

Why don't you put the link to example project in the readme.md?

**Comment by mnapoli** [comment]
The readme only says:

> Read more on the website: **http://php-di.org**

I don't want to duplicate the documentation, I'd rather have one canonical source of information.. If you follow the link and read the "[Getting Started](http://php-di.org/doc/getting-started.html)" guide there's a mention of the demo at the end:

> If you want to use PHP-DI with another framework or your own code, try to use $container->get() in you root application class or front controller. Have a look at this [**demo application**](https://github.com/PHP-DI/demo) built around PHP-DI for a practical example.

Maybe the link to the demo could be in the sidebar though… I'll add it thanks for the feedback!
