### ISSUE TITLE
PHP5.4 documentation message

### ISSUE THREAD

**Issue by juliangut** [PHP-DI/PHP-DI#344]
In the documentation's definitions page it is stated that

> All the examples shown in this page are using a PHP 5.4 compatible syntax, but if you are using PHP 5.5 or 5.6 ...

Anyway in the examples below `::class` magic constant is extensibly used as in `Foo::class` and `FooFactory::class`

The message is misleading and should be removed or the examples accommodated to PHP5.4 accordingly

**Comment by mnapoli** [comment]
I'd rather have the warning fixed. PHP 5.4 is not maintained anymore. The definition syntax was optimized for PHP 5.5 and 5.6 [from the beginning](http://php-di.org/news/06-php-di-4-0-new-definitions.html), it deserves to be documented that way.
