### ISSUE TITLE
PHP 7.0 Support

### ISSUE THREAD

**Issue by Deserved** [PHP-DI/PHP-DI#352]
Hello,
Sorry if it duplicate, or I did a bad searching, but: Have PHP-DI 5.1 (Or older) been tested on PHP 7.0?
Thank you.

**Comment by mnapoli** [comment]
Hi, I have used it with PHP 7 and haven't noticed any problem. It's also tested continuously using Travis, the tests are green on PHP 7 since February: https://github.com/PHP-DI/PHP-DI/commit/bc9cdc2eb163e84d0028a71bfde7fcf286167665.
