### ISSUE TITLE
Wrapped containers aren't used if an item cannot be found in a definition source

### ISSUE THREAD

**Issue by diosmosis** [PHP-DI/PHP-DI#355]
I'm trying to integrate PHP-DI w/ Laravel and have run into a possible bug in PHP-DI. My first attempt to accomplish this involved creating an adapter for Laravel's `Container` interface => the interop `ContainerInterface`, then wrapping this container when building PHP-DI's container.

Unfortunately, this setup fails when trying to get objects that are in Laravel's container from PHP-DI's container. Here: https://github.com/PHP-DI/PHP-DI/blob/master/src/DI/Container.php#L117-L120, if there's no definition in the `definitionSource`, an exception is thrown. I'm under the impression that if there's nothing in the PHP-DI container, then the wrapped container should be checked, but my understanding might be incorrect.

For now, I've worked around it by using a DefinitionSource that wraps the Laravel container (it returns `ValueDefinition`s).

**Comment by mnapoli** [comment]
Hey Benaka!

The `wrapContainer()` method of the `ContainerBuilder` might be misleading: it isn't wrapping the container passed in the parameters, it's instead wrapping the container that will be built by the builder.

So if you want PHP-DI and Laravel to coexist you most probably need a parent "composite container" that will do the dispatch between both containers (or make your Laravel adapter act like a dispatcher between Laravel and PHP-DI => [that's what I do in the Symfony integration](https://github.com/PHP-DI/Symfony2-Bridge/blob/master/src/DI/Bridge/Symfony/SymfonyContainerBridge.php#L55-L63)).

Have a look at this example: http://php-di.org/doc/container-configuration.html#using-php-di-with-other-containers

**Comment by mnapoli** [comment]
FYI also have a look at this: https://github.com/jeremeamia/acclimate-container/blob/master/src/Adapter/LaravelContainerAdapter.php (though it's very simple, you might not need it).

**Comment by diosmosis** [comment]
> Hey Benaka!

Yo!

> The wrapContainer() method of the ContainerBuilder might be misleading: it isn't wrapping the container passed in the parameters, it's instead wrapping the container that will be built by the builder.

So it's there to help provide 2-way binding w/ the parent container?

> So if you want PHP-DI and Laravel to coexist you most probably need a root "composite container" that will do the dispatch between both containers (or make your Laravel adapter act like a dispatcher between Laravel and PHP-DI => that's what I do in the Symfony integration).

I looked at acclimate, but it doesn't implement Laravel's super mutable container interface, so I can't really get it to be used by Laravel (at least, eg, to use php-di to inject Controllers & such). Adapting both interfaces at the same time as in the Symfony bridge is do-able though, thanks for the hint!

**Comment by mnapoli** [comment]
No problem!

> So it's there to help provide 2-way binding w/ the parent container?

Yep, it's basically a way to make PHP-DI aware that it's wrapped by a parent container.
