### ISSUE TITLE
Drop support for PHP 5.4

### ISSUE THREAD

**Issue by mnapoli** [PHP-DI/PHP-DI#361]
PHP 5.4 support has been dropped for a long time, new frameworks like Slim or Zend-Expressive do not support it at all, Symfony 3 either. I'm considering dropping support for the next minor version. Feel free to comment with your thoughts.

**Comment by bradynpoulsen** [comment]
+1

**Comment by mnapoli** [comment]
That's what I used to think but Doctrine and other projects are dropping support for some PHP versions without going up a major version. See also this: https://twitter.com/Ocramius/status/672806796826931200 So I'm considering doing the same and letting Composer do its job…
