### ISSUE TITLE
Inheritance and 'duplicate' use of private properties

### ISSUE THREAD

**Issue by holtkamp** [PHP-DI/PHP-DI#366]
Suppose I have the following classes

```php
class A
{
    /**
	 * @Inject
	 * @var \Project\Repository\ProductRepository
	 */
    private $productRepository;
}

class B extends A
{
    /**
	 * @Inject
	 * @var \Project\Repository\ProductRepository
	 */
    private $productRepository;
}
```

The B::$productRepository seems not to be injected.

Of course one can argue that A::$productRepository should be protected, but still, it should not affect the way DependencyInjection works right?

PS, tried to add a test-case to ```DI\Test\IntegrationTest\InheritanceTest```, but could not get the DataProvider up and running properly...

**Comment by mnapoli** [comment]
Thank you I managed to reproduce it, I'm looking into it.

**Comment by mnapoli** [comment]
Pull request for tests and fix: #367

**Comment by mnapoli** [comment]
I released the fix, thanks for the report!

**Comment by holtkamp** [comment]
thanks! Upgraded to https://github.com/PHP-DI/PHP-DI/tree/5.2.1 and the child's private properties are also injected properly :+1: .
