### ISSUE TITLE
ZF2 bridge Bug - Cache factory can not return null

### ISSUE THREAD

**Issue by mmizera** [PHP-DI/PHP-DI#368]
Hi

\DI\ZendFramework2\Service\Cache\CacheFactory in createService method can return null, but ZF2 ServiceLocator does not allow this behaviour - you'll get this :

\Zend\ServiceManager\ServiceManager @ 953
if ($instance === null) {
            throw new Exception\ServiceNotCreatedException('The factory was called but did not return an instance.');
        }

ZF2 version Im using is current stable ("zendframework/zendframework": "~2.5").

Proposed fixes : 
Add some 'BlackholeCache' as default service returned via DiCache factory

**Comment by mnapoli** [comment]
Hi, thank you for the report! Sorry for the trouble but could you reopen this ticket in this project: https://github.com/PHP-DI/ZF2-Bridge Another person is maintaining it, so I think it will have more chances to be fixed.

Thanks!
