### ISSUE TITLE
Using PHP 7.1-dev throws fatal error in ClassDefinitionResolver.php

### ISSUE THREAD

**Issue by RyanNerd** [PHP-DI/PHP-DI#377]
PHP Fatal error:  Cannot use lexical variable $parameters as a parameter name in ...
[php-di/src/DI/Definition/Resolver/ClassDefinitionResolver.php on line 146](https://github.com/PHP-DI/PHP-DI/blob/4.x/src/DI/Definition/Resolver/ClassDefinitionResolver.php#L146)

The variable name $parameters is not permitted in PHP 7.1

**Comment by mnapoli** [comment]
Hoho that's a nice one! I hope it's just a bug with PHP 7.1 and not something real, because if we can't name a variable `$parameters` it will be an issue with a lot of projects ;)

Maybe you could try reporting it to https://bugs.php.net/report.php ?

Also I notice you use PHP-DI 4, I'm curious if you have tried updating to v5 and if there was something preventing you?

**Comment by RyanNerd** [comment]
I've placed a query into the PHP dev team about this issue. I built PHP 7.1-dev from source and quite a bit of changes lately have to do with determining reserved words and locking them down -- which of course is going to cause many Breaking Changes. I'll let you know of any response I get from them, but so far I don't think this is going to be ruled a bug -- but I hope I'm wrong.

I thought I was using the latest php-di version. Thanks for letting me know. I'll upgrade and let you know my experience. 

I **love** your DI library.

**Comment by mnapoli** [comment]
Thanks for reporting the bug, I'd love to know if you hear an answer indeed. And thanks for the support :)

**Comment by RyanNerd** [comment]
I've not heard back from the PHP dev team. I did upgrade to v5 of php-di and the fatal error is no longer being thrown. I think this issue should be marked as resolved (by upgrading to v5). I'll keep my eye on it and forward you any response from the PHP dev team. 
Most developers are not living on the bleeding edge like myself running the latest unstable PHP version. I'm just trying to stay ahead of the curve.
