### ISSUE TITLE
Ability to make @Injectable annotation mandatory

### ISSUE THREAD

**Issue by mmizera** [PHP-DI/PHP-DI#381]
Ability to make @Injectable annotation mandatory (via container configuration) - after that, you must explicitelly specify, that this object is Service and it must be obtained exclusivelly via container. 

Read-only items (e.g. classes from 3rd party library) can be added only through factories (callbacks, factory class) or you can add a 3rd option - autowire class/namespace

Benefits:
* better traceability across your project classes, you can define, what can be provided via container
* programmer can explicitelly state his/her intention for concrete object

**Comment by mnapoli** [comment]
Here is what I understood: you want PHP-DI to be able to load:

- services defined in configuration: *yes*
- services that have the `@Injectable` annotation: *yes*
- services that are not configured and don't have an annotation: *no*

Is that correct?

If it is, that might not be too complicated, this might need a change: https://github.com/PHP-DI/PHP-DI/blob/master/src/DI/Definition/Source/AnnotationReader.php#L262-L264 (plus adding an option on the ContainerBuilder).

**Comment by mmizera** [comment]
Yes, that is correct.

**Comment by mnapoli** [comment]
I'm sorry but after thinking about it I'd rather decline this for now. My goal for PHP-DI 6 (and next v5 versions) is simplification, so I'd rather avoid adding new options and different behaviors.
