### ISSUE TITLE
Enhance injecting configuration/scalar values

### ISSUE THREAD

**Issue by mmizera** [PHP-DI/PHP-DI#383]
@Resource('foo.bar.baz')

as @Inject annotation injects service, @Resource could inject scalar values. Yes, I know you can @Inject('anything.under.this.key'),

anyway ... @Resource should definitelly give you more possibilities, such as :

-  ability to read multilevel arrays via dot notation, e.g. @Resource('foo.bar.baz') should look inside $config['foo']['bar']['baz']
			for target value to inject

-  ability to enforce scalar value type - via @var : exact (@var string), multiple @var string|array, or not, if @var mixed

-  optional resources - @Resource(value="foo.bar.baz", optional=true) // if not found, no error and field will hold it's default value

**Comment by mnapoli** [comment]
Hi, thank you for the ideas. What's possible with annotations needs to be possible with the rest of the API of the container:

- "ability to read multilevel arrays via dot notation": this is something to implement globally, not just in a specific annotation (see for example #319)
- "ability to enforce scalar value type": I think I don't see what you mean, also how wouldn't it be possible with `@Inject`?
- "optional resources": same here, such feature needs to be thought globally, and I don't see a reason why it wouldn't be compatible with `@Inject`?

**Comment by mmizera** [comment]
Hi

Thanks for reply. 

Point 1 - I agree, #319 looks exactly what I want. 
I only mentioned @Resource annotation, because I thought of separating resources (some scalar value - mainly application configuration) and Services might be a good idea.

Point 2 - This is basically type validation. Simillar, as it works for injecting services. If you write @Inject and @var FooService, container will look for FooService. In case of Resources - @Inject('db.host') @var string I would expect Exception, if db.host is not string. For multiple allowed types @var string|string[], for any type e.g. @var mixed - but this is feature from 'nice to have' cathegory

Point 3 - same as 1, I have no objections for not separating services and resources.

**Comment by mnapoli** [comment]
:+1: 

I've opened #385 for point 3.

For point 2 I'm not sure if it falls under the scope of what a container should do. Also if we were to enable such check it would be a big BC break (I don't like adding too many options to preserve the ease of use of the package), and it might have a performance impact. It might be useful in `dev` environment to have the container perform some extra validation, but not by default I think.

**Comment by mnapoli** [comment]
Same here I'll close because this issue boils down to:

> `@Inject('db.host') @var string` I would expect Exception, if db.host is not string

And that's not something I plan on adding in the near future.
