### ISSUE TITLE
Can't have two different DIC objects easily?

### ISSUE THREAD

**Issue by woodywould** [PHP-DI/PHP-DI#386]
(apologies if this is the wrong place, I can't see a PHP-DI forum or similar?)

I was running some tests, whereby I have two container classes, each facading an instance of  PHP-DI container.

$phpDiContainer;
$myPhpDiContainer;

In the get($id) method of one of these, if this is the first ever attempt to resolve this class ($id), 
I want to perform some additional checks against the resolved object, before returning it (I'm doing this to see if I can replace the legacy container/locator class in our apps, which does similar checks after creating the object for the first time).

As far as I can tell, once I have  created the $phpDiContainer, there is no way to create a new, distinct one for $myPhpDiContainer, as the builders always return the same instance.

Is there a way to create a brand new container object, i.e not treat the container itself as a singleton, via the container builders? Or do I need to call the Container constructor directly?

**Comment by mnapoli** [comment]
Hi! This is the right place to ask :)

There is no reason you wouldn't be able to create 2 container instances, either using `new` (which can be a bit tedious because you have to pass all the parameters) or using a container builder. Here is an example using **the same** container builder:

```php
$builder = new DI\ContainerBuilder();
$container1 = $builder->build();
$container2 = $builder->build();
```

Those will be 2 different and separate containers. If you call `$container1->get('abc')`, it will not be the same object as `$container2->get('abc')` (assuming `abc` is configured to return an object).

You can also, if you want, use 2 different container builders (for example to have a different configuration).

**Comment by woodywould** [comment]
Thanks for clarifying, you're totally right - I think the source of my confusion is the intention of the Container Interop 'has' method. 

This is what I was expecting:

```
$builder = new \DI\ContainerBuilder();
        $container= $builder->build();
        $this->assertFalse($container->has('\Elwood\Foo'), 'has will ever return false');

```

This assertion fails, so I assume 'has' is more along the lines of 'canHave, if you decide to get()' ?

My goal is to perform some post-retrieval logic on an object the first time it's resolved from the container.

Specifically, I need to support some existing class hierarchies which I can't modify, which have setup() methods that need to be called after first construction.

Maybe I can't do this via the interop interface, but perhaps there's a better way to do it in PHP-DI directly?

Thanks in advance for any ideas on the best approach here!

**Comment by mnapoli** [comment]
> so I assume 'has' is more along the lines of 'canHave, if you decide to get()' ?

Yes.

> which have setup() methods that need to be called after first construction.

You can define your container entries using a factory (http://php-di.org/doc/php-definitions.html#factories) or by using `DI\object(...)->method(..)`  (see http://php-di.org/doc/php-definitions.html#objects).

> Maybe I can't do this via the interop interface, but perhaps there's a better way to do it in PHP-DI directly?

There are 2 sides to a container : first you configure the entries, i.e. how they will be constructed. Container-interop interfaces are not related to this. Second you fetch entries from the container: that's where you use the interop interface.

Do you use a framework? There are also integrations you can use to avoid having to get entries from the container and perform dependency injection everywhere (which is a cleaner).

**Comment by woodywould** [comment]
Thanks for explaining.
I'm trying to incorporate modern DI in a existing codebase, as seamlessly as possible. 
I'd prefer not to define all these pre-existing entries again.

Basically what I want to do is 

```
if($firstTimeEntryWasFetched && $resolvedInstance instanceof SomeClass) $resolvedInstance->setup()

```
But I can't work out how to set $firstTimeEntryWasFetched , so I don't call setup() twice on an instance.

I'll keep digging :)

**Comment by mnapoli** [comment]
You can only do this with definitions as I mentioned previously. If you don't want to do it for all your classes, you can use wildcards:

```php
return [
    '*' => function ($container, RequestedEntry $r) {
        $class = $r->getName();
        $resolvedInstance = new $class();
        $resolvedInstance->setup();
        return $resolvedInstance;
    }
];
```

Have a look at the documentation: http://php-di.org/doc/php-definitions.html#wildcards

**Comment by mnapoli** [comment]
To be more explicit: there is no way to know if this is the first time an instance is fetched when you call `Container::get()`.

**Comment by mnapoli** [comment]
I hope that answered your questions, let me know if you have others :)
