### ISSUE TITLE
Misleading Exceptionmessage when using the object definition helper with a non existing class

### ISSUE THREAD

**Issue by mopahle** [PHP-DI/PHP-DI#388]
`\DI\object(NonExistingClass::class)->constructorParameter('foo', 'bar)`
gives the  exception message "Parameter with name 'foo' could not be found". 
The real cause of the exception ("Class NonExistingClass does not exist") is dropped in ObjectDefinitionHelper::fixParamter() when catching the ReflectionException.

**Comment by mnapoli** [comment]
Good catch thank you! This is definitely something to improve, feel free to submit a pull request if you have time.

**Comment by mnapoli** [comment]
Fixed in #389
