### ISSUE TITLE
@inject does not work on Amazon ECS

### ISSUE THREAD

**Issue by kocsismate** [PHP-DI/PHP-DI#393]
Hey,

I have just deployed my Docker based application to Amazon ECS using an ECS optimized AMI, but I had to notice that all those dependencies of my controllers were null which were injected with annotations. After some debugging I managed to find the very issue:

As I was not aware before that annotations are case-sensitive (I guess it's because of case-sensitivity of certain file systems) I wrote `@inject` everywhere instead of `@Inject`. After correcting this problem, everything worked as expected.

I suggest adding some hints about the case-sensitivity of annotations in the proper section of the documentation. I'll open a PR for this soon.

**Comment by mnapoli** [comment]
Thank you!
