### ISSUE TITLE
PHP-DI 6 ideas

### ISSUE THREAD

**Issue by mnapoli** [PHP-DI/PHP-DI#395]
**Must haves:**
- **minimize BC breaks** as much as possible (upgrading should be easy!) - when I say "rename" below, I mean we keep the old names to preserve BC but we deprecate them
- drop support for PHP 5.4 #361 
- solve the `object()` helper that does too much and is too magic

What about PHP 5.5?

**Main ideas:**

Support PHP 7 and above only?

Remove scopes: #409 

Rename a few helpers to actions:
- `factory()` -> `call()`
- `object()` -> `create()`

This is hopefully clearer on what will actually be done by the container.

Same for `object()` methods (though I'm a little less convinced of the gain vs effort to migrate):
- `->constructor(...)` -> `->parameters(...)`
- `->method(...)` -> `->call(...)`

`object()` is too magic (#294 extends autowiring and other definitions). We can split its behavior into:
- `create()`: create an object, doesn't extend autowiring or a previous definition
- `autowire()`: create an object using autowiring, also allows to set some parameters/method calls
- `extend()`: extend the previous definition to override constructor parameters/method calls #279 (**it might even be removed altogether**)

It will be much clearer (less surprises is always better), and we'll be able to add support for "explicit autowiring" where you only get autowiring when using `autowire()` (optional of course), which I think is really good when you don't want too much magic.

Add a way to set parameters on `call()` (#362, #239): `call(function (...) {...})->parameters(get('abc'), get('def'))`.

**Other ideas:**
- migrate the cache to PSR-6? #376 

**Summary:**

``` php
return [

    'foo' => get('bar'),

    'foo' => env('FOO'),

    'foo' => string('{root}/test.txt'),

    'foo' => create(MyClass::class),
    MyClass::class => create(),
    MyClass::class => create()
        ->with('param1', get('foo'))
        ->call('setLogger', get(Logger::class)),
    '*Repository' => create('*DoctrineRepository'),

    'foo' => autowire(MyClass::class),
    MyClass::class => autowire()
        ->parameters(get('abc')),
    MyClass::class => autowire()
        ->parameter('param1', get('abc')),
    MyClass::class => autowire()
        ->call('setLogger', get(Logger::class)),

    'bar' => extend('foo')
        ->parameter('param2', get('def')),
    'bar' => extend()
        ->call('setLogger', get(Logger::class)),

    'foo' => call(function () {
        return 'bar';
    }),
    'foo' => call([Factory::class, 'method']),
    'foo' => call([Factory::class, 'method'])
        ->parameters(get('abc')),
    'foo' => call([Factory::class, 'method'])
        ->parameter('param1', get('abc')),

    'api' => decorate(function ($previous, $c) {
        return new CachedApi($previous);
    }),

    'log.handlers' => [
        get(StreamHandler::class),
        get(EmailHandler::class),
    ],
    'log.handlers' => add([
        get(SyslogHandler::class),
    ]),

];
```

**Internal changes:**

The configuration array could be turned into an AST and visitors could be applied (to turn it into a proper definition array). Then the resulting processed array of definitions could be cached.

Autowiring and annotation reader might not be "definition source" anymore (so much trouble from the beginning because of this).

That should solve problems of definitions nested in others (#297, #343), making caching easier and much more efficient (cache one array instead of each definition separately), maybe open the door for AST extensions, maybe open the door to compiling? It will also allow "validation passes" for dev environment (e.g. #243).

That config-to-AST part could be written as a separate package. It allows to write any configuration using PHP arrays, it could be useful. For example I needed exactly that for a framework and started a draft of such a thing (https://github.com/stratifyphp/framework/tree/master/src/Config).

**Feedback and ideas are welcome!**

**Comment by cisco87** [comment]
I think one cool thing to have here would be the opportunity to add interceptors when mapping a class. Like the UnityContainer extension from C#. Pratically, if you have a class like UserRepository, you can register it with something like CacheInterceptor. When the container is asked to resolve the dependency then it returns a class which is created on the moment, respecting the extends, implementing the same interfaces and having the same methods, but each method calls the interceptor object before the target class methods, so that you can perform operations before the target class is actually invoked

**Comment by mnapoli** [comment]
@cisco87 this is the [decorator pattern](https://en.wikipedia.org/wiki/Decorator_pattern). You can already do this, see this documentation: http://php-di.org/doc/definition-overriding.html#decorators The example you gave is similar to what's in the documentation ;)

**Comment by busywebservices-deployment** [comment]
@mnapoli it'd be cool to have the `create()->with()` functionality when using `call()->with()` (whether it be from `create()->call()` and just `call()` if `factory()` were to be renamed).

**Comment by mnapoli** [comment]
@busywebservices-deployment I'm not sure I understand what you mean?

**Comment by bradynpoulsen** [comment]
Sorry I just realized I was signed into the wrong account. For consistency, it'd be cool if I could use the `parameter()` method when specifying method calls (just like the new `call()` that'll be replacing `factory()`)

**Comment by mnapoli** [comment]
I see, do you have this in mind?

```php
return [
    'foo' => object('Abc')
        ->call('setThing')->parameter(123, 456),
];
```

That prevents to do something like this though:

```php
return [
    'foo' => object('Abc')
        ->call('init')
        ->call('initSomethingElse'),
];
```

**Comment by hidehalo** [comment]
feature autowiring is crazy awesome,I love it!

**Comment by predakanga** [comment]
Two things that would be nice for the future:

Lazy factories - would require specifying the class name/interface, but would be very helpful for things like injecting database connections

Composition support - this is a bit out there, but it would be useful to be able to define injections on traits. For instance, I can't use [ContainerAwareTrait](https://github.com/symfony/dependency-injection/blob/master/ContainerAwareTrait.php) because it doesn't use the @Inject annotation. At the minute, the only options are to copy ContainerAwareTrait and add the annotation, or add a methodInjection on every single class that uses the trait

**Comment by mnapoli** [comment]
@predakanga regarding "composition": 👍  that sounds very close to the `extend()` helper I mentioned. (however I can't say it's good to encourage using `ContainerAware`)

**Comment by robcapo** [comment]
One thing I'd love to see is the ability to set constructor parameters based on type instead of parameter name. For instance:

```php
return [
  'FooPackage\*' => object()
    ->constructorParamType(PDO::class, get('foo.package.db')
];
```

I'm still learning about PHP-DI, so please let me know if this is already possible.
Thanks!

**Comment by Taluu** [comment]
Hum, and why PHP 5.5, as it's already dead ? How about php 5.6 or php 7 ?

**Comment by mnapoli** [comment]
@robcapo the parameter type idea is good, I like it.

@Taluu at that point I guess supporting PHP 7 and above makes sense, there is a wide adoption and since Symfony 4 and Laravel 5.5 are going that way then it sounds perfectly safe to follow them.

**Comment by mnapoli** [comment]
See [this comment](https://github.com/PHP-DI/PHP-DI/issues/279#issuecomment-269176614) in #279, `DI\extend()` could even be removed. That would simplify a lot of things internally, and also even for users. @cogentParadigm suggests writing function helpers instead of having a whole concept of reusable abstract definitions. I like that idea a lot, it could be added to the docs.

**Comment by bradynpoulsen** [comment]
Huge +1 for functional definition reuse instead of `DI\extend()`. I'm not sure I have ever used extend in a good use case before.

Something else that would be nice is if we could define the parameters of constructors or functions flexibly:
 - By name (supported) `->constructorParameter('arg1', get('foo.bar'))`
 - By type (proposed) `->constructorParameterType(PDO::class, get('database'))`
 - By position `->constructorParameter(1, get('foo.bar'))`

## By Position

Many times when I am reading API references, I am often given examples of providing specific values as the 2nd parameter (for example).
```php
class A
{
    public function __construct(string $foo, array $bar)
    {
        // ...
    }
}
```
Using these definitions
```php
object()->constructorParameter(1, [ ... ]);
// vs
object()->constructorParameter('bar', [ ... ]);
```

By defining positional arguments, we can instead rely on API signatures instead of implementation details. This ensures that our definitions still work even if something as small as a renamed variable (which should be an implementation detail) occurs but behavior stays the same:
```php
// if the variable names changed in a minor/patch release
class A
{
    public function __construct(string $name, array $details)
    {
        // ...
    }
}
```
Our original definitions would be broken
```php
object()->constructorParameter(1, [ ... ]);
// vs
object()->constructorParameter('bar', [ ... ]); // broken
object()->constructorParameter('details', [ ... ]);
```

**Comment by bradynpoulsen** [comment]
I have been thinking about the composition idea. The trait idea is a hard one since it would require annotations to even work, but perhaps something to support parent classes and interfaces (via [class_implements](https://php.net/manual/en/function.class-implements.php) and [class_parents](https://php.net/manual/en/function.class-parents.php)) with something like `compose()` which would allow definitions similar to `create()` minus the object instantiation.

```php
use function DI\compose;
use function DI\get;

class MyClass implements DatabaseAwareInterface, LoggerAwareInterface { ... }

return [
    DatabaseAwareInterface::class => compose()
        ->call('setDatabase')->parameters(get('db.connection')),
    LoggerAwareInterface::class => compose()
        ->call('setLogger')->parameters(get('monolog')),
    AbstractDatabaseConnection::class => compose()
        ->parameters(get('db.dsn'), get('db.user'), get('db.password'))
];
```

Does the container definitions currently support a single class being composed of multiple definitions?

**Comment by bradynpoulsen** [comment]
@mnapoli If `DI\extend` is removed, it feels like the `DI\decorate` helper should be removed, too.

Are there any alternates to achieving the following?
```php
return [
    ProjectRepository::class => decorate(function ($repo) {
        return new CachedRepository($repo);
    })
];
```

This is a few approaches that come to mind but the first few seem like they would cause a circular dependency
```php
return [
    // Using call()
    ProjectRepository::class => call(function (ContainerInterface $c) {
        return new CachedRepository($c->get(ProjectRepository::class));
    }),

    // Using create()
    ProjectRepository::class => create(CachedRepository::class)
        ->parameters(get(ProjectRepositories::class)),

    // Will function, if you don't mind using work around verboseness
    'original.project.repository' => autowire(ProjectRepository::class),
    ProjectRepository::class => create(CachedRepository::class)
        ->parameters(get('original.project.repository')),

    // Alternate of the same thing in one line instead, if it would be supported
    ProjectRepository::class => create(CachedRepository::class)
        ->parameters(autowire(ProjectRepository::class))
];
```

**Comment by mnapoli** [comment]
@bradynpoulsen:

- setting parameters by position can be easy to implement (IIRC) and as you demonstrate it's a good use case, so +1 to add that

- setting parameters by type is often requested, why not but we'd have to see if it impacts performance a lot

- `compose()` is essentially `extend()` except it's done implicitly, I'm not a fan of that. I'm also not a fan of those `*Aware` interfaces or traits, but I have to admit they are widespread. On the other hand I don't want to make PHP-DI more complex/slower. The idea is noted anyway.

- `decorate()` is different from `extend()` and I don't see a reason to remove it, it's essential to modular systems. Re-implementing it through other methods (like you suggest, injecting/getting the container entry with the same name) would be less explicit and more confusing, I don't see a gain in doing that. The `decorate()` method (and its name, easy to search in the documentation) is pretty straightforward.

**Comment by bradynpoulsen** [comment]
* `decorate()` seems like a clone of `extend()`, except `extend()` interacts with the object definition itself whereas `decorate()` interacts with a resolved object.
  Concerning this example imported from the docs: 
  ```php
  return [
      ProjectRepository::class => decorate(function ($repo) {
          return new CachedRepository($repo);
      })
  ];
  ```
  How does it know how to instantiate the initial `ProjectRepository::class`? Does it just hope it can be autowired, or does it look at definitions that were provided for it earlier like `extend()`?

* I agree that `compose()` would introduce some more complexity. Too bad we don't have DI for the ContainerBuilder to use like a CompositionObjectResolver if composition is enabled ;) haha. I'm just interested if there are other ways to achieve this without having to support it explicitly while still keeping syntactic sanity haha
  ```php
  function databaseAware(ObjectDefinition $definition) : ObjectDefinition
  {
      return $definition->call('setDatabase')->parameters(get('db.connection'));
  }

  function loggerAware(ObjectDefinition $definition) : ObjectDefinition
  {
      return $definition->call('setLogger')->parameters(get('monolog'));
  }

  return [
      MyClass::class => loggerAware(databaseAware(create()))
  ];
  ```

**Comment by cogentParadigm** [comment]
Some way of applying a definition to multiple keys could help with cases like the *Aware interfaces. It could still be done by pre-processing definitions if we take a more object oriented approach to writing definitions. I'm not really familiar with PHP-DI internals so at least some of this is probably an over-simplification but here is an example of what I'm thinking.

```php
class DefinitionBuilder {
    protected $definitions = [];
    public function addDefinitions($keys, $definition) {
        if (!is_array($keys)) $keys = [$keys];
        foreach ($keys as $key) {
            $this->definitions[$key] = $definition;
        }
    }
    public function decorateDefinitions($keys, $callable) {
        if (!is_array($keys)) $keys = [$keys];
        foreach ($keys as $key) {
            $this->definitions[$key] = call_user_func($callable, $this->definitions[$key]);
        }
    }
    public function getDefinitions() {
        return $this->definitions;
    }
}
```

That would allow you to do something like this.

```php
class MyClass implements LoggerAwareInterface { ... }
class MyOtherClass implements DatabaseAwareInterface, LoggerAwareInterface { ... }

$builder = new DefinitionBuilder();
$builder->addDefinitions(
    [MyClass::class, MyOtherClass:class],
    loggerAware(create())
);
$builder->decorateDefinitions(MyOtherClass::class, 'databaseAware');
return $builder->getDefinitions();
```

You could take it even further and use class_implements to allow defining these at an abstract level but it would be a little bit more explicit than just wiring a definition to the interface directly, doesn't require any definition composition, and the above approach can still be used to keep it entirely explicit.

```php
//merge this into the above DefinitionBuilder
protected $interfaceDecorators = [];
public function addInterfaceDecorator($keys, $callable) {
        if (!is_array($keys)) $keys = [$keys];
        foreach ($keys as $key) {
            $this->interfaceDecorator[$key] = $callable;
        }
}
public function getDefinitions() {
    foreach ($this->definitions as $class => $definition) {
        foreach ($this->interfaceDecorators as $interface => $callable) {
            if (in_array($interface, class_implements($key))) {
                $this->definitions[$class] = call_user_func($callable, $this->definitions[$class]);
            }
        }
    }
}
```

That would allow something like this.

```php
$builder = new DefinitionBuilder();
$builder->addDefinitions([MyClass::class, MyOtherClass:class], create());
$builder->addInterfaceDecorator(DatabaseAwareInterface::class, 'databaseAware');
$builder->addInterfaceDecorator(LoggerAwareInterface::class, 'loggerAware');
return $builder->getDefinitions();
```

Once again, it's pretty trivial to implement this type of definition pre-processing even for 5.x.

**Comment by mnapoli** [comment]
@bradynpoulsen right I can see what you mean.

However decorate is much cleaner than `extend` in the sense that it's completely decoupled from the definition your are decorating. You are decorating, which is a like composition, whereas extend modifies the parent definition, which is like inheritance. And as always, "favor composition over inheritance".

> How does it know how to instantiate the initial ProjectRepository::class? 

It will look in previous config files, have a look at this documentation: http://php-di.org/doc/definition-overriding.html It's heavily used for modular systems.

> Too bad we don't have DI for the ContainerBuilder to use like a CompositionObjectResolver if composition is enabled ;)

But we do, DI is used everywhere in PHP-DI, you can extend the container in a lot of places ;) (maybe that comment was ironic, sorry if I missed that :p)

@cogentParadigm What you suggest is completely possible, it would be however very hard to optimize performance-wise. I want to remove as many components as possible internally to make the container as simple (and thus as fast) as possible, while keeping the existing features.

**Comment by mnapoli** [comment]
In #447 I drop support for PHP 5 and require PHP 7 (for PHP-DI 6.0).

Feedback welcome!

**Comment by mnapoli** [comment]
FYI `DI\object()` has been replaced by `DI\autowire()` and `DI\create()` in #449

**Comment by juliangut** [comment]
I'm seeing in [container-configuration](https://github.com/PHP-DI/PHP-DI/blob/6.0/doc/container-configuration.md) that PSR-6 or/and PSR-16 support haven't been added yet.

Do you still consider adding a standard cache interface? Doctrine's cache can be [wrapped](https://github.com/Roave/DoctrineSimpleCache)

**Comment by mnapoli** [comment]
@juliangut yes #376 is planned for v6.

**Comment by mnapoli** [comment]
Closing this issue now, thanks to all who participated.
