### ISSUE TITLE
ZF2 integration: config/module.config.php vs config/application.config.php ?

### ISSUE THREAD

**Issue by ChieftainY2k** [PHP-DI/PHP-DI#397]
Hello!
Just started using the PHP-DI, it's awesome! :-)

I think **http://php-di.org/doc/frameworks/zf2.html** seems to be wrong about the location of the ZF2 configuration file: "Register it in application_root/config/**module.config.php**" 

Shouldn't it be "**application.config.php**" :-) ?

Tom.

**Comment by mnapoli** [comment]
Hi! Thanks :)

I don't use ZF2 so I'll ping @Rastusik (who maintains the ZF2 integration) maybe he can answer you.

**Comment by Rastusik** [comment]
@mnapoli I pushed the fix into the zf2 bridge repo and I also made a pull request in the PHP-DI repo, so it's up to you now :)

**Comment by mnapoli** [comment]
#398 was merged, thanks for the documentation fix!

@ChieftainY2k thank you for the report!

**Comment by Rastusik** [comment]
@mnapoli thanks for the merge, and thanks for the report @ChieftainY2k
