### ISSUE TITLE
Question about autoloading / class preloader

### ISSUE THREAD

**Issue by rico** [PHP-DI/PHP-DI#400]
I have a question about how classes are loaded in DI - not even sure if it's the right place to ask.

Based on [ClassPreloader/ClassPreloader](https://github.com/ClassPreloader/ClassPreloader) I've implemented a mechanism to dump classes used in every request to a file which is the required along the composer autoload file

    // Autoload
    require __DIR__ . '/../vendor/autoload.php';

    // Dumped
    require __DIR__ . '/../bootstrap/classes.php';

Unfortunately I get error messages like the following when I try to `get` an instance form the container

    Fatal error: Cannot declare class [...], because the name is already in use in

It looks like the container tries to load the class a second time from the original file. Not even sure if this is a problem with DI or just something I do terribly wrong :-) But if you have any idea it would be great.

**Comment by mnapoli** [comment]
Mmh I don't think it's could be a problem with this library, PHP-DI doesn't mess with autoloading, except with the loading of annotations: https://github.com/PHP-DI/PHP-DI/blob/master/src/DI/Definition/Source/AnnotationReader.php#L228 Maybe that's the source of your problem?

If not then I guess it's with your system. In any case I don't think there's anything specific to change in this package, but if I'm wrong please let us know we'll fix it :)

In the meantime I'll close this ticket but feel free to continue the discussion.

**Comment by rico** [comment]
Thanks! The annotations caused the errors.
