### ISSUE TITLE
Constructor injection does not work when argument has null as default value

### ISSUE THREAD

**Issue by mmizera** [PHP-DI/PHP-DI#405]
Hi 

I found possible invalid behaviour in constructor injection - if constructor argument is object and has set null as default, inject does not work - e.g. 
@Inject
__constructruct(Foo $foo = null)

while if it does not, it works 
@Inject
__constructruct(Foo $foo)

In my opinion it should work in both cases

php-di version :     "php-di/php-di": "~5.0",

**Comment by mnapoli** [comment]
Hi, this is an expected behavior: `= null` means the argument is optional so PHP-DI treats it as such. In the end I think the decision between one or the other is not obvious, there are argument for both. But in my experience injecting automatically in optional parameters is way more problematic.
