### ISSUE TITLE
Propose to add PHP-DI to Zend Expressive documentation

### ISSUE THREAD

**Issue by bgaillard** [PHP-DI/PHP-DI#419]
Hi, I'm beginning to use Zend Expressive and saw a page dedicated to DI Container integration https://zendframework.github.io/zend-expressive/features/container/intro. 

I think it would be great to add PHP-DI here too, perhaps by proposing a description / a page to the guys who maintain Zend.

**Comment by mnapoli** [comment]
👍  that would definitely be great. I think the best course  of action would be:

- create the `Expressive-Bridge` like the other existing bridges (https://github.com/PHP-DI?utf8=%E2%9C%93&query=bridge)
- write documentation for http://php-di.org
- write a PR for Zend Expressive's documentation too (which would introduce PHP-DI and mostly point to the up-to-date documentation on http://php-di.org/)

That way it's consistent with existing bridges but at the same time it's consistent with Expressive's supported containers. 

If you want to have a go at it (I think Slim-Bridge should be a great starting point) I can create a new repo and add you as collaborator?

**Comment by juliangut** [comment]
Is this integration effort happening already?

**Comment by mnapoli** [comment]
Hi @juliangut, not at the moment but that would be interesting to see happening!

**Comment by holtkamp** [comment]
>If you want to have a go at it (I think Slim-Bridge should be a great starting point) I can create a new repo and add you as collaborator?

I think I can have a look at this... Can you already create the (empty?) repo, so I can clone it and work from there?

**Comment by mnapoli** [comment]
@holtkamp done, you should have collaborator access: https://github.com/PHP-DI/Zend-Expressive-Bridge

I've enabled Travis CI too, it should build if you push a `.travis.yml`

Good luck :)

**Comment by holtkamp** [comment]
@mnapoli ok thanks, got some initial tests working already. Will be on a vacation coming week, so little activity should be expected on the short term 😄

**Comment by holtkamp** [comment]
Pushed my initial ideas here: https://github.com/holtkamp/Zend-Expressive-Bridge/tree/develop

Doubts:
- how to deal with dependencies that might not exist? For example:
  - router, various libraries can be used: FastRoute, Aura.Router, zend-mvc Router
  - template engine, various libraries can be used: Plates, Twig, zend-view
- how to deal with global vs local configuration settings? It is probably the responsibility to override these settings, but at that point the PHP-DI container is already built...

For the current approach FastRoute and zend-view is used. But in case people use other ones, this approach breaks.

**Comment by mnapoli** [comment]
It seems to me there are 2 approaches:

- integrate PHP-DI and write modules for all routers and view libraries
- choose a router and a view library and make a package that allows to get started immediately, but doesn't necessarily allow to switch those components

> how to deal with global vs local configuration settings? It is probably the responsibility to override these settings, but at that point the PHP-DI container is already built...

I'm not sure I understand what you mean.

The 1st one seems quite ambitious, the 2nd solution seems more doable, and more in line with the Slim and Silex module.

FYI I think all this:

```php
    'Zend\Expressive\Whoops' => function (\Interop\Container\ContainerInterface $container) {
        $factory = $container->get(\Zend\Expressive\Container\WhoopsFactory::class);
        return $factory($container);
    },
```

can be replaced with this:

```php
    'Zend\Expressive\Whoops' => DI\factory(\Zend\Expressive\Container\WhoopsFactory::class),
```

in the config files.

**Comment by holtkamp** [comment]
Thanks for the pointer to \DI\factory(), never really understood it until now 😄 

>I'm not sure I understand what you mean.
Well, for example this line:
https://github.com/holtkamp/Zend-Expressive-Bridge/blob/9d34e434c30356ffb888305300d07c5fe7e7e81d/config/autoload/errorHandler.php#L12
In a production environment one should use a different handler, but probably also caching is applied. So the definition can not be updated at runtime when having this bridge already build the Container.

Additionally users will have a bunch of other Dependency Definitions for their own application. I now circumvented this by instructing the user to use the ContainerBuilder instead of already building the Container. See https://github.com/holtkamp/Zend-Expressive-Bridge/blob/develop/README.md

**Comment by holtkamp** [comment]
@mnapoli the configProvider of @elie29 is already integrated in the Zend Expressive skeleton installer:

`composer create-project zendframework/zend-expressive-skeleton expressive-project`

involves: 

```
  Which container do you want to use for dependency injection?
  [1] Aura.Di
  [2] Pimple
  [3] zend-servicemanager
  [4] Auryn
  [5] Symfony DI Container
  [6] PHP-DI
  Make your selection or type a composer package name and version (zend-servicemanager): 6
  - Adding package elie29/zend-phpdi-config (^3.0)
```

So this issue can probably be closed?

**Comment by mnapoli** [comment]
Oh nice! Thanks @elie29!

**Comment by elie29** [comment]
@mnapoli it would be nice if we spread the word by twitter that php-di is already integrated in the Zend Expressive skeleton installer.

**Comment by holtkamp** [comment]
Might be good to "resolve" the problem with ZendView before promoting it? Or at least we should name it. Currently it does not work out-of-the-box with ZendView as template rendering engine...

**Comment by elie29** [comment]
It is a problem related to zend manager service not to php-di. However, if you kick off the container first with the interop aliasing, you solve the problem.

**Comment by holtkamp** [comment]
>It is a problem related to zend manager service not to php-di

True, thought most people use ZendView when using Zend Expressive, but might be wrong. 

>However, if you kick off the container first with the interop aliasing, you solve the problem.

I did tried this suggestions, however it seems not to work. You seem to be more familiar with Zend Expressive, can you try a clean Zend Expressive Skeleton project which uses ZendView and apply that alias for the container to see if it works like that?

**Comment by elie29** [comment]
@holtkamp You are right the problem came from typehinting, for that reason, I created a ContainerWrapper that implements Interop as you suggested and passed to the ContainerBuilder. I had no problem to load zend view. The version [3.0.9](https://github.com/elie29/zend-di-config/releases/tag/v3.0.9) is released.

Thank you for your feedback.

**Comment by holtkamp** [comment]
thanks @elie29 for spending time on this, great to see this resolved in such an elegant way.
