### ISSUE TITLE
Can't use PHP magic methods for factory instantiation

### ISSUE THREAD

**Issue by lattwood** [PHP-DI/PHP-DI#422]
It would be nice to be able to use PhpDoc methods when specifying a factory callable. This would greatly reduce the verbosity of Aws configuration for us.

https://github.com/aws/aws-sdk-php/blob/master/src/Sdk.php#L7-L142

**Comment by mnapoli** [comment]
Hi, I'm not sure I understand. What do you expect to work and isn't working today?

**Comment by lattwood** [comment]
Doing this complains the method `createEc2` doesn't exist.

```
return [
    Sdk::class => object()->constructor(get('config.aws')),
    Ec2Client::class => factory([Sdk::class, 'createEc2'])
];
```

which is happening because (I assume) it's looking for a concrete method.

**Comment by mnapoli** [comment]
Ah I understand thank you! I'm not sure it's going to be an easy fix, I'll try to have a look at it this week. If you want to give it a look my guess is that the problem is in https://github.com/PHP-DI/Invoker more specifically (it tries to "validate" the callables before calling them).

**Comment by mnapoli** [comment]
I'm afraid it's not possible to support those magic methods easily. The best solution for now will be to improve the error message to help users understand the situation.

I've opened https://github.com/PHP-DI/Invoker/pull/11 for that

**Comment by artemmolotov** [comment]
Currently, we can use `Closure::fromCallable` as an explicit workaround, but the `$arguments` of the magic method always will be `empty array`. Example:
```php
return [
    Sdk::class => object()->constructor(get('config.aws')),
    Ec2Client::class => Closure::fromCallable([Sdk::class, 'createEc2'])
];
```

**Comment by SvenRtbg** [comment]
Am I thinking too easy? You can provide a closure function and do whatever is necessary in your code:

    return [
        Sdk::class => object()->constructor(get('config.aws')),
        Ec2Client::class => function(ContainerInterface $c) { return $c->get(Sdk::class)->createEc2(); },
    ];

Provide any required arguments to the `createEc2()` method as needed. You can pull it from the container just the same way.

You can go way beyond that simple one-liner if for example you need two or more objects

PHP-DI should be able to build everything, but it isn't able to build everything itself without developer support.
