### ISSUE TITLE
About PHPDI in PHP 5.4

### ISSUE THREAD

**Issue by rjsandim** [PHP-DI/PHP-DI#424]
I was trying to use PHPDI in a project of the company that I am working. There we use php5.4 ( we'll change for php 7 in this year, but now is php 5.4).

I think that I'm using PHPDI correctly , because when I change the config of server to php 5.5..it works magnificently.

I know that PHPDI 5.3 don't works with PHP 5.4, so I downgraded for PHPDI 5.2, but it stills not working.

Do you have some documentation for older version?

**Comment by mnapoli** [comment]
Hi, PHP-DI 5.2 requires PHP 5.4: https://github.com/PHP-DI/PHP-DI/blob/5.2.2/composer.json#L26

What errors do you have when using that version?

**Comment by rjsandim** [comment]
For example, I was trying to use configuration inside an array in a external file.

I was trying, at injections.php:

```
return [
	Teste::class => \DI\object()->constructor()->get(Teste2::class),
];
```

But, I saw that ::class only works in PHP >= 5.5.

And the documentation in the homepage says:

PHP 5.4 SHORT ARRAYS

```
return [

];
```

PHP 5.5 ::CLASS MAGIC CONSTANT

```
return [
    Foo::class => DI\object()
      ->constructor(DI\get(Bar::class))
];
```

etc.

So, I don't have to config it or there is no way to do it?

PS: I'm new at using this kind of containers, although of using DI almost always.

TY

**Comment by rjsandim** [comment]
Hi, It worked.

I have a class Teste that has at contructor an interface as dependency. And it works when I'm using this file:

```
<?php

return [
	'App\Controllers\Teste' => \DI\object()->constructor(DI\get('App\Controllers\Teste3')),
	'App\Controllers\Teste2'=> \DI\object()->constructor(),
	'App\Controllers\Teste3'=> \DI\object()->constructor(),
];
```

I saw at documentation that for interface to implementation binding  I can use:

INTERFACE-TO-IMPLEMENTATION BINDING

```
return [
    NotifierInterface::class => get(EmailNotifier::class)
];
```
But when I try:

config file
```
// working
<?php
return [
	'App\Controllers\Teste' => \DI\object()->constructor(DI\get('App\Controllers\Teste3')),
	'App\Controllers\Teste2'=> \DI\object()->constructor(),
	'App\Controllers\Teste3'=> \DI\object()->constructor(),
];
```
```
// not working
<?php
return [
	'App\Controllers\Teste' => DI\get('App\Controllers\Teste3'),
	'App\Controllers\Teste2'=> \DI\object()->constructor(),
	'App\Controllers\Teste3'=> \DI\object()->constructor(),
];
```
example:
```
<?php
namespace App\Controllers;

interface IMSG {
	public function menssage();
}

class Teste2 implements IMSG {
	public function menssage() {
		return 'injected Teste2';
	}
}

class Teste3 implements IMSG {
	public function menssage() {
		return 'injected Teste3';
	}
}

class Teste {

	private $teste;

	public function __construct(IMSG $t) {
		$this->teste = $t;
	}

	public function msg() {
		return $this->teste->menssage();
	}
}

class ClientController extends AppController{

	public function index() {
		global $container;

		$injection = $container->get('App\Controllers\Teste');
		echo $injection->msg();
	}
}

```

It don't work, could you give me an example about "INTERFACE-TO-IMPLEMENTATION BINDING"?

**Comment by mnapoli** [comment]
I think you want to do:

```
<?php
return [
    'App\Controllers\Teste' => \DI\object()->constructor(DI\get('App\Controllers\Teste3')),
    'App\Controllers\Teste2'=> \DI\object()->constructor(),
    'App\Controllers\Teste3'=> \DI\object()->constructor(),
];
```

I don't see why you would want to get `Teste3` when you do `$container->get('App\Controllers\Teste');`.

**Comment by rsandimbefore** [comment]
TY
