### ISSUE TITLE
@Inject does not work for factory parameters.

### ISSUE THREAD

**Issue by daiglej** [PHP-DI/PHP-DI#433]
Assuming I have a config like this : 
```
return [
    Psr\Log\LoggerInterface::class => function(DI\Container $di) {
        return $di->get(Psr\Log\LoggerInterface::class . '.main');
    },

    'Psr\Log\LoggerInterface.*' => function(DI\Factory\RequestedEntry $requestedEntry, LoggerFactory $loggerFactory) {
        // 24 === strlen('Psr\Log\LoggerInterface.')
        $name = $requestedEntry->getName();
        $namespace = substr($name, 24);

        // This return a Psr\Log\LoggerInterface that logs into the specific $namespace.
        return $loggerFactory->getLogger($namespace);
    }  
];
```

Then I can have a class like this : 
```
class myClass
{
    /**
      * @Inject({"Psr\Log\LoggerInterface.MyNamespace"})
      */
    public function __construct(Psr\Log\LoggerInterface $logger)
    {}
}
```

And when i do ```$myclass = DI\get('myClass');``` $myClass will be injected with a $logger that logs into the `MyNamespace` namespace.

However if I add this to my config.
```
return [
    'myClass' => DI\factory(['myClassFactory', 'create'])
];
```

With a factory class like this : 
```
class myClass
{
    /**
      * @Inject({"Psr\Log\LoggerInterface.MyNamespace"})
      */
    public static function create(Psr\Log\LoggerInterface $logger)
    {}
}
```

Then when doing And when i do ```$myclass = DI\get('myClass');``` $myClass **WILL NOT BE** injected with a $logger that logs into the `MyNamespace` namespace. But instead with one that logs into `main` (My defaut namespace aka a request ```DI\get('Psr\Log\LoggerInterface');``` instead of ```DI\get('Psr\Log\LoggerInterface.MyNamespace');```)

**Comment by mnapoli** [comment]
I'm not sure I understood how the first part of the description relates to the `myClass` declaration, but no indeed `DI\factory()` calls the given callable, it doesn't take `@Inject` annotations into account.

I don't think that's something that will change in the near future, annotations are sometimes OK but they are not meant to be used everywhere. Also calling a callable is a different use case than instantiating an object.
