### ISSUE TITLE
Cache from container

### ISSUE THREAD

**Issue by AydinHassan** [PHP-DI/PHP-DI#434]
Hi,

Would it be possible to specify the cache as an entry which exists in the container?

I already have a factory for a doctrine cache and would prefer not to copy paste the definition into my bootstrap file to configure the container cache.

Would it even be possible? it does sound like a circular dependency problem!

**Comment by mnapoli** [comment]
You mean configure in PHP-DI the cache that PHP-DI itself will use? Yes it's a common problem I've faced too :) a bit of a circular dependency.

What I usually end up doing is create the cache, create the container and then `$container->set(Cache::class, $cache)`. The only downside is that cache configuration is not in container config files, but I don't see a practical solution.

**Comment by AydinHassan** [comment]
Yeap! My current cache factory returns a different cache adapter based on some config setting (for example null adapter if disabled) and config comes from the container also. I wanted to tell PHP-DI to use that for its cache, but yeah doesn't look like that will work.

Thanks anyway!

**Comment by AydinHassan** [comment]
Went with https://github.com/php-school/phpschool.io/pull/43 - think that should be okay 😄
