### ISSUE TITLE
Optional route parameters depend on correct order

### ISSUE THREAD

**Issue by pontoffeltier** [PHP-DI/PHP-DI#439]
Something like this
`$app = new App;
$app->get('/[{name}]', function ($name = null, $response) {
    $response->getBody()->write('Hello ' . $name);
    return $response;
});`

would throw this exception

> Type: Invoker\Exception\NotEnoughParametersException
Message: Unable to invoke the callable because no value was given for parameter 1 ($name)
File: /var/www/html/public_html/vendor/php-di/invoker/src/Invoker.php
Line: 75

simply because the route parameter is declared before the $response

**Comment by mnapoli** [comment]
Hi, does it work if the parameter is declared after `$response`? To my knowledge optional parameters are supported at all.

**Comment by pontoffeltier** [comment]
Hi,
sorry, it was working the whole time, my testcase didn't account for 
stupidity: the name of the parameter changed so I had the wrong name....


Am 2016-09-12 07:56, schrieb Matthieu Napoli:
> Hi, does it work if the parameter is declared after `$response`? To my
> knowledge optional parameters are supported at all.

**Comment by mnapoli** [comment]
Haha no worries ;)
