### ISSUE TITLE
Annotations are not working as expected

### ISSUE THREAD

**Issue by jsternadel** [PHP-DI/PHP-DI#444]
Here is my simple test case:
`class BlacklistController
{
    /**
     * @Inject
     * @var JsonHydrator
     */
    private $hydrator;
    
    public function __construct($modelClass, $repository)
    {
        var_dump($this->hydrator);
        exit();
    }
}`

According to the documentation PHP-DI should be injecting an instance of the JsonHydrator into my class for me.  However the output of var_dump is always NULL.  I've read and re-read the documentation regarding annotations several times and I can't figure out what I'm doing wrong.  I know they are being parsed because if I do @var RandomClass and I get a PhpDoc exception.  Both the controller and hydrator classes have definitions in the container.  Do I need to remove the definition for the controller and only use annotations or will they work together?  I made the assumption they would work together.

**Comment by mnapoli** [comment]
Hi, this is a normal behavior: you are in the constructor. The constructor is automatically called by PHP when the object is constructed. PHP-DI must create the object first, and then it can inject dependencies.

So you can't use dependencies in the constructor.
