### ISSUE TITLE
Add hook to support object proxies

### ISSUE THREAD

**Issue by parisholley** [PHP-DI/PHP-DI#454]
Would be nice to introduce custom annotations (ie @transaction) that wraps method calls and can be handled by DI. Simple implementation could be to just allow adding a hook to DI\Container::resolveDefinition that optionally allows you to modify (proxy by reading annotations) before setting the singleton.

**Comment by mnapoli** [comment]
Hi, I think what you suggest is close to AOP, in that case here is the current status around that topic: https://github.com/PHP-DI/PHP-DI/issues/230#issuecomment-75893145
