### ISSUE TITLE
Running PHP-DI with APCu on a clustered hosting environment?

### ISSUE THREAD

**Issue by mishtershmart** [PHP-DI/PHP-DI#455]
Hi there,

I'm currently considering using PHP-DI for a large WordPress site. We basically have a core plugin, a whole bunch of feature plugins, then a theme. I'm thinking of using a DI container in the core plugin to keep things a little cleaner and help us in our unit testing, etc. 

This will be my first crack at using a DI container, so I was talking to our host, Pressidium, to see if we have APCu available and they suggested I reach out to you and see if PHP-DI using APCu in a clustered environment will work. Their comment on the matter;

> So, can you use PHP-DI with APCu on Pressidium? It really depends on what the library needs to achieve with caching. For example, if the library caches dependency injection configuration, so no configuration parsing occurs on every request, then APCu seems OK (and a wise decision IMHO), as the configuration is static and all application nodes (where your WordPress instance runs) work with the same configuration. If PHP-DI stores runtime information in the cache, which needs to be read and occasionally updated by all application nodes of your WordPress cluster, then APCu is not appropriate as cached values can't be synced across the cluster (in this scenario a RedisCache is more appropriate).

Now, I'm wondering – would it be a dire mistake to just not use caching in a production environment? If so, should we just go with Redis, or will APCu be fine on a cluster? 

Thanks in advance for the advice.

Cheers,
Phil

**Comment by mnapoli** [comment]
Hi, it's a good question (and your host seems to be understanding the situation quite well).

> For example, if the library caches dependency injection configuration, so no configuration parsing occurs on every request, then APCu seems OK (and a wise decision IMHO), as the configuration is static and all application nodes (where your WordPress instance runs) work with the same configuration

That's the case.

> If PHP-DI stores runtime information in the cache, which needs to be read and occasionally updated by all application nodes of your WordPress cluster, then APCu is not appropriate as cached values can't be synced across the cluster (in this scenario a RedisCache is more appropriate).

Not the case.

So all *should* be good and APCu is a good solution for you. Remember that what is cached is based on the code, so if the code changes you must clear the cache (and that is the case when you deploy the code in production).

However, if you do not plan on using annotations, then the performance difference between using `ArrayCache` (i.e. in-memory cache dropped every request) and `ApcCache` might not be significant. It's really hard to say in advance but containers usually take a very small part of the request time. For example if your pages (or API) execute in 100ms or more I would really not be concerned.

What kind of performances and traffic are you targeting?
