### ISSUE TITLE
Use ::class property to create objects

### ISSUE THREAD

**Issue by flancer64** [PHP-DI/PHP-DI#458]
"Create the objects" documentation [sample](http://php-di.org/doc/getting-started.html#3-create-the-objects) :

```php
$userManager = $container->get('UserManager');
```

I suppose this form is a slightly better:

```php
$userManager = $container->get(UserManager::class);
```

because code refactoring is a little bit easier in this case.

It is not an issuer, it is an documentation improvement probably :)

**Comment by mnapoli** [comment]
:+1: yes that's a better form indeed, however the getting started is meant to be as simple as possible so I'm afraid the `::class` notation could be confusing for those not used to it.

When you go into the [more detailed documentation](http://php-di.org/doc/php-definitions.html#syntax) the `::class` tip is explained.

**Comment by flancer64** [comment]
Thanks for the answer, Matthieu.

I use Magento 2 platform (framework?) for our apps and I have seen the mass refactoring of _'SomeClass'_ form to _SomeClass::class_ in DI usage. There are above 1M LOC in Magento 2 and there were a lot of _SomeClass_ forms. I also have used the simplest form in my code cause I have read "Getting started" only (this was other "getting started" and other lib), until some guy from stackoverflow pointed me to the right way :) I suppose there are a lot of people like me who read the "getting started" and then try to write the simplest code. It's just my oun opinion.

Thanks for the DI :1st_place_medal:
