### ISSUE TITLE
Generate proxies for all definitions results in a separate container configured to do so

### ISSUE THREAD

**Issue by holtkamp** [PHP-DI/PHP-DI#459]
As discussed in https://github.com/PHP-DI/PHP-DI/issues/457, it would be nice to be able to force generation of the proxy files for all definitions that involve lazy loaded objects. While trying to do this I encountered some behaviour I am trying to understand. 

**Approach**
Two separate Dependency Injection Containers are involved:

- `$dic1` used in the application itself, since we are running in a development/non-production environment, this container is not configured to write proxies to a file
- `$dic2`: a newly instantiated container (created by a separate ContainerBuilder) used in a Symfony Command "GenerateProxies", with exactly the same definitions, to be used to write the proxies, so when it is being assembled, this is set to true

The idea is to iterate over all definitions in $dic2 and load them, so the proxies are generated, also see https://github.com/PHP-DI/PHP-DI/issues/152#issuecomment-169946292 for the general idea. The strange thing is:

- `$dic2`: results in 320 proxies
- `$dic1` (when temporarily configured to write proxy files): results in 437 proxies

The process to add the definitions (1087x) is exactly the same so both containers have the same definitions.

**Difference**
When simply bootstrapping the application and not iterating all definition files, 117 proxy files are generated when `$dic1` is configured to write files to proxies. 437-320 = 117: exactly those files 'missing' when I try to force `$dic2` to generate the proxies. 

So apparently simply iterating all the definition files and fetch them from a **newly instantiated** DIC, does not result in proxy generation to be triggered. Any "explanation" for this? I would say since `$dic1` and `$dic2` are not related, new instances would be generated and therefore proxy generation would be forced. I am starting to think this is default behaviour of the proxy manager...

**Comment by holtkamp** [comment]
Think I found the cause of this behaviour: the configuration to write proxies to a file is not taken into account [when generating the classname for the proxy class](https://github.com/Ocramius/ProxyManager/blob/cce5477857504997baf3168974b8f1283516a686/src/ProxyManager/Factory/AbstractBaseFactory.php#L77-L85).

So for:
- `$dic1`, which should not write files to proxies, the generated class name is something like`ProxyClassName_Hash123.php`
- `$dic2`, which **should** write files to proxies, the generated class name is **also** `ProxyClassName_Hash123.php`

Since the classname is already loaded / in memory, the already generated proxy is used here: https://github.com/Ocramius/ProxyManager/blob/cce5477857504997baf3168974b8f1283516a686/src/ProxyManager/Factory/LazyLoadingValueHolderFactory.php#L47. 

When extending the considered proxy parameters, the generated classname (essentially the hash, which is based on the proxy parameters) is different:

```php
$proxyParameters = [
    'className'           => $className,
    'factory'             => get_class($this),
    'proxyManagerVersion' => Version::getVersion(),
    'proxiesTargetDir'    => $this->configuration->getProxiesTargetDir(), //Should the proxy be written to a file??
];
```

Now all 420 proxy files **are** generated by `$dic2`. So this seems not to be an issue with PHP-DI, but with the ProxyManager...

**Comment by mnapoli** [comment]
:+1: thanks for the summary
