### ISSUE TITLE
Drop container-interop support

### ISSUE THREAD

**Issue by mnapoli** [PHP-DI/PHP-DI#463]
Since PSR-11 has been accepted, container-interop support can be removed in the next major version.

Related: #461 (adding full PSR-11 support in PHP-DI).

**Comment by mnapoli** [comment]
TODO left: changelog

**Comment by Grafikart** [comment]
@mnapoli  I understand the need to "clean" the code but this change will break the compatibility with some frameworks that expects the container to implement the interop interface (for instance  Zend Expressive). 

Could we keep Interop interfaces for compatibility purpose. Using both Interop and PSR interfaces for Exceptions and Container ?

**Comment by mnapoli** [comment]
@Grafikart thanks for the feedback, this is indeed something I've been wondering about since the first alpha release…

I've opened #515 to continue the discussion and list potential problems.
