### ISSUE TITLE
Generic setter/method injections in code

### ISSUE THREAD

**Issue by pavarnos** [PHP-DI/PHP-DI#468]
Hi. Sorry if this is an FAQ: spent a while browsing the docs and the issues here...

Is there a way to add a generic pattern for setter or method injections? eg about 1/4 of my classes use an `EventDispatcherAwareTrait` which has a `setEventDispatcher(EventDispatcherInterface $dispatcher)` method. How can I tell PHP-DI that if it creates a class that that has a `setEventDispatcher` method, it should call `setEventDispatcher` with the appropriate `EventDispatcherInterface` instance?

I've seen the @Inject annotation. Wondered if there was a way to do this in in code rather then relying on annotations?

**Comment by mnapoli** [comment]
Hi, no indeed there is no clean way to do that. That's something that has been discussed a few times, and I'm not really keen on adding because it adds a lot of indirection.

What you could do though is write your own function helper. That's quite simple, and clear I guess:

```php
return [
    'foo' => eventListener(),
];

function eventListener(...$params) {
    return DI\object(...$params)
        ->method('setEventDispatcher', DI\get('event_dispatcher'));
}
```

**Comment by pavarnos** [comment]
Thanks for the quick answer. The attraction of PHP-DI is that I don't have to declare every class in advance: I can just ask the container for any class and it will figure it out. 

I'm currently using Symfony. The compiled file is 11,000 lines and represents about 1/4 of the final number of classes that need to be included. It is already taking several seconds to generate after each edit, so it is becoming unwieldy. Which is why PHP-DI is attractive: because I can configure the complicated / non standard classes and let container magic do the rest.

So: to benefit from the magic, what I need is a way to apply your function helper to a subset of the namespace. Would the following work if none of the Repository* classes are explicitly configured (if they all use magic)?

```php
return [
    'ISV\Repository\*' => addEventListener(),
];

function addEventDispatcher(...$params) {
    $object = DI\object(...$params);
    if (method_exists($object,'setEventDispatcher')) {
        $object->setEventDispatcher(DI\get(EventDispatcherInterface::class));
    }
    return $object;
}
```

**Comment by pavarnos** [comment]
... an alternative is creating a wrapper class that overrides `get()`, looks for the namespace pattern and calls `setEventDispatcher` where needed. But this is kinda ugly. I wanted to see if there was a natural way to do it already supported by PHP-DI...

**Comment by mnapoli** [comment]
> Would the following work if none of the Repository* classes are explicitly configured (if they all use magic)?

Yes but not as you put it, rather like this:

```php
return [
    'ISV\Repository\*' => addEventDispatcher(),
];

function addEventDispatcher(...$params) {
    return DI\object(...$params)
        ->method('setEventDispatcher', DI\get('event_dispatcher'));
}
```

> ... an alternative is creating a wrapper class that overrides get(), looks for the namespace pattern and calls setEventDispatcher where needed. But this is kinda ugly. I wanted to see if there was a natural way to do it already supported by PHP-DI...

That's not possible. I think you are confusing the fact that `object()` and `get()` helpers are modifying PHP-DI definition objects, not your final instances. The definition objects represent *how* to create your services. For example they have no `setEventDispatcher()` method.

**Comment by mnapoli** [comment]
Closing to keep the issue tracker organized but feel free to continue de discussion.
