### ISSUE TITLE
Internal classes cannot be instantiated

### ISSUE THREAD

**Issue by sagikazarmark** [PHP-DI/PHP-DI#470]
It's probably not a bug, but I think it worth noting (sorry if it already is): internal classes (like `Memcached`) cannot be instantiated as PHP-DI cannot determine their constructor parameters through reflection. I guess it also means that this is only true for classes with constructor parameters.

The solution is using a factory:

``` php
            \DI\factory(function($host, $port) {
                $memcached = new \Memcached();

                $memcached->addServer($host, $port);

                return $memcached;
            })
```

Again, I don't think this is a bug in PHP-DI, but it might worth to investigate what actually happens and write a few lines in the documentation.

**Comment by mnapoli** [comment]
Hi, yes it is "expected", PHP doesn't allow to use reflection on internal classes. There should be a clear exception in that case: https://github.com/PHP-DI/PHP-DI/blob/08afcf77c896db3900054d7e5f701811f1135748/src/DI/Definition/Resolver/ParameterResolver.php#L108-L109

**Comment by sagikazarmark** [comment]
Yeah, there is, but I couldn't find any references in the docs (not that I looked to hard). Just wanted to bring it up, feel free to close it.

**Comment by mnapoli** [comment]
Right! I'll leave this issue open, indeed that could be a good addition in https://github.com/PHP-DI/PHP-DI/blob/master/doc/autowiring.md#limitations

**Comment by Blackskyliner** [comment]
Alternatively as those interfaces change more rarely than often we could provide a lookup table which may be pluggable. So users which use not-so-often-used extensions could plug in the definitions of those... Just an idea though to circumvent the limitations and have a more streamlined usage w/o thinking about internal/external classes.

**Comment by mnapoli** [comment]
@Blackskyliner that could work but honestly that sounds a bit overkill to me given there are very good workarounds (configuring the class without autowiring).

**Comment by sagikazarmark** [comment]
That would indeed be nice, but given the very little gain and the huge maintenance overhead it means I am not sure it would be stable enough, on the contrary, things could get messy when some classes work some don't.

**Comment by Blackskyliner** [comment]
What if we outsource the problem of maintaining such a list to an external (optional) dependency which need those definitions nevertheless and already have them and keep them in a current version. e.g. https://github.com/JetBrains/phpstorm-stubs

**Comment by sagikazarmark** [comment]
Even then such list means some kind of risk to me which I prefer not taking in production code.

**Comment by mnapoli** [comment]
I have to agree with @sagikazarmark. However feel free to create the list. But for me it has been a problem maybe once, writing and maintaining those definitions is not worth it to me. And I wonder also how it could impact performances in production if we have a big list (in v5 and in v6 which both work differently).

**Comment by bjoern-tantau** [comment]
What about simply stopping the collection of arguments as soon as we can't resolve the default value? The default will be taken by PHP anyway.

I solved this by replacing

`$args[] = $this->getParameterDefaultValue($parameter, $method);`

with

```
try {
    $args[] = $this->getParameterDefaultValue($parameter, $method);
} catch (DefinitionException $e) {
    break;
}
```

in `ParameterResolver::resolveParameters`.

**Comment by mnapoli** [comment]
@bjoern-tantau IIRC the problem is that you can have optional arguments between required arguments, so you would not provide enough parameters for the method call to work.

**Comment by bjoern-tantau** [comment]
Hmm, but I'd say that's a not very common edge case because there is no easy way of calling such a method with the optional arguments left intact. And I'd wager it's non-existant for built-in classes which are the only classes that should actually produce this exception.

Off the bat I actually can't think of a case where this would fail. Anyone wanting to use constructors with optional arguments before required arguments will still be able to use them because `getParameterDefaultValue` works perfectly fine on custom classes. Only the built-in classes would throw the exception and continue to work because the optional arguments would be left undefined.
