### ISSUE TITLE
@Inject sometimes fails on 6.0.0-alpha1?

### ISSUE THREAD

**Issue by holtkamp** [PHP-DI/PHP-DI#472]
Still investigating the exact cause of this, but it seems `@Inject` does not work "out-of-the-box" in some scenarios when testing DI 6.0.0-alpha1... 

- upgrade PHP-DI 5.4 to PHP-DI 6.0.0-alpha1
- change use of \DI\object to \DI\create in the configuration
- running code that uses @Inject annotation on properties results in these properties being `null`

Note that a ContainerBuilder is used + $builder->useAnnotations(true); to create the Container.

I realize a working test would be nice, but already wanted to report this. Rolling back to PHP-DI 5.4 and will try to isolate the problem. I have the idea it has to do with nested dependencies and the use of proxies.

**Comment by mnapoli** [comment]
Unless I've missed something this is expected (and that shows I probably need to improve the migration guide).

`DI\create()` defines how to create an object, end of the story. It completely supersedes autowiring/annotaitons.

Does that text from the migration guide help:

> **What should you do with your `DI\object()` definitions:**
>
> - if you disabled autowiring:
>     - replace it with `DI\create()` and everything should work
> - if you use autowiring:
>     - replace it with `DI\create()` for definitions that replace autowiring completely (i.e. those that redefine all the parameters)
>     - replace it with `DI\autowire()` for definitions that just define *some* parameters and let autowiring guess the rest of the parameters

My guess is that you should use `autowire()` here if you want annotations to be taken into account.

**Comment by holtkamp** [comment]
Thanks for the response. 

>Does that text from the migration guide help

Aah, must have missed [that section](https://github.com/PHP-DI/PHP-DI/blob/bcd354c854ae8bc71eab2a9809236eb60e792ad7/doc/migration/6.0.md#diobject). Will give it a new shot then and report back here. Closing for now.
