### ISSUE TITLE
cache key character request

### ISSUE THREAD

**Issue by juliangut** [PHP-DI/PHP-DI#473]
This is a humble question and request

Testing new psr16 in dev-master and using `doctrine/cache` with `php-cache/doctrine-adapter` I get this error from php-cache:

```
1) /.../ContainerBuilderTest::testCreation
Cache\Adapter\Common\Exception\InvalidArgumentException: Invalid key: "DI\Definition\foo". The key contains one or more characters reserved for future extension: {}()/\@:

/.../vendor/cache/adapter-common/AbstractCachePool.php:290
/.../vendor/cache/adapter-common/AbstractCachePool.php:122
/.../vendor/cache/adapter-common/AbstractCachePool.php:428
/.../vendor/php-di/php-di/src/DI/Definition/Source/CachedDefinitionSource.php:73
/.../vendor/php-di/php-di/src/DI/Definition/Source/CachedDefinitionSource.php:44
/.../vendor/php-di/php-di/src/DI/Container.php:194
/.../tests/PHPDI/ContainerBuilderTest.php:78
```

This is the line that triggers the error:

```php
self::assertTrue($container->has('foo'));
```

I know it's no PHP-DI error but some sort of characters php-cache reserved for "the future"

BUT

@mnapoli could you consider using a character other than back-slash given it could have special meaning? underscore maybe?

**Comment by juliangut** [comment]
I've reviewed [PSR16 document](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-16-simple-cache.md) and it states:

> Key - A string of at least one character that uniquely identifies a cached item. Implementing libraries MUST support keys consisting of the characters A-Z, a-z, 0-9, _, and . in any order in UTF-8 encoding and a length of up to 64 characters. Implementing libraries MAY support additional characters and encodings or longer lengths, but must support at least that minimum. Libraries are responsible for their own escaping of key strings as appropriate, but MUST be able to return the original unmodified key string. The following characters are reserved for future extensions and MUST NOT be supported by implementing libraries: {}()/\\@:

So I consider PHP-DI should comply with this restrictions when supporting PSR16

**Comment by mnapoli** [comment]
Oh good point, I completely missed that!

I think it should be as easy as to change that constant: https://github.com/PHP-DI/PHP-DI/blob/master/src/DI/Definition/Source/CachedDefinitionSource.php#L20 (and adding a test) If you want to send a pull request feel free, else I'll get around it this week.

Thanks!
