### ISSUE TITLE
Support PHP 7.1 only for PHP-DI 6?

### ISSUE THREAD

**Issue by mnapoli** [PHP-DI/PHP-DI#483]
Following up on https://github.com/PHP-DI/PHP-DI/pull/481#issuecomment-295857401 I'm trying to see if it would make sense to support PHP 7.1 and up for PHP-DI 6 (instead of PHP 7.0 and up).

The benefits I see are:

- more options for strict typing with nullable types (`?bool` for example)

To be honest I'm not convinced it's worth the risk of excluding users that didn't keep up with the latest version for now. Are there other advantages (for PHP-DI or its users) that you see?

Edit: another thing is that I'm not against bumping the minimum required version between minor versions. Composer avoids BC breaks for us, so I don't see that as a BC break. What I mean is that nothing would prevent us to bump to PHP 7.1 later this year when PHP 7.0 is not supported anymore.

**Comment by Taluu** [comment]
IMO, when releasing a new major version, it's better to support the current stable version (which is currently 7.1). This can help moving the community forward, helping propagate new versions of PHP and dropping old unsupported ones.

I'd suggest we wait for a new php stats (I think @Seldaek is going to make one soonish, as it's every 6 months or so) to see how much php 7.0 and php 7.1 are used ? But that may be a bit too far away for you ?

**Comment by avant1** [comment]
Besides nullable types and void return type I don't see really important changes for PHP-DI.
But nullable types are really awesome, without them PHP 7.0 types looked incomplete for me.

If we can bump PHP requirement in minor releases - it would be nice to keep PHP-DI compatible with PHP 7.0 for now. Since PHP 7.0 is still supported (and [will be supported until December 2017](http://php.net/supported-versions.php)), it makes sense to support it in libraries too.

But if PHP-DI 6 release will be close to PHP 7.0 end of life then it makes more sense to require PHP 7.1 starting from first stable release of PHP-DI 6.

**Comment by mnapoli** [comment]
PHP-DI 6 will definitely come before December.

I think it's safer for adoption to support PHP 7 now, and switch to 7.1 in December (for example PHP-DI 6.1). Supporting only 7.1 right now creates a risk that fewer users will migrate, yet we want as many people as possible to migrate: currently there is no versioning in the documentation so once v6 is released the website will be about v6. Also maintaining and giving support for 2 versions is exhausting.

That is unless there is some report that shows that a majority of PHP users are on 7.1, but honestly I highly doubt that.

**Comment by Seldaek** [comment]
Just FYI, and in case it helps you make a decision, the new post is out https://seld.be/notes/php-versions-stats-2017-1-edition

**Comment by mnapoli** [comment]
@Seldaek thanks! PHP 7.0 sounds like a good bet, and 7.1 at the end of the year.

**Comment by mnapoli** [comment]
Closing since the question is resolved :)

**Comment by holtkamp** [comment]
https://github.com/PHP-DI/PHP-DI/issues/483#issuecomment-299706970 just encountered this again. Current requirement is (still) 7.0?

https://github.com/PHP-DI/PHP-DI/blob/e06622fdf89adcfb3e970c11a616ebf07ca7f400/composer.json#L28

**Comment by mnapoli** [comment]
I created a follow up issue: #583
