### ISSUE TITLE
php-di annotations

### ISSUE THREAD

**Issue by stelin** [PHP-DI/PHP-DI#486]
How to define scan annotation file path Or namespace，when I use php-di annotations to inject object. Don't want to some php class files to inject, how to do?

**Comment by stelin** [comment]
if php-di can simple used,it likes spring mvc inject.

**Comment by mnapoli** [comment]
Hi, I'm sorry but I don't understand the question at all. For support I invite you to ask your question on http://stackoverflow.com/ and maybe include a bit more details on what you have tried, what you want to do and maybe the errors you faced.
