### ISSUE TITLE
Documentation regarding opcache and saving of comments is not PHP 7 compatible.

### ISSUE THREAD

**Issue by rquadling** [PHP-DI/PHP-DI#510]
http://php-di.org/doc/annotations.html#troubleshooting

The documentation shows ...

> To check the value of this option, you can run the following command:
> `$ php -i | grep "opcache.load_comments"`

But opcache.load_comments was removed in PHP 7 : http://git.php.net/?p=php-src.git;a=commitdiff;h=0a21a0c752a06d25704e04c15464700f75164849

Commentary regarding the necessity of have `opcache.save_comments = 1` set is missing also.

**Comment by mnapoli** [comment]
Thank you, do you mean we can remove this whole section of the documentation because it's not a problem with PHP 7?

If that's the case would you have time to send a pull request?

Thanks!

**Comment by rquadling** [comment]
https://github.com/PHP-DI/PHP-DI/pull/511
