### ISSUE TITLE
Composer replace clause should not be used

### ISSUE THREAD

**Issue by SvenRtbg** [PHP-DI/PHP-DI#512]
The composer file claims that this package replaces any version of "mnapoli/php-di". This clause has been added about 2 years ago into version 4.4.9.

This clause is problematic, because it claims that every version of "php-di" starting from 4.4.9 is able to replace ANY version of that other package. I doubt this to be true in the first place, and I wonder what kind of problem was sensed then that would be solved by this clause. Migration?

However, the problems may be long gone, and I'd like to see this clause gone, because usually it creates unexpected problems when used inappropriately (and giving "*" as a version constraint is such a use IMHO), and does not add much noticeable benefit.

**Comment by mnapoli** [comment]
Hi, I'm not sure I understand the problem, could you illustrate it with a piece of code or example on how to reproduce it?

**Comment by SvenRtbg** [comment]
The statement in this line is simply wrong. 

If once the renaming of this package made `mnapoli/php-di` version 4.4.9 be identical to `php-di/php-di`, then the latter version should have stated that it replaces the former. And after that, no later release of php-di should have stated that it could replace that package.
`php-di/php-di` in version 6 for sure is incompatible with it's own version 4.4.9, and it should not state that it can act as a replacement for `mnapoli/php-di` - for all versions of it.

Assume this: A project still uses `mnapoli/php-di` in version 4.4.9. It works and draws exactly that latest version ever since. And now another component is either added, or updated, and now has a dependency on `php-di/php-di` version 6. This version states that it replaces all versions of `mnapoli/php-di` - and Composer will assume that `mnapoli/php-di` has to go, and remove it. I doubt that this update will work.

Note that this process also takes place for any older version of `mnapoli/php-di` as well. The update is unavoidable because of the wildcard replacement statement.

I'd like to see this replace statement be removed because it surely serves no purpose anymore for any migration efforts that it might have been introduced for.

**Comment by mnapoli** [comment]
After re-reading the documentation (https://getcomposer.org/doc/04-schema.md#replace) it seems you are right and the replace clause is not used correctly, I'll remove it.
