### ISSUE TITLE
Restore container-interop support?

### ISSUE THREAD

**Issue by mnapoli** [PHP-DI/PHP-DI#515]
Followup on #463

Is PSR-11 supported in all major frameworks and integration?

**Comment by mnapoli** [comment]
@Grafikart mentioned Zend Expressive: is there a version compatible with PSR-11?

**Comment by Grafikart** [comment]
@mnapoli Zend expressive supports PSR-11 but the ecosystem around is not updated yet 

ZendTwigRenderer : https://github.com/zendframework/zend-expressive-twigrenderer/blob/master/src/TwigRendererFactory.php#L11
ZendPlateRenderrer : https://github.com/zendframework/zend-expressive-platesrenderer/blob/master/src/PlatesRendererFactory.php#L10

But Zend require the right interface

ZendExpressiveApp : https://github.com/zendframework/zend-expressive/blob/master/src/Application.php#L13

I'll report the libraries I encounter that require interop in this comment

**Comment by ldebrouwer** [comment]
I understand the caution taken in moving to a different interface, but `container-interop` has officially been deprecated in favour of PSR-11 for a couple of months now. Existing projects can always continue using PHP-DI 5.x for the time being, but should take action to update to the latest version. Breaking changes are to be expected with major version changes.

It would be a shame to halt or slow down the progression of PHP-DI moving onto the recommended standard. Plus we could always provide pull requests for the 'outdated' packages to help them move to 6.x.

**Comment by Grafikart** [comment]
Indeed this is a good point of view. I will try to do PR when I see a Container Interop interface used. TwigRenderer has already a PR so let's move forward ;) 
https://github.com/zendframework/zend-expressive-twigrenderer/pull/30

**Comment by fire015** [comment]
Agreed with @ldebrouwer

**Comment by mnapoli** [comment]
Yep I agree too, I'll keep this issue open for a few weeks more to gather more feedback and see if we identify big blocking points. Else we'll probably stay with PSR-11 only (it is true that PHP-DI 5 will still keep working for those projects).

**Comment by xtreamwayz** [comment]
About the expressive related packages: I might have time this weekend to merge all PSR-11 related PR's.

**Comment by mnapoli** [comment]
I checked Slim 3 and it supports PSR-11 *and* container-interop so we are good to go there too (PR for updating the documentation: https://github.com/slimphp/Slim-Website/pull/236).

Closing, thanks everyone!
