### ISSUE TITLE
Dependency Inheritance when constructor is overridden

### ISSUE THREAD

**Issue by vegbrasil** [PHP-DI/PHP-DI#519]
Hi,

I'm having a bit of trouble finding a way to solve dependencies in cases where both classes (parent and child) have their own constructors.

Quick example:

```php
class BaseClass
{
    protected $exampleDependency;

    function __construct(ExampleDependency $exampleDependency)
    {
        $this->exampleDependency = $exampleDependency;
    }
}

class ChildClass extends BaseClass
{
    private $differentDependency;

    function __construct(DifferentDependency $differentDependency)
    {
        $this->differentDependency = $differentDependency; // this is injected correctly
        
        // the code below is never true because $this->exampleDependency is null
        if($this->exampleDependency instanceof ExampleDependency)
            echo 'ExampleDependency was inherited';
    }
}
```

In the example above, `ExampleDependency` was never injected because the constructor was overridden.

Any thoughts?

Thanks!

**Comment by ldebrouwer** [comment]
I reckon this is because you're not calling the parent constructor in the constructor of `ChildClass`.

**Comment by vegbrasil** [comment]
@ldebrouwer Sure, the problem with calling `parent::__construct()` is that I would have to inject the dependencies myself, like `parent::__construct(new ExampleDependency)`... not a great solution, unfortunately.

Thanks for your time!

**Comment by avant1** [comment]
You can request both `ExampleDependency` and `DifferentDependency` in `ChildClass` constructor and then pass `ExampleDependency` to parent constructor.

```php
class ChildClass extends BaseClass
{
    private $differentDependency;

    function __construct(DifferentDependency $differentDependency, ExampleDependency $exampleDependency)
    {
        parent::__construct($exampleDependency);

        $this->differentDependency = $differentDependency;

        if ($this->exampleDependency instanceof ExampleDependency) {
            echo 'ExampleDependency was inherited';
        }
    }
}
```

**Comment by mnapoli** [comment]
> @ldebrouwer Sure, the problem with calling parent::__construct() is that I would have to inject the dependencies myself, like parent::__construct(new ExampleDependency)... not a great solution, unfortunately.

@vegbrasil that's exactly the problem, and this is how PHP works, PHP-DI will not change the rules here :)

When you extend a class in PHP you have to call the parent constructor if you want it to do its job. The example shown by @avant1 is a very good solution.

I'll be closing this issue since it's a question (I want to keep the issue tracker clean). However feel free to continue the discussion.

**Comment by vegbrasil** [comment]
Thanks everyone for the answers!
