### ISSUE TITLE
DI doesn't resolve, if an optional parameter comes before other definitions

### ISSUE THREAD

**Issue by exts** [PHP-DI/PHP-DI#520]
For example there's some legacy code in a project I'm working on:

    Object (
        class = LanguageWebService
        scope = singleton
        lazy = false
        __construct(
            $language_directory = #UNDEFINED#
            $request = get(Symfony\Component\HttpFoundation\Request)
            $permissions = get(Permissions)
        )
    )

Even if the $language_directory is set to null by default (optional) php-di doesn't properly pass a optional null value when trying to resolve the dependency. If $language_directory is the last parameter it works as normal.

**Comment by juliangut** [comment]
As a hint optional parameters should always be placed at the end of parameter list

**Comment by exts** [comment]
@juliangut right, but I feel like it's still easy to detect that using `ReflectionParameter::getDefaultValue`

**Comment by mnapoli** [comment]
Thanks this is indeed a bug (though not best practice for code as @juliangut mentioned), I was suprised because it is supposed to be covered by tests but actually there is some weird behavior of PHP's reflection.

I've pushed https://github.com/PHP-DI/PHP-DI/pull/521 to fix it. It will be fixed in 6.0 though.

**Comment by exts** [comment]
alright cool, yeah when working with a lot of legacy code having to change parameter order all at once would slow me down. So this fix really helps me out until I can solve those issues. Thanks a lot for fixing this :)
