### ISSUE TITLE
Compile does not work

### ISSUE THREAD

**Issue by mx1700** [PHP-DI/PHP-DI#522]
6.0.0-alpha4

```php
class Foo
{
    private $bar;
    public function __construct(Bar $bar)
    {
        $this->bar = $bar;
    }
}

class Bar
{
}

$builder = new \DI\ContainerBuilder();
$builder->addDefinitions([
    Bar::class => autowire(),
    Foo::class => autowire(),

]);
$builder->enableCompilation(__DIR__ . '/CompiledContainer');
$container = $builder->build();
$foo = $container->get('Foo');
```

PHP Fatal error:  Uncaught DI\DependencyException: Circular dependency detected while trying to resolve entry 'Bar' in E:\project\test\di\vendor\php-di\php-di\src\CompiledContainer.php:47
Fatal error: Uncaught DI\DependencyException: Circular dependency detected while trying to resolve entry 'Bar' in E:\project\test\di\vendor\php-di\php-di\src\CompiledContainer.php:47

**Comment by mnapoli** [comment]
Thanks for the report and the script, I'll have a look into it!

**Comment by mnapoli** [comment]
I'm sorry I cannot reproduce with your script. Here is what I did:

```
composer require php-di/php-di:6.0.0-alpha4
```

Then I wrote `test.php` with this content:

```php
<?php


use function DI\autowire;

require 'vendor/autoload.php';

class Foo
{
    private $bar;
    public function __construct(Bar $bar)
    {
        $this->bar = $bar;
    }
}

class Bar
{
}

$builder = new \DI\ContainerBuilder();
$builder->addDefinitions([
    Bar::class => autowire(),
    Foo::class => autowire(),

]);
$builder->enableCompilation(__DIR__ . '/CompiledContainer');
$container = $builder->build();
$foo = $container->get('Foo');
```

and I ran the script:

```
php test.php
```

I get no error.

**Comment by mx1700** [comment]
I tested the code again and I still got an error.
I think it's the running environment that I use Windows system
I tested PHP 7.0 and PHP 7.1 will have an error
However, the Linux system will not be an error

I found the reason and fixed it.
Code in the Compiledefinition method:
$methodname = uniqid (' get ');

The Uniqid function may generate duplicates on Windows

**Comment by mnapoli** [comment]
Thanks for digging and that detailed information! Reopening!
