### ISSUE TITLE
Phpfastcache

### ISSUE THREAD

**Issue by piernik** [PHP-DI/PHP-DI#525]
Is it possible to use phpfastcache for caching?

**Comment by mnapoli** [comment]
Hi,

you can see the cache drivers available here: http://php-di.org/doc/performances.html#cache-types You can click the link to get to the Doctrine documentation if you want the complete and up to date list: http://docs.doctrine-project.org/projects/doctrine-common/en/latest/reference/caching.html (PHP-DI uses Doctrine's cache).

It seems phpfastcache is not supported by Doctrine though.

**Comment by piernik** [comment]
I think phpfastcache is alternative for doctrine. It is not cacheing engine.
