### ISSUE TITLE
Circular dependency with method (setter) injection

### ISSUE THREAD

**Issue by sirtopp** [PHP-DI/PHP-DI#527]
Method injection is a common workaround for circular depenedency but in case oh PHPDI it's not possible to use it to prevent this error from being throw.

Example code that throws `DependencyException` although it is possible to initialize objects using plain PHP:

```
<?php

use DI\ContainerBuilder;

require __DIR__ . "/../vendor/autoload.php";

$builder = new ContainerBuilder();

class A {
    public function __construct(B $b)
    {
    }
}

class B {
    public function __construct(){
        
    }
    
    public function setA(A $a) {
        
    }
}

$builder->addDefinitions([
    A::class => \DI\object(),
    B::class => \DI\object()->method('setA', \DI\get(A::class)),
]);

$c = $builder->build();

// This works:
$b = new B();
$a = new A($b);
$b->setA($a);


// This does not:
$a = $c->get(A::class);
```

I would expect all method injections to be evaluated after container creates all the objects along the way, after object is removed from the `entriesBeingResolved` table, but before it is returned by `$conatiner->get()`.

**Comment by mnapoli** [comment]
Hi, yes this is a limitation of the current architecture :/

I'm not 100% convinced this should be fixed for this case though. Have you tried [lazy loading](http://php-di.org/doc/lazy-injection.html)?

**Comment by sirtopp** [comment]
I tries to avoid lazy loading due to additional packages required and potential performance setback. Besides having an actual circular (constructor) dependency kind of hurts my sense of aesthetics and I prefer to work it out by falling back to setter injection.

**Comment by mnapoli** [comment]
The problem with setter injection being done after the object is initialized is:

```php
class A {
     public function __construct(B $b) {
          $b->doSomething();
    }
}

class B {
     public function __construct(A $a) {
          ...
    }
}
```

The service `B` will be used in `A` before it is completely initialized. In short that means code can run when objects are not 100% initialized.

**Comment by mnapoli** [comment]
Closing as "won't fix" for the moment.
