### ISSUE TITLE
Slim bridge in phpdi 6

### ISSUE THREAD

**Issue by piernik** [PHP-DI/PHP-DI#528]
I'm creating new project and thinking about using 6.0 alpha.

Will slim bridge work with phpdi 6 ?

**Comment by juliangut** [comment]
You can try with a project of mine, branch 2.x supports current PHP-DI v6:

https://github.com/juliangut/slim-php-di/tree/2.x

**Comment by piernik** [comment]
Great - thank I'll give it a try next week

**Comment by mnapoli** [comment]
Good to know, regarding https://github.com/PHP-DI/Slim-Bridge it's not compatible yet (it will be when PHP-DI 6 is released).

**Comment by mnapoli** [comment]
I'll close this issue to keep each repository on topic, feel free to open an issue on both projects.
