### ISSUE TITLE
Know the class something is going to be injected to?

### ISSUE THREAD

**Issue by SvenRtbg** [PHP-DI/PHP-DI#529]
I'm using Log4PHP, and one of the good features is that it offers named loggers, which can be configured individually - or simply allow to add their own name to the log. So I use the class name for the logger name, and instantly I know which class is logging, and I can in theory prevent or enable some classes (or layers in the application) to produce a very detailed debug log.

However, using PHP-DI makes it really hard to facilitate this feature, because I'd either need to know at the time of creating the logger the class name this logger is going to be injected to (constructor injection), or (not preferred, but if nothing else works) implement the LoggerAwareInterface and set the Logger after creating the object (Zend DI allows to define "initializers" which would do this).

Currently, either I am forced to not use a named logger at all, or define a construction method for every class that requires a logger even if it could otherwise be autowired.

Does PHP-DI offer something I haven't seen in the docs that can help?

**Comment by SvenRtbg** [comment]
To illustrate with code, I basically do this:

$class = new XClass(LoggerFactory::get('XClass');

With PHP-DI I'd have to define every single class that need a logger in order to define a different LoggerFactory call parameter, which is "the name of the class the logger is being use in".

**Comment by mnapoli** [comment]
Hi, I'm not sure I understand what you are trying to achieve, but could http://php-di.org/doc/php-definitions.html#retrieving-the-name-of-the-requested-entry help?

**Comment by SvenRtbg** [comment]
Thanks! Your suggestion is close, but off by one.

Reading and experimenting with it tells me that if I define a DI definition as name "Foo" like in the example, the result of getting `RequestedEntry::getName()` will return "Foo". So it always returns the name of the think it is currently working on.

However, I'd need the name this thing is going to be used in, i.e. one level higher up in the dependency hierarchy.

Suppose I have 

    class Foo {
        public function __construct(LoggerInterface $logger) {}
    }

When resolving `LoggerInterface`, I need a method to get the class name `Foo` in order to affect building the logger object.

**Comment by mnapoli** [comment]
OK I see, unfortunately I don't see a solution to achieve that except writing custom code or writing each entry in the config manually :/

**Comment by rafaelbeckel** [comment]
Now I'm reading the overriding part of the docs. It seems I can declare the class that is going to be injected like this: 

~~~php
return [
    'Foo' => DI\create()
        ->constructor(DI\get('another.specific.service')),
    // ...
];
~~~

Now I'm starting to understand it better. I wish that mini-project example included some advanced use cases that not depended on autowiring. I'll include some new examples there and I'll make a PR when I have some time.

**Comment by mnapoli** [comment]
:+1: yes that's the solution.

I'll be closing this question since it's a bit old and it's been answered.
