### ISSUE TITLE
Getting exception

### ISSUE THREAD

**Issue by nimasdj** [PHP-DI/PHP-DI#530]
I am getting this error. Please advise what does it mean and how to fix it?

Fatal error: Uncaught DI\DependencyException: Circular dependency detected while trying to resolve entry 'router' in /vendor/php-di/php-di/src/DI/Container.php:281 Stack trace: #0 /vendor/php-di/php-di/src/DI/Container.php(124): DI\Container->resolveDefinition(Object(DI\Definition\AliasDefinition)) #1 /vendor/php-di/php-di/src/DI/Definition/AliasDefinition.php(63): DI\Container->get('router') #2 /vendor/php-di/php-di/src/DI/Definition/Resolver/SelfResolver.php(34): DI\Definition\AliasDefinition->resolve(Object(DI\Container)) #3 /vendor/php-di/php-di/src/DI/Definition/Resolver/ResolverDispatcher.php(58): DI\Definition\Resolver\SelfResolver->resolve(Object(DI\Definition\AliasDefinition), Array) #4 /vendor/php-di/php-di/src/DI/Container.php(287): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\ in /vendor/php-di/php-di/src/DI/Container.php on line 281

**Comment by mnapoli** [comment]
Hi, you have a circular dependency in your object graph.

For example you want to inject the router in a service A and also inject service A in the router. That is often because of a root problem in the design of the classes.

**Comment by nimasdj** [comment]
Would you please give a simple code example to reproduce this error? It helps me debugging.
@mnapoli

**Comment by richard4s** [comment]
This problem comes from php-di/slim-bridge v1.0.3.

There is a couple steps you need to run to solve it.

1. Remove php-di/slim-bridge from Composer
With this command in your bash: composer remove php-di/slim-bridge

2. Then you need to pull in the slim-bridge v1.0.2
With this command in your bash: composer require php-di/slim-bridge 1.0.2

Finally, Build Something awesome.

**Comment by mnapoli** [comment]
@richard4s suggesting to install an older version is not at all a good solution.

If you have found a bug please open an ticket instead.

**Comment by richard4s** [comment]
Using an older version is not the best but when you're working on a project
with a deadline, you can't let a new version get in the way

**Comment by peterhuynhnguyen** [comment]
thank! fix error

**Comment by sankhacbw** [comment]
> This problem comes from php-di/slim-bridge v1.0.3.
> 
> There is a couple steps you need to run to solve it.
> 
> 1. Remove php-di/slim-bridge from Composer
>    With this command in your bash: composer remove php-di/slim-bridge
> 2. Then you need to pull in the slim-bridge v1.0.2
>    With this command in your bash: composer require php-di/slim-bridge 1.0.2
> 
> Finally, Build Something awesome.

Thanks!
