### ISSUE TITLE
$container->make() returns same instance when an 'alias' is used

### ISSUE THREAD

**Issue by holtkamp** [PHP-DI/PHP-DI#537]
Based on https://github.com/PHP-DI/PHP-DI/issues/409#issuecomment-339890242
>Another solution is to call $container->make() instead of get()

I tried this using `6.0.0-alpha4` but the same instance of the object is returned over and over. The configuration is quite simple, but involves an 'alias':
```php
[
   'nonQualifiedClassName' => DI\get(\Fully\Qualified\ClassName::class),
    \Fully\Qualified\ClassName::class => autowire()->lazy(),
]

$instance1 = $container->make(\Fully\Qualified\ClassName::class);
$instance2 = $container->make(\Fully\Qualified\ClassName::class);

var_dump($instance1 === $instance2); //Returns FALSE, which is as expected

$instance3 = $container->make('nonQualifiedClassName');
$instance4 = $container->make('nonQualifiedClassName');

var_dump($instance3 === $instance4); //Returns TRUE, which is not expected, a new instance should be created
```
Not sure whether this "approach" is supported. We use it to have a shortname point to a longer name:

```php
[
   'button' => DI\get(\Project\View\Helper\Html\Element\Button::class),
    \Project\View\Helper\Html\Element\Button::class => autowire()->lazy(),
]
```

**Comment by mnapoli** [comment]
Oh to be honest no it's not supported :/

What `make()` does is re-resolve the entry you ask for. If you ask to resolve a `get()` entry it will do that, but it will not re-resolve dependencies of that entry (and the entry to which `get()` points is considered a dependency).

Did you get a different result with v5? Because I would think it's the same behavior on both versions.

**Comment by holtkamp** [comment]
>Did you get a different result with v5?

Well, v5 supported Scope::PROTOTYPE 😄. So in that case the alias would point to an entry defined with Scope::PROTOTYPE, which would return the same instance... 

Also see the described use case https://github.com/PHP-DI/PHP-DI/issues/409#issuecomment-339826444

**Comment by mnapoli** [comment]
You are right this is noted.

TODO for v6:

- document that `make()` only makes the instance you ask for and will reuse all dependencies that were already resolved
- make sure that the removal of the PROTOTYPE scope is correctly documented in the migration guide to ease that transition

**Comment by holtkamp** [comment]
Encountered this again, just wondering, would a ```\DI\make()```make sense as a shortcut?

```php
[
   'nonQualifiedClassName' => DI\make(\Fully\Qualified\ClassName::class),
    \Fully\Qualified\ClassName::class => autowire()->lazy(),
]

$instance1 = $container->make(\Fully\Qualified\ClassName::class);
$instance2 = $container->make(\Fully\Qualified\ClassName::class);

var_dump($instance1 === $instance2); //Returns FALSE, which is as expected

$instance3 = $container->make('nonQualifiedClassName');
$instance4 = $container->make('nonQualifiedClassName');
var_dump($instance3 === $instance4); //Should also return FALSE since new instances are created over and over
```

Currently using the more explicit approach:

```php
[
    'nonQualifiedClassName' => function(\DI\FactoryInterface $container) {
        return $container->make(\Fully\Qualified\ClassName::class);
     },
]

**Comment by mnapoli** [comment]
Why would you not use this kind of config directly (bypassing the alias):

```php
   'nonQualifiedClassName' => autowire(ClassName::class)->lazy(),
```

?

**Comment by mnapoli** [comment]
Would it help if `make()` would throw an exception when used with `get()` (to avoid surprises)?

**Comment by holtkamp** [comment]
thanks for the swift reaction!

- https://github.com/PHP-DI/PHP-DI/issues/537#issuecomment-355732323, would that ensure a new instance is created over and over (as is the idea of `make()`)?
- https://github.com/PHP-DI/PHP-DI/issues/537#issuecomment-355734882, well, it might save users hours figuring out why their `make()` (purpose: have a new instance each time / formerly used as prototype scope) is behaving like a `get()` (re-using instances / formerly used as singleton scope)
