### ISSUE TITLE
Pre-generate proxy classes

### ISSUE THREAD

**Issue by mnapoli** [PHP-DI/PHP-DI#542]
Proxy classes are generated on demand (in dev and production).

It could be useful to pre-generate them for performance reasons and to make it usable on read-only filesystems.

**Comment by bbaga** [comment]
If no one else is working on this issue, I'd be happy to pick it up.

**Comment by SvenRtbg** [comment]
Doesn't this look like it should be closed? Haven't looked in detail, but the referenced PR looks like it addresses this issue, and it got merged.

**Comment by mnapoli** [comment]
:+1:
