### ISSUE TITLE
Possible performance issue 

### ISSUE THREAD

**Issue by danslo** [PHP-DI/PHP-DI#546]
Hey there!

I'm currently profiling performance for a part of our application that is calling into a third-party library that use PHP-DI for dependency injection. Therefore I will preface this by saying that I'm not entirely sure if this is a PHP-DI problem yet.

There are some strong indications that it is related to this library. I'm using xdebug profiler to generate a cachegrind dump. Here's the output when processed using qcachegrind:
![profile](https://user-images.githubusercontent.com/743661/32655760-4bec1b48-c60f-11e7-90af-a121bbd11d0a.png)

I've had to redact some of the contents, I hope you can forgive me for that. 

I'm not entirely sure what *exactly* is taking so long, because qcachegrind seems to send me in circles (these things are called recursively) when trying to traverse the call trace.

This library is running 5.x and turning on definition cache (I've confirmed that it is actually caching) made a negligible impact on performance.

Does this look familiar to you at all? Any pointers to profile PHP-DI more in depth? Would switching to 6.x (with compilation) help in this case?

Thanks in advance.

**Comment by danslo** [comment]
Another part of my confusion comes from the fact that this profile is showing that DI\* classes have a bigger Incl. time than {main}. Maybe this is related to autoloading (not counted towards {main}?).

**Comment by danslo** [comment]
I'll be closing the issue since I found the problem.

Xdebug profiler doesn't [deal well with recursion](https://bugs.xdebug.org/view.php?id=77). So I used [xt2callgrind](http://www.exteon.ro/ro/produse/unelte-php/xt2callgrind) to convert a trace file into proper cachegrind file. This let me traverse the call tree properly, and figure out that some expensive work was being done inside a class constructor. PHP-DI instantiated this object and therefore we incorrectly assumed it was the culprit.

Sorry for wasting anyone's time.

**Comment by mnapoli** [comment]
Hi, no worries, happy that you found the source. It is indeed often misleading in these situations because all the objects constructors end up being aggregated behind `Container::get()` so it can seem like it's the container taking so much time.

In any case, to answer you question about v6: it should definitely bring a big improvement compared to v5, but in most applications the container is only a small part of the whole HTTP request so there shouldn't be major differences in response times.
