### ISSUE TITLE
Recursive compilation breaks when abstract classes are involved

### ISSUE THREAD

**Issue by holtkamp** [PHP-DI/PHP-DI#567]
As first mentioned here https://github.com/PHP-DI/PHP-DI/pull/566#issuecomment-357530850, it "can" occur that an abstract class is involved in the collection of classes that is considered for compilation.

Simply skipping these classes might be an approach to be considered?

**Debugging / logging**
As mentioned in https://github.com/PHP-DI/PHP-DI/pull/566#issuecomment-357691451 it is sometimes difficult to determine "why" such an abstract class is considered for compilation.

Improving / extending the error message, or the ability to inject a PSR Logger might simplify this.

**Comment by amakhrov** [comment]
@holtkamp do you know why an abstract class is considered for compilation in your case? Is it specific app setup?

**Comment by amakhrov** [comment]
Copying my use case from another PR to have it all in once place:

My app uses Zend Framework 1.
I list my controllers (they are entry points) in the PHP-DI config.

However, the controllers apparently inherit from the abstract one (provided by ZF1). And the abstract controller's constructor has the following signature:
```
public function __construct(Zend_Controller_Request_Abstract $request, Zend_Controller_Response_Abstract $response, array $invokeArgs = array())
```
So you see - the abstract controller has abstract dependencies.
In ZF1 you're not supposed to redefine the base constructor - so my real controllers inherit the same constructor with abstract dependencies.

PHP-DI Compiler properly compiles the controllers listed in the config, because they are not abstract.

But then, with the new 'recursive compilation' feature, it also tries to compile those abstract dependencies - that's where I get the error from the Compiler.

**Comment by holtkamp** [comment]
@amakhrov 

> do you know why an abstract class is considered for compilation in your case? Is it specific app setup?

No, got no clue why an Entity is considered for compilation. To be honest did not dive very deep into it as well, maybe coming days...

**Comment by mnapoli** [comment]
What I was thinking was ignoring most errors during compilation. Those errors would be triggered at execution time *if* those were actually triggered.

In a future version there could even be a log (PSR-3 logger) of "warnings" found during compilation.

WDYT?

**Comment by holtkamp** [comment]
@mnapoli yes, I guess that would be a good approach to deal with this!

**Comment by amakhrov** [comment]
@mnapoli Frankly, I like the compilation errors very much. ("fail fast!")
And the mentioned errors DO indicate some problems. In my case it's limitations of the current compiler code, which doesn't allow to selectively compile `@Inject` annotations only. In the @holtkamp 's case it might be smth else - but still it's quite an problem that needs investigation.

So maybe it's still a good idea to have fatal errors during compilation **by default**. And add an option to ignore them (let a developer do that at their own risk).

**Comment by mnapoli** [comment]
I did some experiments and I agree that suppressing errors globally is not a good idea, just too much gets suppressed.

We could also silence errors specifically about abstract classes/interfaces but it's too precise and doesn't cover every use case.

One solution would be to silence errors only for *definitions that are not in the config* (i.e. those we found by reference in autowired classes). That should cover classes that are not supposed to be autowired (your abstract controller class for example, or your entity which must be a parameter somewhere but it doesn't seem to matter at runtime).

We loose some errors at compilation, but I don't see a better idea right now…

**Comment by mnapoli** [comment]
I've opened #569 to propose a solution. The implementation is not the prettiest code but it does the job (and I really want to land a stable v6 soon :p).

**Comment by amakhrov** [comment]
@mnapoli Looks like the proposed approach should solve my use case!

**Comment by mnapoli** [comment]
I've released a new beta version, please give it a try :)

**Comment by holtkamp** [comment]
Thanks! Just adopted `6.0.0-beta3`and compilation no functions without fatal errors. Still have to take a look on which definitions compilation failed, but for now this does the job!
