### ISSUE TITLE
Using compilation on 6.0.0-beta3 causes errors in __destruct() functionaltity

### ISSUE THREAD

**Issue by holtkamp** [PHP-DI/PHP-DI#570]
Still investigating, but thought it was good to report. When using `6.0.0-beta3` with compilation enabled, New Relic (which monitors the application) indicates:

- no significant increase in performance

![screen shot 2018-01-21 at 20 11 58](https://user-images.githubusercontent.com/776405/35200170-f8ae33a0-fee7-11e7-822c-0d69ea29dc2a.png)

- increased number of errors
![screen shot 2018-01-21 at 20 13 09](https://user-images.githubusercontent.com/776405/35200174-09094104-fee8-11e7-8f2f-645d10a2774c.png)

The error message: ```curl_multi_close(): supplied resource is not a valid cURL Multi Handle resource``` triggered by [CurlMultiHandler::__destruct()](https://github.com/guzzle/guzzle/blob/aa5b807560eb4c5d0ef6ff9e7cbeb02a1c587223/src/Handler/CurlMultiHandler.php#L56) which is used by [CloudWatchClient::putMetricDataAsync](https://github.com/aws/aws-sdk-php/blob/421217ceff7de350cf9fc61c9bfc5ff363ef894f/src/CloudWatch/CloudWatchClient.php#L36) (which involves a promise) to send log information to [AWS CloudWatch](https://aws.amazon.com/cloudwatch/)

When *not* enabling compilation, these errors do not occur anymore. 

I will check what happens when using the synchronous [CloudWatchClient::putMetricData](https://github.com/aws/aws-sdk-php/blob/421217ceff7de350cf9fc61c9bfc5ff363ef894f/src/CloudWatch/CloudWatchClient.php#L35), to see whether the use of a promise is related to this error.

**Comment by mnapoli** [comment]
Thanks for the report but without more details I cannot help.

Regarding the performances what is the average page load time? Because for most applications the improvements will most certainly not be visible since we are talking about something that takes usually less time that the time needed for 1 SQL query. Have you tried comparing 2 profiles too? (using e.g. Blackfire)

**Comment by mnapoli** [comment]
This is a performance comparison I made between 6.0.0-beta3:

- with cache, without compilation
- with cache, with compilation

I'm saving 10ms on externals.io homepage.

![capture d ecran 2018-01-22 a 08 35 18](https://user-images.githubusercontent.com/720328/35209652-54f7242a-ff4f-11e7-8a89-63438d19ba64.png)

https://blackfire.io/profiles/compare/14e34b57-8963-42f8-b072-1637af58b6e9/graph

To debug your findings we will need more data I think.

**Comment by holtkamp** [comment]
> Thanks for the report but without more details I cannot help.

I understand, just wanted to report my findings that enabling compilation might have side effects.  

When using the synchronous [CloudWatchClient::putMetricData](https://github.com/aws/aws-sdk-php/blob/421217ceff7de350cf9fc61c9bfc5ff363ef894f/src/CloudWatch/CloudWatchClient.php#L35), (which does not involve a promise) the error does not occur.

The code used to dispatch metric data asynchronously with a promise:

```php
private function dispatchAsynchronously(Collection $metricData): void
    {
        $promise = $this->cloudWatchClient->putMetricDataAsync([
            'MetricData' => $metricData->toArray(),
            'Namespace' => 'MyProject',
        ]);

        while (!\GuzzleHttp\Promise\is_settled($promise)) {
            $this->curlMultiHandler->tick();
        }
    }
```

Both `$this->cloudWatchClient` and `$this->curlMultiHandler` are dependencies injected as constructor parameters and part of the PHP-DI configuration (and therefore compiled). 

Maybe this case is very specific / exotic, just wanted to report it. Feel free to close this issue, at least not it is documented 😄

**Comment by holtkamp** [comment]
Correction, the issue also occurs with the synchronous approach. Will disable compilation for now and try to isolate the issue.

**Comment by mnapoli** [comment]
OK let me know! I have done several performance tests and they all show an improvement.

Here is a comparison between PHP-DI 5 (cache) and PHP-DI 6 (cache + compilation) on the homepage of externals.io:

[![](https://i.imgur.com/AdIVPuL.png)](https://blackfire.io/profiles/compare/647ec5b4-08f4-4a82-821f-f1ef7be9cad8/graph)

Needless to say I'm happy with the results ^^

**Comment by holtkamp** [comment]
Recently enabled compilation again and now no errors occur, so it seems either:

- not reproducible in 100% of the cases
- not related to PHP-DI compilation

closing issue.

**Comment by holtkamp** [comment]
Just to report my findings, no need to re-open this issue until I find some time to dive into this and can isolate the problem. Disabling compilation makes the error disappear. 

Upgraded to PHP-DI `6.0.2` en re-enabled compilation. Immediately the error popped up in New Relic again. 

![screen shot 2018-04-24 at 16 58 19](https://user-images.githubusercontent.com/776405/39195752-bd25cdce-47e0-11e8-97bc-04c19144dc91.png)


```
Error message
E_WARNING: curl_multi_close(): supplied resource is not a valid cURL Multi Handle resource

Stack trace
…close called at /app/vendor/guzzlehttp/guzzle/src/Handler/
CurlMultiHandler.php (56)
in GuzzleHttp\Handler\CurlMultiHandler::__destruct called at ? (?)
```

https://github.com/guzzle/guzzle/blob/0773d442aa96baf19d7195f14ba6e9c2da11f8ed/src/Handler/CurlMultiHandler.php#L56
