### ISSUE TITLE
Removed method

### ISSUE THREAD

**Issue by juliangut** [PHP-DI/PHP-DI#575]
I've just noticed by [this commit](https://github.com/PHP-DI/PHP-DI/commit/6748f3f75280bb65a6efc52eff80531450de05df#diff-5772c249f61507a501a28c2087d7d2a8) that the method getKnownEntryNames introduced in PR #505 has been removed as being considered "unused"

Without that method [debugEntry](https://github.com/PHP-DI/PHP-DI/blob/master/src/Container.php#L301) method is sort of orphan as you may only debug entries you know exist in the container

Can it be brought back?

**Comment by mnapoli** [comment]
Sounds reasonable indeed, will revert that!

**Comment by mnapoli** [comment]
Thanks!
