### ISSUE TITLE
Argument of function as a parameter gets resolved

### ISSUE THREAD

**Issue by sagikazarmark** [PHP-DI/PHP-DI#576]
After upgrading to PHP-DI beta3 the following code stopped working:

```php
    //....
    \Middlewares\FastRoute::class => \DI\autowire(),
    \FastRoute\Dispatcher::class => \DI\factory('FastRoute\\cachedDispatcher')
        ->parameter(
            'routeDefinitionCallback',
            function (\FastRoute\RouteCollector $r) {
                $routeList = require APP_ROOT.'/etc/routes.php';

                foreach ($routeList as $routeDef) {
                    $r->addRoute($routeDef[0], $routeDef[1], $routeDef[2]);
                }
            }
        )
        ->parameter(
            'options',
            \DI\factory(function (bool $debug) {
                return [
                    'cacheDisabled' => $debug,
                    'cacheFile' => APP_ROOT.'/var/cache/router.php',
                ];
            })->parameter('debug', \DI\get('debug'))
        ),
```

Error:

```
Fatal error: Uncaught DI\Definition\Exception\InvalidDefinition: Entry "Middlewares\FastRoute" cannot be resolved: Entry "FastRoute\RouteCollector" cannot be resolved: Entry "FastRoute\RouteParser" cannot be resolved: the class is not instantiable Full definition: Object ( class = #NOT INSTANTIABLE# FastRoute\RouteParser lazy = false ) Full definition: Object ( class = FastRoute\RouteCollector lazy = false __construct( $routeParser = get(FastRoute\RouteParser) $dataGenerator = get(FastRoute\DataGenerator) ) ) Full definition: Object ( class = Middlewares\FastRoute lazy = false __construct( $router = get(FastRoute\Dispatcher) ) ) in /var/www/vendor/php-di/php-di/src/Definition/Exception/InvalidDefinition.php:18 Stack trace: #0 /var/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(157): DI\Definition\Exception\InvalidDefinition::create(Object(DI\Definition\AutowireDefinition), 'Entry "Middlewa...') #1 /var/www/vendor/php-di/php-di/src/Definiti in /var/www/vendor/php-di/php-di/src/Definition/Resolver/ArrayResolver.php on line 68
```

Looks like PHP-DI tries to resolve the function argument (`FastRoute\RouteCollector`). It's constructor accepts an interface, that's what the error is about.

Is it intended? If so, is there a way to pass a function as a value parameter?

**Comment by sagikazarmark** [comment]
Looks like wrapping in `\DI\value` solves the problem. Is it a new thing?

**Comment by mnapoli** [comment]
Hi! Yes it was intended (#487), I realize this is not documented in the upgrade guide. I will leave this issue open to fix the documentation.

The goal was to make everything coherent: it was weird that closures were interpreted as factories when at the root of the config, but not when embedded in other definitions.

Given how you are surprised by this maybe this was not a very good move, what is your opinion? Others opinions welcome too, we are still in beta so this can be reverted. I'm just worried that closures will be handled inconsistently again.

**Comment by sagikazarmark** [comment]
If I understand right, the closure is actually invoked and the returned result is passed to the factory.

Well, I have arguments for and against this change.

From one point it's good to be consistent. This way every time I pass a closure somewhere I can expect it to be invoked by the container.

On the other hand, this is probably not what I would expect when I think about the closure as a parameter. As you can see from the code above, my first instinct was to pass the closure as a plain argument and pass a factory definition manually when I wanted the container to resolve it.

This way it's more explicit what I expect from the container to do. Not sure if documentation would help much on the DX part of this question.

To be honest, for the same reason I wouldn't pass a plain closure to root config either. I would wrap it in a factory definition. (I guess it happens under the hood anyway). So if consistency is a priority, I wouldn't mind if passing a plain closure to the root config would not be automatically turned into a factory definition anymore.

**Comment by mnapoli** [comment]
Being able to define config using closures (like Pimple for example) is an important feature IMO. After looking at a few use cases I think it still makes sense, and consistency is important.

I have pushed an update to the documentation and the upgrade guide to make that clearer.

**Comment by sagikazarmark** [comment]
Cool, either way, documentation should resolve any confusion. Thanks.
