### ISSUE TITLE
Release date for v6?

### ISSUE THREAD

**Issue by odahcam** [PHP-DI/PHP-DI#577]
Now that the [milestone](https://github.com/PHP-DI/PHP-DI/milestone/19) is complete and the [project](https://github.com/PHP-DI/PHP-DI/projects/1) closed, what can we expect of PHP-DI 6? Does it has a release date?

**Comment by mnapoli** [comment]
Yes ! Next monday ! (19th)

The last work left is to write the release article and unfortunately that takes a lot of time, I'll finish it this week-end and publish everything on Monday (far less people are online during the weekend). I wanted to shoot it this week but things got in the way :/

**Comment by odahcam** [comment]
OMG! That's awesome! 

I'm very very very excited to put PHP-DI in my Slim project and start using it's awesome features. Do you think I should wait or start directly on v6 or should I go with v5?

Thanks for the fast response. 😁

**Comment by mnapoli** [comment]
You should use the latest beta, it will be the same as the release unless a bug appears in the meantime. The beta is stable.

However please note that the current documentation online is for v5. But next week it will be v6. In the meantime all the v6 documentation can be found here: https://github.com/PHP-DI/PHP-DI/tree/master/doc

**Comment by odahcam** [comment]
All right, thank you!

**Comment by mnapoli** [comment]
Article is ready, going online tomorrow ;)

**Comment by mnapoli** [comment]
It's live http://php-di.org/news/22-php-di-6-0-released.html :)
