### ISSUE TITLE
Compilation and configuration/dynamic-values

### ISSUE THREAD

**Issue by SpazzMarticus** [PHP-DI/PHP-DI#579]
I played around with 6.0.0-beta3 and - as expected - configuration values are also compiled into `CompiledContainer.php`.

```php

//...reading config from file...
$config = ['key'=>'value'];

$containerBuilder=new \DI\ContainerBuilder();
$containerBuilder->addDefinitions([
    'key1'=>$config['key'],
    'A'=>DI\create(Dummy::class)->constructor($config['key']), //values is compiled (static)
    'B'=>DI\create(Dummy::class)->constructor(DI\get('key1')), //values is compiled (static)
    'C'=>DI\create(Dummy::class)->constructor(DI\get('key2')), //value is retrived dynamically
]);

$containerBuilder->enableCompilation(__DIR__.'/cache');
$container=$containerBuilder->build();

$container->set('key2', $config['key']);
```

 Is the correct way to add configuration-values to the container after running `build` via `set` on the container directly?

**Comment by mnapoli** [comment]
It is not a good idea to use `set()` especially with the compiled container (because the value may already be injected in some services for example). Is there something preventing you to put the value in the config directly?

**Comment by SpazzMarticus** [comment]
If the configuration-values are compiled in the container, then changing them in the configuration-file won't affect the application unless the container is rebuilt. 

In my example the first run will result in `A`, `B` and `C` having set the same value, but if I change the value an run the script again, `A` and `B` will have the same value as before, `C` has the updated value. (This is expected behaviour.)

What is the best way to adapt to changing configuration-values?

**Comment by mnapoli** [comment]
I see, you cannot compile the container if you want to have a dynamic configuration. There are 2 solutions:

1. do not compile the container
2. compile the container again every time the configuration changes (or create several different compiled containers)

For example with option 2, let's imagine you have an application that serves multiple hosts: `http://client1.com` and `http://client2.com`. You can have 3 config files:

- `config/generic-config.php`
- `config/client1.php`
- `config/client2.php`

Then in your bootstrap file:

```php
$client = /* client1 or client2 based on the HTTP host */;

$containerBuilder=new \DI\ContainerBuilder();
$containerBuilder->addDefinitions('config/generic-config.php');
$containerBuilder->addDefinitions('config/' . $client . '.php');

$containerBuilder->enableCompilation(__DIR__.'/cache/' . $client);
$container=$containerBuilder->build();
```

That way you will have 2 compiled containers in the `/cache/` directory.

**Comment by SpazzMarticus** [comment]
Is there any chance that a option - like the `lazy()`-option for object-definitions - will be added to prevent certain definitions from being compiled?

**Comment by mnapoli** [comment]
Not at the moment, I'm not sure it would make sense though.
