### ISSUE TITLE
nikic/php-parser 4 for PHP-DI/PHP-DI 6?

### ISSUE THREAD

**Issue by automatix** [PHP-DI/PHP-DI#585]
Hello!

I've just installed Symfony 4 and would like to use it with the currently latest version of PHP-DI, the `v6`.

```
$ composer require php-di/php-di ^6.0
...
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for php-di/php-di ^6.0 -> satisfiable by php-di/php-di[6.0.0].
    - Conclusion: remove nikic/php-parser v4.0.0
    - Conclusion: don't install nikic/php-parser v4.0.0
```

So the problem is, that one of the Symfony packages (namely `symfony/maker-bundle`) needs the `nikic/php-parser ^4.0`. And this dosn't meet the PHP-DI's requirements defined in its `composer.json`:

```
"require": {
    ...
    "nikic/php-parser": "^2.0|^3.0"
},
```

The `nikic/PHP-Parser`'s `v4` was [released `18 days ago`](https://github.com/nikic/PHP-Parser/releases). And the PHP-DI's `v6` was released about a week earlier. So is the restriction to the `^2.0|^3.0` just outdated and should be extended with `^4.0`? If so, could the core developers please update it.

Thanks

**Comment by mnapoli** [comment]
Thanks, feel free to send a pull request if you have time.

**Comment by mnapoli** [comment]
:+1: thanks for starting the work. The best course of action then would be to send a pull request to SuperClosure first. I'll try to do that myself in the next weeks but I don't have a time estimate, contributions are welcome ;)

**Comment by jdreesen** [comment]
It seems that support has already been added in https://github.com/jeremeamia/super_closure/pull/104 but it has not been released yet.

**Comment by SvenRtbg** [comment]
SuperClosure 2.4.0 has been released almost right after your comment.
https://github.com/jeremeamia/super_closure/releases/tag/2.4.0

**Comment by railto** [comment]
Just tested, seems that the new holdup is phpstan, lol.  Version 0.9.2 requires php-parser at ^3.1 and not seeing any PR's there for upping it, might look at that one later

**Comment by jdreesen** [comment]
It seems to be scheduled for the v0.10 milestone. See: https://github.com/phpstan/phpstan/issues/859

**Comment by nikic** [comment]
As your version constraint would become `^2.0|^3.0|^4.0", that still satisfies the `^3.1` constraint by phpstan, so I'm not sure why that's a blocker. It will not be a conflict for dependent libraries, as they don't install dev dependencies.

**Comment by mnapoli** [comment]
Yep no blocker here, thanks for the feedback it's fixed!
