### ISSUE TITLE
Zend\Expressive\Route will not accept anything other than objects implementing the MiddlewareInterface starting in version 3.0.0

### ISSUE THREAD

**Issue by spencer237** [PHP-DI/PHP-DI#588]
Hello everyone please i have this problem :
we detected usage of "callable" for path "/nkenmoe" using methods GET. Please update your code to create middleware instances implementing MiddlewareInterface; use decorators for callable middleware if needed. in C:\xampp\htdocs\mon_mvc\vendor\zendframework\zend-expressive-router\src\Route.php on line 296

**Comment by mnapoli** [comment]
Hi, I'm not sure to understand how this is related to PHP-DI?

**Comment by spencer237** [comment]
@mnapoli sorry I made a mistake

**Comment by mnapoli** [comment]
No problem thanks for the answer!
