### ISSUE TITLE
Question regarding \DI\env()

### ISSUE THREAD

**Issue by RinkAttendant6** [PHP-DI/PHP-DI#592]
The documentation states

> You can get an environment variable's value using the `DI\env()` helper

Are there any advantages to using `\DI\env()` instead of [`getenv()`](https://secure.php.net/manual/en/function.getenv.php)? I see that `\DI\env()` provides the ability to set a default value if the environment variable doesn't exist, but is that it?

```php
return [
    'db1.url' => DI\env('DATABASE_URL'),
    'db2.url' => getenv('DATABASE_URL'),
    'db3.url' => DI\env('DATABASE_URL', 'sqlite://user:pass@localhost/db'),
    'db4.url' => getenv('DATABASE_URL') ?: 'sqlite://user:pass@localhost/db',
];
```

Or did I miss something else and the functions actually do two different things? Both of them seem to be working for me so far.

**Comment by mnapoli** [comment]
That's it ;)

The advantage is that it allows for a default value, and that default value can also be a definition (e.g. `get('something.else')`, etc).

**Comment by RinkAttendant6** [comment]
Great to know, thanks for the prompt response! :+1:
