### ISSUE TITLE
Passing callable in autowire/create function

### ISSUE THREAD

**Issue by RinkAttendant6** [PHP-DI/PHP-DI#598]
I'm not sure if I doing something wrong but I can't seem to get the autowiring working with a callable constructor parameter:

```php
// Not working
return [
    ProblemDetailsResponseFactory::class => autowire()
        ->constructor(
            function (): ResponseInterface {
                return new Response();
            },
            getenv('FOO_ENV') === 'production' ? ProblemDetailsResponseFactory::EXCLUDE_THROWABLE_DETAILS : INCLUDE_THROWABLE_DETAILS
        )
];
```

It works fine if I write a factory function:

```php
// Working
return [
    ProblemDetailsResponseFactory::class => factory(function (): ProblemDetailsResponseFactory {
        return new ProblemDetailsResponseFactory(
            function (): ResponseInterface {
                return new Response();
            },
            getenv('FOO_ENV') === 'production' ? ProblemDetailsResponseFactory::EXCLUDE_THROWABLE_DETAILS : ProblemDetailsResponseFactory::INCLUDE_THROWABLE_DETAILS
        );
    }),
];
```

I also tried using `constructorParameter` with no success. It seems to be evaluating the callable instead of passing it as a parameter:

> Fatal error: Uncaught TypeError: Argument 1 passed to Zend\ProblemDetails\ProblemDetailsResponseFactory::__construct() must be callable, object given, called in /var/www/html/ventus/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php on line 146 and defined in /var/www/html/project1/vendor/zendframework/zend-problem-details/src/ProblemDetailsResponseFactory.php on line 203

**Comment by mnapoli** [comment]
Hi, yes this is because the callable is considered as a nested `factory()` definition:

> Keep in mind that closures are equivalent to "factory" definitions. As such, closures are always interpreted as factories, even when nested inside other definitions.

(see http://php-di.org/doc/php-definitions.html#nesting-definitions)

If you use anonymous functions for something else than factories you need to wrap them in the `DI\value()` helper:

```php
return [
    'router' => create(Router::class)
        ->method('setErrorHandler', value(function () {
            ...
        })),
];
```

Hope that helps!
