### ISSUE TITLE
class connectivity does not work

### ISSUE THREAD

**Issue by Div-Man** [PHP-DI/PHP-DI#600]
if you use `use DI\ContainerBuilder;` the class does not find, and for some reason, NetBeans swears on ContainerBuilder on line 106

syntax error

```
 public static function buildDevContainer() : Container
    {
        return new Container;
    }
```
In version 5.4, this was not, everything worked fine.

Now tried to install version 5.4, everything works, and the new version 6.0.2 does not work

```
<?php

require_once 'vendor/autoload.php';


use DI\ContainerBuilder;

$builder = new DI\ContainerBuilder();

```

Fatal error: Uncaught Error: Class 'Container' not found in C:\OSPanel\domains\phpdi\index.php:6 Stack trace: #0 {main} thrown in C:\OSPanel\domains\phpdi\index.php on line 6

**Comment by mnapoli** [comment]
I'm sorry this kind of support is out of scope for this issue tracker, this is very probably not related to PHP-DI but to another issue in your code or your local setup. I'm afraid I don't have the time to help more, maybe [stackoverflow.com](https://stackoverflow.com/) could?

If however you do find an issue with PHP-DI please report back with additional details (like a reproducible test case).
