### ISSUE TITLE
Missing comma in Compiler

### ISSUE THREAD

**Issue by prisis** [PHP-DI/PHP-DI#601]
Im not sure but, between the second and the last parameter a comma is missing. 

https://github.com/PHP-DI/PHP-DI/blob/71a7f2ed1e728138060ea159cbb1a92dc8620bd2/src/Compiler/Compiler.php#L236-L241

**Comment by prisis** [comment]
oh missed https://github.com/PHP-DI/PHP-DI/blob/71a7f2ed1e728138060ea159cbb1a92dc8620bd2/src/Compiler/Compiler.php#L233

**Comment by mnapoli** [comment]
👍 yep
