### ISSUE TITLE
Clear resolved entry

### ISSUE THREAD

**Issue by hultberg** [PHP-DI/PHP-DI#602]
Hello,

I was unable to find a issue for this, so here goes. In my unit tests I have a service I need to override with a mock because it makes external requests. However, as the `ContainerInterface` in php-di has a resolved entries cache, the next unit test will also get the mocked service class. I would like to see a method that would unset an entry from `resolvedEntries` like: `\DI\Container::unset()`. Another solution is to implement that method in a new class, like `TestableContainer`. Any thoughts?

**Comment by SvenRtbg** [comment]
I'd not fetch the instance to test from PHP-DI (or any other DI container) for a unit test. I put them together the traditional way. The same goes for integration tests with more than just one class.

I'd wonder how you'd get to the mock object anyway and configure it.

**Comment by mnapoli** [comment]
If you are writing an integration test that makes sense to use the container. @hultberg you have 2 options:

- after running the test call `Container::set()` to restore the original service
- boot a new PHP-DI container for every time

I highly recommend the second solution, tests should be isolated from each other, if you start going down the road of sharing stuff you will spend a lot of time debugging and fixing small unpredicted problems.

**Comment by hultberg** [comment]
@mnapoli Thanks. I did end up using a new container instance in the test. I'm closing this issue as I feed we don't need any change to the container. If one really need to unset an resolved entry, they could override the Container class and implement it as `$resolvedEntries` is protected.
