### ISSUE TITLE
DI\env should probably treat empty string variable values the same as undefined variables

### ISSUE THREAD

**Issue by ezzatron** [PHP-DI/PHP-DI#606]
I work with @jmalloc who originally wrote the `DI\env` function. We've realised recently that if you somehow end up with an environment variable set to an empty string, `DI\env` will not use the supplied default value.

As far as I know, it's pretty well established that empty strings are treated the same as undefined values in systems like Bash, where the following will behave the same in both cases:

```bash
if [ -z "$VAR" ]; then
  echo "VAR is empty"
fi
```

I recently had to replace all usage of DI\env in a project because of this, so I thought I would at least open the discussion about whether it could be changed, and whether it would constitute a BC break for PHP-DI.

**Comment by SvenRtbg** [comment]
The bash code above is not the same when running with `set -u` or `set -o nounset`, which enables detecting and failing on usage of unset variables in bash scripts.

From PHP perspective: If I set an environment variable to an empty string, I would expect to get that empty string when asking for it, not run into the "undefined env variable triggers the default value" case. If I want to run into that case, I'd unset the env variable.

And even for bash there are ways to work with differentiating between these cases, or work around them in specific cases, like answered in https://stackoverflow.com/questions/7832080/test-if-a-variable-is-set-in-bash-when-using-set-o-nounset

IMHO this ticket should be closed without changing any code.
