### ISSUE TITLE
Strategy pattern

### ISSUE THREAD

**Issue by paddelboot** [PHP-DI/PHP-DI#609]
What if I want to use different implementations for an interface during the runtime of an application? As far as I can see, I can only bind 1 implementation to 1 interface in the container's config. 

https://www.phptherightway.com/pages/Design-Patterns.html#strategy

**Comment by paddelboot** [comment]
Wouldn't this mean I would have to pass the container object around, which is definitely not recommended?

**Comment by mnapoli** [comment]
Do you have an example of your problem?

**Comment by paddelboot** [comment]
I have a lot of problems with circular dependencies, as described here:

https://www.codingforums.com/php/391581-cicular-dependency.html#post1550227

My approach to solve this was to use the Strategy Pattern; instead of having an error class that has dependencies which themselves need an error object, I was going to create a notifications class that can be used with different output implementations (log, SMS, email, etc).

**Comment by mnapoli** [comment]
> Therefore I would need to pass different implementations to the notification interface, depending on where it's being used.

That means you need to configure which entry to inject for each service. There is no concept of "depending on where it's being used" in PHP-DI, you have to be explicit in the configuration.

**Comment by paddelboot** [comment]
> That means you need to configure which entry to inject for each service. [...] you have to be explicit in the configuration.

My initial question was how to achieve this; maybe you could give me an example or point me to some documentation? I don't see it here: http://php-di.org/doc/container-configuration.html. Thanks.

**Comment by paddelboot** [comment]
Hold on, does it mean I shouldn't type hint against an interface in such a case? So if I would want to use a logger in my error class:

`class error{
  function __construct( SomeLogger $logger ){

}

}`

Is that what you meant by "configuration" of my service? Usually I would type hint against an interface like NotificationsInterface, therefore my confusion.

**Comment by mnapoli** [comment]
@paddelboot check here: http://php-di.org/doc/php-definitions.html

For example:

```php
return [
    SomeClass::class => DI\create()
        ->constructor(DI\get(FirstLogger::class)),

    AnotherClass::class => DI\create()
        ->constructor(DI\get(SecondLogger::class)),
];
```

As you can see, both classes will receive a different logger.

I'll be closing this issue because it is a support request, feel free to continue the discussion.
