### ISSUE TITLE
Parse error in PHP-DI with DELETE route

### ISSUE THREAD

**Issue by scottfriebel** [PHP-DI/PHP-DI#620]
_From @scottfriebel on August 29, 2018 19:42_

I'm getting the following errors when making a request that is routed but only with the DELETE request method. Using the exact same url for a GET/POST request, it runs without a problem. I'm using php v. 7.1.19, php-router v. 4.2.0.4, and php-di v. 6.0.3.
The url that I'm getting the error with is `/api/v1/users/me/projects/8399421535/pages/0/photos/1372` and the route is `api/v1/users/{userid}/projects/{projectid}/photos/{photoid}`

'<b>Warning</b>:  Unsupported declare 'strict_types' in <b>C:\inetpub\wwwroot\DevCreatePhotoCalendars\Studio\classes\vendor\php-di\php-di\src\functions.php</b> on line <b>3</b><br />
<b>Parse error</b>:  syntax error, unexpected ':', expecting '{' in <b>C:\inetpub\wwwroot\DevCreatePhotoCalendars\Studio\classes\vendor\php-di\php-di\src\functions.php</b> on line <b>22</b>'

_Copied from original issue: skipperbent/simple-php-router#425_

**Comment by scottfriebel** [comment]
_From @skipperbent on August 30, 2018 23:58_

You should move this issue to the php-di GitHub page here:
https://github.com/PHP-DI/PHP-DI

It looks like the `declare` function is not supported in PHP in your environment which is called within the `php-di` library. If you are receiving the error when running unit-tests etc. make sure that the php version in CLI is 7.0 or higher.

Also the parse error could be due to your PHP installation not parsing strict types (methods with strictly declared type as parameters) properly resulting in an invalid php-file.

Hope it helps.

/ Simon

**Comment by mnapoli** [comment]
> It looks like the `declare` function is not supported in PHP in your environment which is called within the `php-di` library. If you are receiving the error when running unit-tests etc. make sure that the php version in CLI is 7.0 or higher.

That sounds about right.
