### ISSUE TITLE
factory: optional parameter becomes factorydefinition

### ISSUE THREAD

**Issue by webmaster777** [PHP-DI/PHP-DI#628]
While writing some code for a symfony Lock object, I was trying to configure php-di to use the factory provided for this kind of thing.

simplified:
~~~php
use Symfony\Component\Lock\StoreInterface;
use Symfony\Component\Lock\Store\FlockStore;
use Symfony\Component\Lock\LockInterface;
use Symfony\Component\Lock\Factory;

use function DI\get;
use function DI\factory;
use DI\ContainerBuilder;

$config = [
    StoreInterface::class => get(FlockStore::class),
    LockInterface::class => factory([Factory::class,"createLock"])
        ->parameter("resource", "some-lock"),
];

$containerBuilder = new ContainerBuilder();
$containerBuilder->addDefinitions($config);
$containerBuilder->useAnnotations(true);
$container = $containerBuilder->build();

$myLock = $container->get(LockInterface::class);
~~~

The definition of `Factory::createLock()` looks like this:

~~~php
    /**
     * Creates a lock for the given resource.
     *
     * @param string $resource    The resource to lock
     * @param float  $ttl         Maximum expected lock duration in seconds
     * @param bool   $autoRelease Whether to automatically release the lock or not when the lock instance is destroyed
     *
     * @return Lock
     */
    public function createLock($resource, $ttl = 300.0, $autoRelease = true)
    {
        $lock = new Lock(new Key($resource), $this->store, $ttl, $autoRelease);
        $lock->setLogger($this->logger);

        return $lock;
    }
~~~

As you can see,  only `$resource` is a required var.

However, running this will create the following Error (php7.2 / php-di 6.0.4)
~~~
PHP Fatal error:  Uncaught TypeError: Argument 3 passed to Symfony\Component\Lock\Lock::__construct() must be of the type float or null, object given, called in .../vendor/symfony/lock/Factory.php on line 47 and defined in .../vendor/symfony/lock/Lock.php:44
Stack trace:
#0 .../vendor/symfony/lock/Factory.php(47): Symfony\Component\Lock\Lock->__construct(Object(Symfony\Component\Lock\Key), Object(Symfony\Component\Lock\Store\FlockStore),Object(DI\Definition\FactoryDefinition), true)
#1 [internal function]: Symfony\Component\Lock\Factory->createLock('some-lock', Object(DI\Definition\FactoryDefinition), true)
#2 .../vendor/php-di/invoker/src/Invoker.php(82): call_user_func_array(Array, Array)
#3 .../vendor/php-di/php-di/src/Definition/Resolver/FactoryResolver.php(80): Invoker\Invoker->call(Array, Array)
#4 .../vendor/ph in .../vendor/symfony/lock/Lock.php on line 44
~~~

My guess is that the default second parameter (requestedentry?) overwrites any default parameters of the method.

The third parameter (`$autoRelease`) was set to `true`, though I'm not sure this is resolved by DI or by the php internals.

The workaround was of course to provide my own closure as factory:

~~~php
[
    LockInterface::class => function (ContainerInterface $c) {
        $factory = $c->get(Factory::class);
        return $factory->createLock("some-lock");
    },
]
~~~

**Comment by webmaster777** [comment]
I hoped #597 / #526 would have fixed this, but that seems to be about a different kind of factory.

**Comment by jworreth** [comment]
Hello,

After a bit of reflection on the code, it seems to me that this issue is not really about PHP-DI/PHP-DI's repository but rather about the combination of the Invoker and the DefaultValueResolver objects from PHP-DI/Invoker's repository.

I'm not sure about that though but I found out that one part of the real problem is that DefaultValueResolver object doesn't check the parameter's type but only if it's optional or not. If so, it will force the resulting value to its default one.

I suggest to open an issue or to move this one to PHP-DI/Invoker (if I'm right of course...).

I wrote a little UnitTest and a possible way to fix this in my local copy of the PHP-DI/Invoker repository and my proposal is as follow :
````php
class DefaultValueResolver implements ParameterResolver
{
    public function getParameters(
        ReflectionFunctionAbstract $reflection,
        array $providedParameters,
        array $resolvedParameters
    ) {
        $parameters = $reflection->getParameters();

        // Skip parameters already resolved
        if (! empty($resolvedParameters)) {
            $parameters = array_diff_key($parameters, $resolvedParameters);
        }

        foreach ($parameters as $index => $parameter) {
            /** @var \ReflectionParameter $parameter */
            if ($parameter->isOptional() && ($class = $parameter->getClass()) === null) {
                try {
                    $resolvedParameters[$index] = $parameter->getDefaultValue();
                } catch (ReflectionException $e) {
                    // Can't get default values from PHP internal classes and functions
                }
            } elseif ($parameter->isOptional()) {
                try {
                    $resolvedParameters[$index] = [
                        'name' => $class->getName(),
                        'default' => $parameter->getDefaultValue()
                    ];
                } catch (ReflectionException $e) {
                    // Can't get default values from PHP internal classes and functions
                }
            }
        }

        return $resolvedParameters;
    }
}
````
The current version is:
````php
class DefaultValueResolver implements ParameterResolver
{
    public function getParameters(
        ReflectionFunctionAbstract $reflection,
        array $providedParameters,
        array $resolvedParameters
    ) {
        $parameters = $reflection->getParameters();

        // Skip parameters already resolved
        if (! empty($resolvedParameters)) {
            $parameters = array_diff_key($parameters, $resolvedParameters);
        }

        foreach ($parameters as $index => $parameter) {
            /** @var \ReflectionParameter $parameter */
            if ($parameter->isOptional()) {
                try {
                    $resolvedParameters[$index] = $parameter->getDefaultValue();
                } catch (ReflectionException $e) {
                    // Can't get default values from PHP internal classes and functions
                }
            }
        }

        return $resolvedParameters;
    }
}
````

Unfortunately, I'm now stuck on the parsing of the `DefaultValueResolver::getParameters` function's result in the `Invoker` class. I would suggest to alter the `Invoker::call` method to be able to handle the result of the `DefaultValueResolver::getParameters` to identify complex objects type and then retrieving their instance/s from the container if they exists. If not, just force the default value as before.

What do you think ?

**Comment by mnapoli** [comment]
@jworreth that's interesting, thanks for digging in!

I have a few questions about your code, but it will be easier to discuss if you open a pull request on the `Invoker` repository. Could you do that?

**Comment by jworreth** [comment]
@mnapoli Thanks for your reply. I just created a pull request with the potential fix [here](https://github.com/PHP-DI/Invoker/pull/25).

Let me know if I did something wrong.

**Comment by jworreth** [comment]
Hi again guys,

Hope you're doing well.

@mnapoli would it be possible to merge the pull request #714 on that repo into master branch if you think it's enough to solve the issue ? If not, could you please give me some advise on how to solve the it properly ?

In addition to that, I've made a pull request on the PHP-DI/Invoker repository [here](https://github.com/PHP-DI/Invoker/pull/25) which I've linked to the according issue 24 of the repo (if I remember correctly). This pull request should solve @webmaster777's issue.

Best Regards

**Comment by mnapoli** [comment]
OK I took the time to dig into all of this. Thank you for all the details and the pull requests, that really help.

After trying to solve this in different ways, I have decided that for now I will not merge a fix. The current behavior is surprising, but it kind of makes sense from a logical perspective. Solving this would require to add more magical behavior.

Given that currently it seems to affect only a very small pool of users, I have decided not to complexify the codebase and the behavior of PHP-DI.

I have pushed my fix in https://github.com/PHP-DI/PHP-DI/compare/issue-628. If we realize with time that more people are affected, we could reopen this issue and decide to revisit this decision.

Hopefully you understand!

**Comment by jworreth** [comment]
Thanks for coming back with your explanations.

I will take a look at the branch you mentioned and I will try it on my environment. Indeed one of the pull request I made was solving my issue. If that doesn't work, I'll use a factory for the time being, or maybe if I come up with an other solution, then I will create a new pull request.

Thanks again for your help
