### ISSUE TITLE
\DI\env not Type aware

### ISSUE THREAD

**Issue by sridesmet** [PHP-DI/PHP-DI#633]
It is not possible to Typecast a \DI\env('variable') variable.

For example:
```
IMyClass::class => \DI\create(MyClass::class)->constructor(
    (int) \DI\env('variable')
  ),
```

**Comment by mnapoli** [comment]
Not it isn't, `DI\env()` creates an object that represents the definition. It is executed when the configuration is loaded, not when the object is instantiated. This is a configuration format.
