### ISSUE TITLE
decorators and type hinting

### ISSUE THREAD

**Issue by akrz** [PHP-DI/PHP-DI#634]
Hi, I want to decorate a Repository with a CachedRepository. I have a Service that's autowired with ExampleRepository, but when php-di wants to construct that Service it'll throw: 

> "message": "Argument 2 passed to API\\Services\\ExampleService::__construct() must be an instance of API\\Repositories\\ExampleRepository, instance of API\\Repositories\\CachedExampleRepository given, called in /var/www/app/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php on line 142",

Both repositories implements an interface, so I tried to change the Service typehint to the interface but throws:

> "message": "Entry \"API\\Services\\ExampleService\" cannot be resolved: Entry \"API\\Repositories\\ExampleRepositoryInterface\" cannot be resolved: the class is not instantiable

It makes sense as an interface cannot be instantiated.

Decorator:
```php
\API\Repositories\ExampleRepository::class => \DI\decorate(function ($previous, ContainerInterface $c) {
   return new \API\Repositories\CachedExampleRepository($c->get(Redis::class), $previous);
}),
```

__construct of the Service:
```php
    public function __construct(UserRepository $userRepository, ExampleRepository $exampleRepository)
    {
        $this->userRepository = $userRepository;
        $this->exampleRepository = $exampleRepository;
    }
```

Am I doing something wrong? I have used php-di decorators before but I was getting the instance directly from the container, like $container->get(FooRepository::class);

**Comment by mnapoli** [comment]
I'm guessing you haven't aliased the interface to the `ExampleRepository` implementation?

**Comment by akrz** [comment]
That was it. For future reference:

```php
\API\Repositories\ExampleRepositoryInterface::class => DI\get(\API\Repositories\ExampleRepository::class)
```
