### ISSUE TITLE
Di as not global

### ISSUE THREAD

**Issue by 6562680** [PHP-DI/PHP-DI#635]
Not sure about your library but defining injected variables using config file has more testability than $container->get();

Example of worst testability (you need to run whole framework to test function):
MyService.php
Class MyService() 
{
  function myfunc() { $container->get('myservice2'); }
}

Example of good testability (you need to include config only):
config.php
['myservice2'] = [ 'class' => MyService2 ];
['myservice'] = [ 'class' => MyService, 'payload' => [ 'myservice2' ]; // if singleton
['myservice'] = [ 'class' => MyService, 'payload' => [ MyService2::class ]; // if instance

MyService.php
function _construct(Interface $myservice2) { ...actions }
function myfunc() { ...actions }

**Comment by mnapoli** [comment]
Not sure what your point here is but OK.
