### ISSUE TITLE
make() is not using typehints but named parameters instead

### ISSUE THREAD

**Issue by dynasource** [PHP-DI/PHP-DI#651]
Let me first thank you for all the efforts put into this useful library.

About the issue. I dont know if this is intended behavior, but the fact that argument names in constructors are used to match with ```make()```` parameters, is quite error prone. 

Once you change a parameter $name, exceptions are thrown.

Am I missing some setting to force Typehint parameter resolving?

**Comment by mnapoli** [comment]
I'm sorry I don't understand.

**Comment by dynasource** [comment]
Let's say one wants to create class X:
```
class X{
public function __construct(Z $name_1)
}
```
By calling make($id, $params):
```
make(X::class, [
'name_1' => new Z ()
])
```

In this basic scenario, one has to make sure 'name_1' and $name_1 are equally named, which is much more error prone, than when is matched by Class typehint (Class_Z)

**Comment by dynasource** [comment]
Of course names are always unique, being it a safe solution compared to a case in which constructors have multiple arguments of the same type. In most cases (apart from variadic) this is rare and a fallback to the current $name matching solution could be executed. 

To me, matching by Class Typehint is the most obvious default as it is less error prone and also done during autowiring.

**Comment by SvenRtbg** [comment]
You may call it ignorant, but I never really found a need to use the unstandardized `make()`, but always went for the PSR-compliant `get()`. And autowiring of course, keeping manual configuration to a minimum.

Yes, you'd have to pay attention to the parameters names, and all the same problems occur that we also have when using strings to define method names for mocks in tests: Once you refactor, either the tests are going red for no real reason, or worse: They stay green.

Maybe `make()` has no good interface because syntactical elements like variable/parameter names are represented as strings and are likely to not be changed during refactoring. But the same is true for adding class names as strings (if you don't use `::class`). 

My major point however would be that you cannot have the same type twice. For classes, this might be only a minor issue, but what about scalar types, arrays?

**Comment by mnapoli** [comment]
@dynasource if you want to inject a dependency (especially via its typehint) then you will want to either:

- let PHP-DI create `Z` (autowiring)
- configure `Z` in the container configuration and not specify this parameter in `make()`

Parameters in `make()` are only useful for parameters that are not dependencies.

But yeah maybe in your case `get()` is better as well.

**Comment by dynasource** [comment]
I tend to disagree here

The fact that ```make()``` is available in the public api enables end-users to benefit from its specific functionality, other than ```get()```. IMHO, a discussion about whether to use ```get()``` is not relevant to me.

When actually using ```make()``` it doesnt take long to get the first exception, magically appearing out of nowhere. Further digging into the cause, it was just because of changing the name of a ``$variable`` to ``$variable_other_name`` in a constructor. This fragile behavior, came unexpected, especially not in this DI container library which is so excellent in autowiring dependencies

If you ask me, if you choose to have ```make``` available, why not make it more stable and consistent with  the rest of the library.

**Comment by mnapoli** [comment]
> The fact that make() is available in the public api enables end-users to benefit from its specific functionality, other than get().

Yes but you don't seem to understand **when** to use this method and what parameters to provide when calling it.

If want want to inject a service via its type-hint then you shouldn't pass the parameter in `make()`.

**Comment by dynasource** [comment]
You can't blame me for the usecase you are suggesting in your docs ;)

```Container::make() is useful for creating objects that should not be stored inside the container (i.e. that are not services, or that are not stateless)```

**Comment by mnapoli** [comment]
Well there you go then, I don't see what the fuss is all about.

**Comment by holtkamp** [comment]
Interesting... 

Regardless of the question whether `$container->make()` should actually be used, it seems this request for a different strategy of parameter resolving is related to https://github.com/PHP-DI/PHP-DI/issues/594 and https://github.com/PHP-DI/PHP-DI/issues/584

When given an array `$providedParameters`, the following chain of strategies can be considered to get an array `$resolvedParameters` to be used in `__construct()` :

1. use the [AssociativeArrayResolver](https://github.com/PHP-DI/Invoker/blob/master/src/ParameterResolver/AssociativeArrayResolver.php), which is the current behavior: named parameters are required. In case that fails, essentially: `count($resolvedParameters) !== $providedParameters`
1. use the [TypeHintResolver](https://github.com/PHP-DI/Invoker/blob/master/src/ParameterResolver/TypeHintResolver.php) to use the type of `$value` (the actual parameter) to determine the position. If that that fails :
1. use the [NumericArrayResolver](https://github.com/PHP-DI/Invoker/blob/master/src/ParameterResolver/NumericArrayResolver.php), as suggested in as suggested in https://github.com/PHP-DI/PHP-DI/issues/594)

This looks a lot like this [`ResolverChain`](https://github.com/PHP-DI/PHP-DI/blob/3b04ed9b518bc30b8afb3f89d7a620d6b8df16d5/src/Container.php#L399-L405) involved with `$container->call($name, $parameters)`:

I was planning on working on support for the [NumericArrayResolver](https://github.com/PHP-DI/Invoker/blob/master/src/ParameterResolver/NumericArrayResolver.php) in `$container->make()`. When doing this might as well have a look at support for the [TypeHintResolver](https://github.com/PHP-DI/Invoker/blob/master/src/ParameterResolver/TypeHintResolver.php) ...
