### ISSUE TITLE
How can I detect pre-flight wether a class is instantiable b PHP-DI

### ISSUE THREAD

**Issue by michielroding** [PHP-DI/PHP-DI#656]
We use Composer to get us a classmap of all interfaces and their implementations. Whenever there's a 1:1 relation, we generate a mapping of those interfaces to their single implementations.

This saves us a ton of time maintaining a mapping.

However, as we deal with everything composer finds for use, we end up with implementation of an interface that PHP-DI cannot instantiate, for example when there's an argument that has no proper definition, e.g.:

```PHP
class foo {
  public function __construct($fail) { 
    ;
  }
}
```

How can I use PHP-DI to detect wether it's able to instantiate an object? That way I can prevent adding them to the definition list, as I can't compile the current result.

**Comment by mnapoli** [comment]
You can try `$container->has(...)` but it won't anticipate all errors (as that's extremely hard to do).

What you can do is call `get()` and catch any exception? But I'm not sure there is a perfect solution for what you are trying to do :/
