### ISSUE TITLE
Is DI\env unfinished?

### ISSUE THREAD

**Issue by exts** [PHP-DI/PHP-DI#659]
The docs say `DI\env`:

`You can get an environment variable's value using the DI\env() helper:`

Yet all it creates is a `EnvironmentVariableDefinition` with no reference to the actual value of an environment variable value. 

Not sure what the point of env() is in its current state, same code from 5.0 too?

**Issue:**

Calling `DI\env('VARIABLE_NAME')` doesn't actually grab any data from the server environment. 

**Expected:**

I expected the return value would at least give me a value from the environment, instead I get an object that doesn't relate to the environment variables at all.

**Comment by mnapoli** [comment]
Just like all helper functions you need to use this function in the PHP-DI configuration array only. See http://php-di.org/doc/php-definitions.html#environment-variables for examples.

The behavior you describe is normal, this is how PHP-DI works. The idea is that the environment variable is evaluated lazily only when it is actually used.

**Comment by exts** [comment]
So this can't be used on its own, guess that makes sense. thanks for the response
