### ISSUE TITLE
Calling factory with parameters

### ISSUE THREAD

**Issue by nlemoine** [PHP-DI/PHP-DI#666]
Hi, 

I'm struggling with a quite simple use case. I'm defining a factory and try to call it with some parameters. 

```php
<?php

require 'vendor/autoload.php';

use DI\ContainerBuilder;

$builder = new ContainerBuilder;
$container = $builder->build();

$container->set('my_factory', function($param1, $param2 = null) {

	// Do some logic stuff here
	// if($param1 === 'foo') {
	//     return new Foo($param1);
	// }
	// return new Bar($param1, $param2);
});

$r = $container->make('my_factory', [
	'param1' => 'foo',
]);

```

But in my factory, `param1` is a the container instance. I tried every possible way to achieve this: 

```php

use DI\ContainerBuilder;
use function DI\factory;

$builder = new ContainerBuilder;
$container = $builder->build();

$container->set('my_factory', factory(function($param1, $param2 = null) {
	// Do some logic stuff here
	// if($param1 === 'foo') {
	//     return new Foo($param1);
	// }
	// return new Bar($param1, $param2);
})
	->parameter('param1', null)
	->parameter('param2', null)
);

$r = $container->get('my_factory', [
    'param1' => 'foo'
]);
// param1 is always null

$r = $container->make('my_factory', [
    'param1' => 'foo'
]);
// param1 is always null
```

Am I missing something?

Thanks for your help.

**Comment by mnapoli** [comment]
Hi, I'm not sure I understand, you are expecting things which are not what PHP-DI does. Have a look at the documentation for `factory` to see what you can do with it: http://php-di.org/doc/php-definitions.html#factories

A factory returns the instance. Its parameters are not affected with what is passed to `make()`, these parameters are mostly used when autowiring an object (with `autowire()`).

**Comment by nlemoine** [comment]
Sorry, I'm quite new to DI/Service containers. I'm trying to adapt the `SilexAssetProvider` to `PHP-DI` (switching from Pimple to PHP-DI) and I can't figure out how I can reproduce this [factory pattern](https://github.com/silexphp/Silex/blob/master/src/Silex/Provider/AssetServiceProvider.php#L48).
created [here](https://github.com/silexphp/Silex/blob/master/src/Silex/Provider/AssetServiceProvider.php#L81). 

I read everything I could before posting this. And I think I just found an answer [here](https://github.com/PHP-DI/Silex-Bridge/blob/6b86749801e15795daca826e95a4c7a0fc415e5b/tests/PimpleTest.php#L62-L68). Seems like the `Pimple` `protect` way of doing things isn't available in `PHP-DI`. 

Thank you for the quick reply!
