### ISSUE TITLE
Is it possible to configure injection for traits?

### ISSUE THREAD

**Issue by glen-84** [PHP-DI/PHP-DI#672]
Since #279 doesn't seem to be happening, I'm trying to think of alternatives to the classic "Controller" issue, where multiple controllers share similar functionality.

The documentation recommends annotation-based property injection, but having to manually add something like this:

```php
class UserController
{
    /**
     * @Inject
     * @var FormFactoryInterface
     */
    private $formFactory;

    // repeat for templating, session, request, etc.
}
```

... in every controller would be quite repetitive.

I think I read that it's possible when using *annotations* in traits, but can they be configured with PHP definitions as well?

**Comment by SvenRtbg** [comment]
Have you tried it? What was the result?

From what I get, traits get copy&pasted into the host class during compile time, and annotations may be detected thereafter, because the doc blocks do not get removed from the opcode (at least they have their own "docblock comment" opcode).

**Comment by glen-84** [comment]
@SvenRtbg,

I'm not using PHP-DI yet, so it's not easy for me to test it. I understood from other issues that annotations in traits should work, but I don't see any documentation related to configuring traits (via PHP *or* annotations).

**Comment by mnapoli** [comment]
IMO this should work indeed. Let us know if it doesn't by opening a ticket.

Internally PHP-DI uses Doctrine's annotation reader.

**Comment by glen-84** [comment]
@mnapoli My question is not about annotation-based configuration, it's about PHP based configuration.

**Comment by mnapoli** [comment]
Oh I'm sorry, I don't understand then. Do you have an example to illustrate?

**Comment by glen-84** [comment]
It's possible with _annotations_ on a trait, but there's no way to use PHP definitions to say "anything with trait X should have its Y setter called".

Quick example:

```php
trait X
{
    protected $y;

    protected function setY($y)
    {
        $this->y = $y;
    }
}

class Controller
{
    use X;
}
```

There's no way to configure traits like you can with classes. I'm sure it's possible to implement this with reflection, but I can't really answer the question "does it make sense?".

**Comment by mnapoli** [comment]
> anything with trait X should have its Y setter called

Indeed that is not something that PHP-DI can. It isn't something that I plan on implementing either as I don't consider this a good practice.
