### ISSUE TITLE
Install fails under PHP 7.3 due to missing mcrypt extension.

### ISSUE THREAD

**Issue by puckelhontas** [PHP-DI/PHP-DI#673]
Composer installation of PHP-DI 6 fails under PHP 7.3.
Error: "Your requirements could not be resolved to an installable set of packages. The requested PHP extension ext-mcrypt * is missing from your system. Install or enable PHP's mcrypt extension."

PHP 7.3 doesn't have mcrypt anymore. Is there a workaround, i.e. switching to Libsodium, OpenSSL?
Composer was updated to the latest version.

**Comment by SvenRtbg** [comment]
PHP-DI does not require the mcrypt extension. Some of your other dependencies do. If you look into the `composer.lock` file and search for `ext-mcrypt`, you'll quickly discover which software library that is.

The extension got removed with PHP 7.2, after being deprecated with PHP 7.1. There is a polyfill library that recreates all the mcrypt functions by using OpenSSL instead: https://github.com/phpseclib/mcrypt_compat - just in case you need a quick compatibility upgrade.

**Comment by puckelhontas** [comment]
Thanks, you're right - there was an old mcrypt entry left after upgrading PHP. Not PHP-DI related.
Anyway, thanks for the polyfill hint, that might be useful one day!
