### ISSUE TITLE
How to set a closure as value to compiled container?

### ISSUE THREAD

**Issue by downace** [PHP-DI/PHP-DI#674]
PHP-DI 6.0.8

I can `set` any value to the `CompiledContainer`, but `Closure`s are always interpreted as factories and `set` throws `LogicException`. I can't even use the `\DI\value()`

```php
<?php

require_once './vendor/autoload.php';

$builder = new \DI\ContainerBuilder();
$builder->enableCompilation('.');

$container = $builder->build();

$container->set('db:host', 'localhost');                           // ok
$container->set('db:factory', function(){ /* ... */ });            // LogicException
$container->set('db:factory', \DI\value(function(){ /* ... */ })); // LogicException

// LogicException: You cannot set a definition at runtime on a compiled container.
// You can either put your definitions in a file, disable compilation or ->set()
// a raw value directly (PHP object, string, int, ...) instead of a PHP-DI definition
```

**Comment by mnapoli** [comment]
Hi, you can't set any definition at runtime. This is a design constraint of the compiled container.

**Comment by downace** [comment]
Hi, thanks for the answer!

> I can't even use the `\DI\value()`

My bad here, `\DI\value()` is only for setting definitions

But I don't need to set a definition, I need to `->set() a raw value directly` as described in error message. This value should go directly to `\DI\Container::$resolvedEntries`. And this value is a `Closure` in my case (`'db:factory'` is bad example for this). I thought that "raw value" means ANY value, but it's not

I guess it's for convenience: factories are very common and defining them with `DI\factory` may be annoying. But I think that `set`ting definitions ONLY via `\DI\Definition\Definition` would be more consistent

**Comment by mnapoli** [comment]
Ahh I see, so indeed we could have a specific case for `DI\value()` because we know it can be interpreted as a raw value.

I am :+1: to merge a PR implementing this.
