### ISSUE TITLE
Inject static class 

### ISSUE THREAD

**Issue by realrecordzLab** [PHP-DI/PHP-DI#676]
We need to inject RedBeanPHP as a dependency for some classes of a project. Some help to achieve this will be appreciated, this ORM use static methods and we can't figure how to pass the class to PHP-DI container for the injection.

**Comment by SvenRtbg** [comment]
You cannot inject static classes because you dont create instances.

My suggestion would be to create a wrapper layer that translates instance calls to the static calls - you can then inject that layer, and as an additional benefit you separate your own code from that framework.

**Comment by realrecordzLab** [comment]
> You cannot inject static classes because you dont create instances. My suggestion would be to create a wrapper layer that translates instance calls to the static calls - you can then inject that layer, and as an additional benefit you separate your own code from that framework.

@SvenRtbg something like a setter / getter class right?

**Comment by SvenRtbg** [comment]
Well, I was thinking along this:

    class Wrap {
        public function getStuff() {
            return Static::getSomething();
        }
    }

You'd instantiate Wrap in the DI container and inject it where you would originally call the static method.

It's not supposed to do anything besides forwarding parameters and returning the result.

Note however that static methods are usually bad inside a well designed OOP application, so if you really have to use that framework, isolate it as best as you can from your own code.

**Comment by mnapoli** [comment]
:+1: agree with your suggestions @SvenRtbg, there is no support for static classes planned in PHP-DI.

**Comment by realrecordzLab** [comment]
>Note however that static methods are usually bad inside a well designed OOP application, so if you really have to use that framework, isolate it as best as you can from your own code. 

I don't know if you know RedBeadPHP project, all the objects that are part of the ORM library are regular non static classes. They decided to wrap all inside a tiny facade that use statics methods to access to various functions. The problem is that they forgot to create a simply way to avoid using this facade, the result is that sometimes it's "difficult" to implement this ORM, like in my case.
