### ISSUE TITLE
Integrate PHP-DI with FastRoute

### ISSUE THREAD

**Issue by realrecordzLab** [PHP-DI/PHP-DI#677]
There was an [opened issue](https://github.com/PHP-DI/PHP-DI/issues/676) where was suggested to us to wrap a static class in a standard class to inject it when needed. Well, since that issue topic is closed, we needed to open this one, this to ask why we aren't able to make things working. 
We have created a simple class to wrap the static class needed. Now the class is recognized by `PHP-DI`.  
This is what is printed out during debug: 
`UserController Object ( [db] => DataManager Object ( ) ) ` . 
We suppose that the data manager object that is the wrapper class, is injected inside the UserController class, is this right? Unfortunately the UserController will not work because needs it's dependency, in this case the DataManager.
We are using PHP-DI with FastRoute. If anyone have implemented in past PHP-DI with that library, please can suggest us a way to make the things work? 

Here is the error message we got:

>Fatal error: Uncaught ArgumentCountError: Too few arguments to function UserController::__construct(), 0 passed in /../index.php on line 53 and exactly 1 expected

This is the Implementation code (nothing complicated here)

```
<?php

require_once __DIR__.'/vendor/autoload.php';

use \RedBeanPHP\R;
//use DI\Container;
//use DI\DependencyException;
//use DI\NotFoundException;

$dispatcher = FastRoute\simpleDispatcher(function(FastRoute\RouteCollector $router) {
    $router->addRoute('GET', '/', 'Controller/index');
    /* User uri mapping */
    $router->addGroup('/user' , function(FastRoute\RouteCollector $router){
      $router->addRoute('GET', '/', 'UserController/index');
      $router->addRoute('POST', '/reg', 'UserController/register');
    });
});

// Fetch method and URI from somewhere
$httpMethod = $_SERVER['REQUEST_METHOD'];
$uri = $_SERVER['REQUEST_URI'];

// Strip query string (?foo=bar) and decode URI
if(false !== $pos = strpos($uri, '?')){
    $uri = substr($uri, 0, $pos);
}
$uri = rawurldecode($uri);

$routeInfo = $dispatcher->dispatch($httpMethod, $uri);
switch ($routeInfo[0]) {
    case FastRoute\Dispatcher::NOT_FOUND:
        // ... 404 Not Found
        break;
    case FastRoute\Dispatcher::METHOD_NOT_ALLOWED:
        $allowedMethods = $routeInfo[1];
        // ... 405 Method Not Allowed
        break;
    case FastRoute\Dispatcher::FOUND:
        $handler = $routeInfo[1];
        $vars = $routeInfo[2];
        list($class, $method) = explode("/", $handler, 2);
        $container = new DI\Container();
        $class = $container->get($class);
        
        call_user_func_array([new $class, $method], $vars);
        break;
}

class DataManager {

  public function __construct()
  {
    return R::setup();
  }

}


class Controller {

  public function index()
  {
    ...
  }

}

class UserController extends Controller {

  public function __construct(DataManager $db)
  {
    $this->db = $db;
  }

  public function index()
  {
    ...
  }

  public function register()
  {
    ...
  }

}

?>


```

**Comment by realrecordzLab** [comment]
Solved, a collab have attentioned that we didn't need to instantiate the object
`call_user_func_array([new $class, $method], $vars);` 
So we have removed the new keyword: 
`call_user_func_array([$class, $method], $vars);`
But this can create problem with classes that didn't have dependencies. Any suggestion will be appreciated

**Comment by holtkamp** [comment]
You should use the container to get an instance of the controller:

```php
$container = new DI\Container(); //Was this example code? You should probably use ContainerBuilder to acquire a proper PHP-DI container!
$controllerObject = $container->get($class);
$callable = [$controllerObject, $method];
call_user_func_array(callable, $vars);
```
