### ISSUE TITLE
Slim4 support missing?

### ISSUE THREAD

**Issue by tolgaulas** [PHP-DI/PHP-DI#680]
When I wanted to install in Slim4 presence, I've received the below errors:
Problem 1
    - Installation request for php-di/slim-bridge ^2.0 -> satisfiable by php-di/slim-bridge[2.0.0].
    - php-di/slim-bridge 2.0.0 requires slim/slim ^3.9.0 -> satisfiable by slim/slim[3.10.0, 3.11.0, 3.12.0, 3.12.1, 3.9.0, 3.9.1, 3.9.2, 3.x-dev] but these conflict with your requirements or minimum-stability.

Wasn't Slim4 supported?

Thanks.

**Comment by mnapoli** [comment]
@tolgaulas not yet with the bridge, see https://github.com/PHP-DI/Slim-Bridge/pull/47

However you can put PHP-DI in Slim manually thanks to PSR-11 (you won't get any feature of the bridge though). But maybe the PR I linked to can help you.

**Comment by mnapoli** [comment]
Support has been added and the documentation has been updated.
