### ISSUE TITLE
Add ServiceProviderInterface similar to pimple/pimple

### ISSUE THREAD

**Issue by dominikzogg** [PHP-DI/PHP-DI#683]
Are you interested in a PR with an interface similar to: https://github.com/silexphp/Pimple/blob/master/src/Pimple/ServiceProviderInterface.php ?

**Comment by mnapoli** [comment]
Hi, well in PHP-DI service providers are the arrays of definitions.

So I'm not sure that the interface would be useful.

**Comment by dominikzogg** [comment]
@mnapoli would be cool to have an oop way to define them, makes them better testable

**Comment by SvenRtbg** [comment]
Who's "them"? And what are you trying to do with that interface and an implementation? Can you illustrate that a bit, please?

**Comment by dominikzogg** [comment]
@SvenRtbg sure, for example to implements something like: https://github.com/chubbyphp/chubbyphp-doctrine-db-service-provider/blob/master/src/ServiceProvider/DoctrineOrmServiceProvider.php or https://github.com/chubbyphp/chubbyphp-config/blob/master/src/Pimple/ConfigServiceProvider.php

**Comment by SvenRtbg** [comment]
I was hoping for illustrating your test argument. :)

In general the problem with DI containers is that even though there is an interface for `get()`, you cannot really have all your libraries add themselves to your own container. Your proposal looks like it wants to deal with this, but still is only a single product's solution.

I didn't feel like I needed more testability in my applications for DI, but I cannot know everything - so what's your pain point there?

**Comment by dominikzogg** [comment]
@SvenRtbg i think php-di could be a good alternative for pimple, cause it can be used similar if whished. I would like to add php-di support to my libs (mentioned two of them) but dlike to been able to write tests against those services providers, which covers them, as an example: https://github.com/chubbyphp/chubbyphp-doctrine-db-service-provider/blob/master/tests/ServiceProvider/DoctrineOrmServiceProviderTest.php

**Comment by mnapoli** [comment]
Let's try to have a list of arguments to justify for a new concept.

Here is what I got from the discussion yet, feel free to suggest new arguments:

- it's easier to test

On that point I don't see it honestly. If you test that the config is actually valid, you have to create a new container, load the config, and test that services are created correctly. But you can do this already today: just create PHP-DI and pass the config.

Am I missing something that makes testing this simpler with a service provider?

Again, a service provider in PHP-DI is the array. What can you do with a `ServiceProviderInterface` that is needed and can't be done with an array?

**Comment by yethee** [comment]
You can use `zendframework/zend-config-aggregator` + `elie29/zend-phpdi-config`. Config provider as alternative service provider.

**Comment by SvenRtbg** [comment]
Well, I don't like your test because it is huge and does so many different things, but I try not to get distracted by that too much.

What your test essentially does is configuring the DI container in the first 5 code lines (or plenty of more starting in the second test function), then runs plenty of assertions against it. Those assertions are very detailed checks that the container has keys (with PHP-DI you could be that verbose, but autowiring exists), and then does some integration tests with the container build results.

I have tests in my applications that scan the production directory for classes and then query every found class (minus a blacklist) from the DI container to ensure no necessary configuration for PHP-DI is missing. And testing these classes has nothing to do with a container, so no test benefit there.

**Comment by rrigby** [comment]
Main benefit of Service Providers imo is to support modular architecture.

I think support for this would be a worthwhile addition.

**Comment by dominikzogg** [comment]
@rrigby https://packagist.org/packages/laminas/laminas-container-config-test this is a package which supports the testing of packages supporting DI independent service creation. Used for example in mezzio. There might be even a pscksge for PHP-DI.
