### ISSUE TITLE
Detect functionally unchanged compiled container

### ISSUE THREAD

**Issue by jlherren** [PHP-DI/PHP-DI#684]
So I've read about #604 that was implemented in #605 and merged for [6.0.7](https://github.com/PHP-DI/PHP-DI/tree/6.0.7), but then #648 happened so it was reverted in #654.

My use case is that I compile the container on a build server and then commit it to a deployment repository ready to be pulled by servers. The compiled container changes every time due to its use of random IDs, even if nothing else has changed, which produces a lot of noise. However I don't really need the container to be any kind of idempotent, I'm fine with the random IDs. I just want to avoid committing it if it hasn't functionally changed.

Is there a way to detect whether or not the newly compiled container is identical to the old one? It would be good enough if some kind of content hash would be written out as a comment, for my build infrastructure to detect that there's no need to commit that file.

**Comment by mnapoli** [comment]
I see what you mean, that makes sense.

I don't have a specific idea in mind for that right now 🤔 I wish there was a simple trick for this problem.

**Comment by jlherren** [comment]
Seems like 6.0.10 fixes this 🥳 Thanks all!
