### ISSUE TITLE
nested arrays extension/override with DI\add

### ISSUE THREAD

**Issue by juliangut** [PHP-DI/PHP-DI#691]
DI\add does not function on nested arrays, don't know if this behavior is by design, and thus expected, or not

```php
$originalDefinitions = [
    'settings' => [
        'vowels' => ['a', 'e', 'i'],
        'consonants' => ['b', 'c', 'd'],
    ],
];
$overrideDefinitions = [
    'settings' => DI\add([
        'vowels' => ['i', 'o', 'u'],
        'consonants' => DI\add(['f', 'g', 'h']), // <--- notice the add()
        'emojis' => ['👌', '👍', '😎'],
    ]),
];

$builder = new DI\ContainerBuilder();
$builder->addDefinitions($originalDefinitions, $overrideDefinitions);
$builder->build()->get('settings');
```

##### Expected result

```php
[
    'vowels' => ['i', 'o', 'u'],
    'consonants' => ['b', 'c', 'd', 'f', 'g', 'h']),
    'emojis' => ['👌', '👍', '😎']
]
```

##### Actual result

```php
[
    'vowels' => ['i', 'o', 'u'],
    'consonants' => ['f', 'g', 'h']),
    'emojis' => ['👌', '👍', '😎']
]
```

The result is the expected for vowels and emojis, it is replacing and adding new items to the array
On the other hand I expect consonants to be added to the array by using DI\add, what it actually happens is that DI\add does not consider the previous array and creates a new one with the provided data mimicking the replacement done on vowels

**Comment by mnapoli** [comment]
Hi, this is indeed by design, `add()` can unfortunately only be used at the root.

**Comment by juliangut** [comment]
Hi @mnapoli, unfortunately `decorate()` can't be used neither

I assume both add and decorate only work on `DI\Definition\Definition` and that is the reason they can't handle values in an array (which is contained in an `DI\Definition\ArrayDefinition`)

Do you devise a way in which this can be achieved? maybe making `add()` multilevel-aware by traversing the array and creating nested ArrayDefinition?

**Comment by mnapoli** [comment]
> Hi @mnapoli, unfortunately decorate() can't be used neither

Is there an exception thrown?

Or maybe by doing this (I'm not sure at all):

```php
$originalDefinitions = [
    'settings' => new ArrayDefinition([
        'vowels' => ['a', 'e', 'i'],
        'consonants' => ['b', 'c', 'd'],
    ]),
];
```

and then use `decorate()`?

**Comment by juliangut** [comment]
> DI\DependencyException: Definition "settings" contains an error: Decorators cannot be nested in another definition

@mnapoli indeed using decorate produces a very clear exception

Trying with ArrayDefinition as suggested and using `add` instead of `decorate` due to previous exception message is not successful either, same result as my original comment, array content gets replaced completely

Maybe allowing decorator to be used on nested definitions?

**Comment by juliangut** [comment]
Hello again @mnapoli 

I wanted to ask, what is the reason `decorate` cannot be used within another definition while `env` or `factory` can? is there a way to circumvent this or the way it is design forbids it entirely?

**Comment by mnapoli** [comment]
Oh OK I meant to use the decorator at the root. Indeed it can't be nested because we need to figure out "what" the decorator is decorating (what is the target definition). When you are inside an array, then there is no specific definition to reference.
