### ISSUE TITLE
PHP-DI definition is not indexed by an entry name in the definition array

### ISSUE THREAD

**Issue by sam1238801** [PHP-DI/PHP-DI#701]
Fatal error: Uncaught Exception: The PHP-DI definition is not indexed by an entry name in the definition array in
C:\new_xampp\htdocs\project\vendor\php-di\php-di\src\Definition\Source\DefinitionArray.php:45
Stack trace:
#0 C:\new_xampp\htdocs\project\vendor\php-di\php-di\src\ContainerBuilder.php(148):
DI\Definition\Source\DefinitionArray-&gt;__construct(Array, Object(DI\Definition\Source\ReflectionBasedAutowiring))
#1 [internal function]: DI\ContainerBuilder-&gt;DI\{closure}(Array)
#2 C:\new_xampp\htdocs\project\vendor\php-di\php-di\src\ContainerBuilder.php(143): array_map(Object(Closure), Array)
#3 C:\new_xampp\htdocs\project\public\index.php(33): DI\ContainerBuilder-&gt;build()
#4 {main}
thrown in <b>C:\new_xampp\htdocs\project\vendor\php-di\php-di\src\Definition\Source\DefinitionArray.php on line45

**Comment by sam1238801** [comment]
I am getting the above fatal error which in postman while posting the email and password for JWT Authentication in Slim3

**Comment by mnapoli** [comment]
I don't think this is a bug in PHP-DI. Rather it is telling you you probably have a mistake in your configuration file (a definition is not indexed by a class name or a string).

**Comment by mnapoli** [comment]
Closing since you opened https://stackoverflow.com/questions/59499047/php-di-definition-is-not-indexed-by-an-entry-name-in-the-definition-array
