### ISSUE TITLE
PHP-DI - SLIM - Request/Response Availability

### ISSUE THREAD

**Issue by davidgithub1980** [PHP-DI/PHP-DI#703]
Hi. Thanks for the wonderful product. There is a clear example:

```
use Psr\Http\Message\{RequestInterface as Request, ResponseInterface as Response};

class UserController
{
    private $userRepository;
    
    public function __construct(UserRepository $userRepository)
    {
        $this->userRepository = $userRepository;
    }

    public function delete(Request $request, Response $response)
    {
        $this->userRepository->remove($request->getAttribute('id'));
        
        $response->getBody()->write('User deleted');
        return $response;
    }
}

$app->delete('/user/{id}', ['UserController', 'delete']);
```

However, I seem to lack the following functionality or, perhaps, it is there, but not documented. Inside **PHP-DI** definition file, I would like to distribute the content of the **Request/Response** entities via constructor injections to both the **UserRepository** above as well as to other entities inside the PHP-DI definition file. ... I tried injecting via the **UserRepository** constructor, but it, unexpectedly, errors out saying: _the class is not instantiable_. Is injecting **Request/Response** via dependencies constructor possible (just like, for example, in Symfony, Nette etc.) just like it is via the **delete** method above?

**Comment by mnapoli** [comment]
DUplicates https://github.com/PHP-DI/Slim-Bridge/issues/58
