### ISSUE TITLE
[Feature request] Injection point metadata access in factories

### ISSUE THREAD

**Issue by juherr** [PHP-DI/PHP-DI#704]
Kind of duplication of https://github.com/PHP-DI/PHP-DI/issues/529 where I'd like to have access to the injection point metadata.

A similar feature is available on Ray.Di (https://github.com/Ray-Di/Ray.Di#injection-point).

**Comment by mnapoli** [comment]
Thanks for the idea, that is not something that I plan on adding in PHP-DI at the moment because I try to limit the complexity (or bloat) of the package.
