### ISSUE TITLE
Is there a way to cache annotations ?

### ISSUE THREAD

**Issue by tristanbes** [PHP-DI/PHP-DI#705]
Hello,

I just ran some blackfire traces of my application that uses PHPDI.

Blackfire said that Doctrine annotations should be cached in production;
![stupid_forget_profile_-_Blackfire](https://user-images.githubusercontent.com/346010/73735997-62d7a480-4740-11ea-909d-2c4d3f4d49fc.png)

I did enable the PHPDI cache, but it seems uneffective on annotations, so:

Is there an option I missed that enables cache annotations ? (or maybe it's not PHPDI responsability and it should be enabled outside the lib? (https://www.doctrine-project.org/projects/doctrine-annotations/en/1.6/annotations.html#setup-and-configuration)

Thanks :)

**Comment by mnapoli** [comment]
Hello!

> I did enable the PHPDI cache

Not sure which one it is so just to be sure, you should enable:

- compiling the container (http://php-di.org/doc/performances.html#compiling-the-container)
- the APCu cache (http://php-di.org/doc/performances.html#caching)

The APCu cache should avoid reading Doctrine's annotation every time.

Is that what you do?

**Comment by tristanbes** [comment]
Stupid mistake, I didn't notice compiling the container & caching it was 2 different steps; I only compiled it;

Caching it now cache the annotations too; sorry for the noise :)
