### ISSUE TITLE
Support PHP7.4 typed properties in combination with `@var`

### ISSUE THREAD

**Issue by bzikarsky** [PHP-DI/PHP-DI#707]
There does not seem to be support for this currently. I did a quick test - and this works in theory in `AnnotationBadedAutowiring::readProperty()`:

```php
// @Inject("name") or look for @var content
$entryName = $annotation->getName();

if ($entryName === null) {
    $entryName = $property->getType()
        ? $property->getType()->getName()
        : $this->getPhpDocReader()->getPropertyClass($property);
}
```

instead of

```php
// @Inject("name") or look for @var content
$entryName = $annotation->getName() ?: $this->getPhpDocReader()->getPropertyClass($property);
```

It obviously needs a check for versions < PHP7.4 and tests. But is this something you'd accept a PR for?

**Comment by mnapoli** [comment]
Yes definitely, that would be great!

**Comment by bzikarsky** [comment]
See #708; I'll close this issue in favour of the MR
