### ISSUE TITLE
Suggestion - add `make` to `ContainerInterface`

### ISSUE THREAD

**Issue by jamesaspence** [PHP-DI/PHP-DI#712]
Hi all, there might be a very specific reason why the two of these interfaces were separated, but let me explain what I'm doing. See below code example:

```php
$containerBuilder->addDefinitions([
    Foo::class => function (ContainerInterface $c) {
        return new Foo('val1', 'val2', $c->get(Bar::class));
    }
]);
```

In the above example, I'd like to inject a `Bar` instance into my new instance of `Foo`. However, if I'd like that to be a newly-generated instance of `Bar`, I cannot use `make` as `make` is not defined on `ContainerInterface`.

The docs mention that the likely solution for this would be to write an actual factory for `Bar` and instead use that to instantiate my instance of `Bar` every time, but it seems a bit verbose to generate a factory every single time I want to be able to avoid singletons of an object.

I definitely could see this being argued as out of scope for the container layer but figured I'd suggest we just have `ContainerInterface` extend `FactoryInterface`. That would mean that we could call `make` on that `ContainerInterface` and be able to generate instances on the fly.

**Comment by SvenRtbg** [comment]
Are you talking about this interface: `use Psr\Container\ContainerInterface;`? If you want to change that, you have to talk to the authors of that PHP standard recommendation. Currently, it only forces the methods `get()` and `has()`, and I do not think it will ever be extended to support `make()`.

For the same reason, this interface cannot be changed to extend another interface. You'd lose all benefits from implementation-agnostic interoperability.

**Comment by mnapoli** [comment]
Yes, the PSR is completely separate from PHP-DI (and very unlikely to change).

In your example, nothing prevents you to type `Container` instead of the interface (or even `FactoryInterface`).

**Comment by jamesaspence** [comment]
Ah, sorry - didn't realize `ContainerInterface` was the PSR `ContainerInterface`. re: type hinting `Container` instead, I went down that path but noticed this line in your docs: http://php-di.org/doc/php-definitions.html#factories

> When injecting the container, you should type-hint against the interface Psr\Container\ContainerInterface instead of the implementation DI\Container.

If injecting `Container` is the right way to go here then maybe it'd be better to change that doc a little bit to not discourage the type hinting? That line is what led me here to create this issue as I wasn't sure what the best approach would be.

**Comment by mnapoli** [comment]
It's a best practice, but it's very fine to type-hint against `Container` (or to go against a best practice if you know why).

I think it's best to keep that line in the docs though.
