### ISSUE TITLE
6.2.0 breaks backwards compatibility

### ISSUE THREAD

**Issue by chekalsky** [PHP-DI/PHP-DI#719]
After the #717 my Guzzle DI stopped working because of the usage of the `static` keyword with  function inside the constructor.

Getting this exception: `Cannot compile closures which use $this or self/static/parent references`.

```php
...
Guzzle::class => function (LoggerInterface $logger) {
        $handler_stack = HandlerStack::create();
        $handler_stack->push(Middleware::retry(static function (
            $retries,
            \GuzzleHttp\Psr7\Request $request,
            \GuzzleHttp\Psr7\Response $response = null,
            RequestException $exception = null
        ) use ($logger) {
           ...
        }, static function ($retries) {
            return 750 * $retries;
        }));

        return new Guzzle([
            'handler' => $handler_stack
        ]);
    },
...
```

After digging I found it's because of static functions inside the closure. They make `$isUsingScope = true` [here](https://github.com/opis/closure/blob/039b5cc00cc8c1fa4c67311843efce5ff5626cce/src/ReflectionClosure.php#L571).

I've fixed it by removing `static` keyword.

**Comment by mnapoli** [comment]
Thank you for the report, this is indeed related to the switch to opis/closure. I think this is a false positive in their detection system: the `static` keyword here is not related to the scope.

I'll report it to their project.

> I've fixed it by removing static keyword.

Thanks for the workaround.

**Comment by mnapoli** [comment]
I've released https://github.com/PHP-DI/PHP-DI/releases/tag/6.2.1
