### ISSUE TITLE
[Feature Request] Resolve rest of constructor arguments from container

### ISSUE THREAD

**Issue by jamesaspence** [PHP-DI/PHP-DI#720]
Hi all, great job on this library! It's been awesome so far.

Assume I have a class defined like this:
```
class Foo
{
    public function __construct(Dep $dep, array $values) {
        ...
    }
}
```

If possible, I'd like to specify the value of `$values` without touching `Dep`, and have `Dep` be resolved automatically. I know I can create a definition like this:
```
\DI\create(Foo::class)->constructor(\DI\get(Dep::class), \DI\get('foo.values'))
```

but I'm hoping for something like this:
```
\DI\create(Foo::class)->parameter('values', \DI\get('foo.values'))
```

where I don't need to specify the rest of the arguments of the constructor. My hope is to reduce the amount of config when I write a class that has a single dependency that isn't automatically resolvable. I suppose I could use autowiring as well but haven't used it yet, so I'd prefer to remain consistent.

Hopefully that makes sense - it'd be a nice to have and I definitely have workarounds in the meantime. Thanks!

**Comment by JoeBengalen** [comment]
Are you looking for `constructorParameter`?

**Comment by jamesaspence** [comment]
Yep! I didn't see anything like that in the docs or intellisense - does that already exist?

**Comment by jamesaspence** [comment]
ohhh I see - so I could use `\DI\autowire` - I'll give that a go!

**Comment by jamesaspence** [comment]
Yep, this is 100% what I was hoping for and I'm so happy it exists! Thanks so much for pointing me in the right direction - closing this.
