### ISSUE TITLE
Add "function call" definition to call specific function/callable at runtime

### ISSUE THREAD

**Issue by filips123** [PHP-DI/PHP-DI#722]
Currently, if you use function call as value of entry or array, its result will be compiled and used for every run. This means that function will never be called again (until you delete cache) and result will remain the same.

Calling functions at runtime can be useful for configuration if you store configuration as array or normal values. It can be used to, for example, get date or time of execution (useful if you want to save log files to new file every day), generate random execution identifier, make config depending on environment (there is already `DI\env` but it is limited to just `getenv` function)...

I would like to propose "function call" definition (which can be shortened as `DI\call` helper), which takes callable and callable's parameters and executes it on runtime, regardless if container is compiled or not. For non-compiled containers, this can be done using `call_user_func`, and for compiled containers, this can be done with constructing actual function call code and saving it into compiled container.

I can submit PR for this soon (it already works but I still need to write docs). More details how this definition works are below.

For example, if you want to get date and time of execution, you can add those two entries to container builder definitions:

```php
'date' => DI\call('date', 'Y-m-d'),
'time' => DI\call('date', 'H:m:s'),
```

Then they are compiled to (based on actual code but not actual code):

```php
protected function get1() {
    return date('Y-m-d');
}

protected function get2() {
    return date('H:m:s');
}
```

If you want to call static function of a class, you can write callable as `[TestClass::class, 'testFunction']` and this is compiled as `\TestNamespace\TestClass::testFunction()`. However, you can't use this on class instance (for example [$this, 'testFunction']` for the same reason as why you can't use `use`, `$this` or self/static/parent references in closures.

Closures are also callables, and `DI\call` should support them as well (which works similar as `DI\factory` or directly writing closures to definitions). For example, this closure call:

```php
'calculation' => DI\call(function () {
    $value1 = rand(1, 100);
    $value2 = rand(1, 100);
    $value3 = max($value1, $value2) + 10;

    return $value1 / $value2 * $value3;
}),
```

Is compiled to:

```php
protected function get1() {
    return (static function () {
        $value1 = rand(1, 100);
        $value2 = rand(1, 100);
        $value3 = max($value1, $value2) + 10;

        return $value1 / $value2 * $value3;
    })();
}
```

All function call definitions should also accept other/nested definitions as parameters, which should be resolved before function is called, so function just gets values:

```php
'calculation' => DI\call(function ($value1, $value2) {
    $value3 = max($value1, $value2) + 10;

    return $value1 / $value2 * $value3;
}, Di\get('value1'), DI\get('value2')),

'value1' => 10,
'value2' => 20,
```

Which is compiled to:

```php
protected function get2() {
    return $this->delegateContainer->get('value1');
}

protected function get3() {
    return $this->delegateContainer->get('value2');
}

protected function get1() {
    return (static function ($value1, $value2) {
        $value3 = max($value1, $value2) + 10;

        return $value1 / $value2 * $value3;
    })($this->get2(), $this->get3());
    }
```

It should also work in reverse. If function returns definition, it should be resolved before user gets it:

```php
'config' => DI\call(function ($env) {
    return $env === 'dev' ? DI\get('config.dev') : DI\get('config.prod');
}, DI\get('env')),

'config.dev' => [1],
'config.prod' => [2],
'env' => 'dev',
```

Which is compiled to:

```php
protected function get1() {
    $value = (static function ($env) {
        return $env === 'dev' ? \DI\get('config.dev') : \DI\get('config.prod');
    })($this->get2());
    if ($value instanceof \DI\Definition\Definition) {
        return $this->resolveDefinition($value);
    }
    return $value;
}
```

So user just gets `[1]` when they access `config` entry. Note that this is not limited to closures, but works with any callable which is passed to `DI\call`.

Note that some of this can be already implemented using `DI\factory`, but that doesn't work good for built-in PHP functions with optional parameters:

```php

// Providing just required parameters:
'date' => DI\factory('date')
    ->parameter('format', 'Y-m-d')

// Will cause:
// PHP Warning:  date() expects parameter 2 to be int, object given

// However, providing all parameters:
'date' => DI\factory('date')
    ->parameter('format', 'Y-m-d')
    ->parameter('timestamp', time()),

// Will also not work correctly
// Because now time() is also cached and date() will again return the same result

// So you now have to do:
'date' => DI\factory('date')
    ->parameter('format', 'Y-m-d')
    ->parameter('timestamp', DI\factory('time')),

// Compared to just:
'date' => DI\call('date', 'Y-m-d'),
```

The best currently available alternative is to wrap function call into factory closure but it is still more to do than just function call definition:

```php
'date' => function () {
    return date('Y-m-d');
},
```

And it also doesn't support resolving definitions at runtime.

**Comment by mnapoli** [comment]
```php
'date' => function () {
    return date('Y-m-d');
},
```

sounds really good, why not use this?

With PHP 7.4, that can even be:

```php
'date' => fn() =>date('Y-m-d'),
```

**Comment by filips123** [comment]
Oh, I forgot about PHP 7.4 arrow functions. That's basically what I need.

They still don't support resolving return definitions at runtime, but I don't really need this and I don't know how useful would it be in general.
