### ISSUE TITLE
How can I get a fresh new instance?

### ISSUE THREAD

**Issue by LuanMaik** [PHP-DI/PHP-DI#725]
Is this implementation right? Does it return the SAME instance every time (the same memory allocation)?

```php
// /src/Container.php line 126
public function get($name)
{
  // If the entry is already resolved we return it
  if (isset($this->resolvedEntries[$name]) || array_key_exists($name, $this->resolvedEntries)) {
      return $this->resolvedEntries[$name];
  }
....
```

The strange behavior:

```php
$container->set('Foo', new Foo());
$foo = $container->get('Foo');
$foo->setBar('bazz');

$foo2 = $container->get('Foo');
$foo2->getBar(); //'bazz'
```

Is this fine? How can I get a fresh new instance?

Open my eyes guys kkkk

**Comment by LuanMaik** [comment]
I'm using with Slim framework
https://php-di.org/doc/frameworks/slim.html

**Comment by LuanMaik** [comment]
I found the method `$container->make($name)` that create and return a new instance, but how can I change the default behavior `$container->get('Foo')` to `$container->make('Foo')` in dependency injection resolver in Slim integration?


My code:
```php
use DI\Container;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;

require __DIR__ . '/../vendor/autoload.php';


// Create Container using PHP-DI
$container = new Container();

$container->set(\App\Modules\Core\Interfaces\TesteInterface::class, function() {
    return new \App\Modules\Core\Teste();
});

$app = \DI\Bridge\Slim\Bridge::create($container);

// Api route definition
$app->get('/api/path/teste', [FooController::class,'bar']);


class FooController 
{
       public function bar(TesteInterface $teste) 
       {
           //...
       }
}
```

**Comment by LuanMaik** [comment]
I found this link that relate the same problem:
https://discourse.slimframework.com/t/slim-4-php-di-getting-new-instance-from-container/3650

**Comment by mnapoli** [comment]
Yes this is how PHP-DI work, use `make()` to create a new instance every time.

Service containers work like this because services are supposed to be stateless.
