### ISSUE TITLE
facing a Problem in setter injection

### ISSUE THREAD

**Issue by kingx619** [PHP-DI/PHP-DI#748]
Hello Matthieu sir,

I am facing a problem in setter injection

```php
class Application{

public Router $router;
private Controller $controller;

   public function __construct(Router $router)
  { 
       $this->router = $router;
   }
    public function getController()
    {
        return $this->controller;
    }

    public function setController(Controller $controller)
    {
        $this->controller = $controller;
    }
}
```

In my config file i am doing like this

```php
return [
'Application' =>   \DI\autowire()->constructor(\DI\get('Router'))->method('setController',DI\get('Controller'))
];
```

I am trying to do setter injection using php-di but when I var dump($container) in the fetched array I see an empty method injections array  #methodInjections: [] . What i am doing wrong and how can i achieve this setter injection

**Comment by mnapoli** [comment]
Hi,

Does that work when the code runs? Is `setController()` called?

(I think it's better to discuss the end result first, rather than debug the internals of PHP-DI)

If you have an error message please share it.

**Comment by kingx619** [comment]
Pouvez-vous faire une vidéo sur php-di-6 sur votre chaîne YouTube. La vidéo que vous avez pour php-di a 5 ans. Si une vidéo est possible, merci de me le faire savoir.
