### ISSUE TITLE
make() doesn't work with alias

### ISSUE THREAD

**Issue by CharleysTante** [PHP-DI/PHP-DI#753]
The whole example is in the same file (PHP-DI 6.3.0):
```
<?php
namespace app\src\test;

$builder = new \DI\ContainerBuilder();
$builder->useAutowiring(true);
$builder->useAnnotations(true);
$builder->enableCompilation(__DIR__ . '/tmp');
$builder->addDefinitions([
   'MyAlias' => \DI\get(GithubProfile::class),
]);
$container = $builder->build();

// The following is working fine for me:
$User = $container->make('\app\src\test\GithubProfile', [
    'user' => 'frank',
]);

// But with an alias it doesn't work:
$User = $container->make('MyAlias', [
    'user' => 'frank',
]);
```
Error message:
`Fatal error: Uncaught DI\Definition\Exception\InvalidDefinition: Entry "app\src\test\GithubProfile" cannot be resolved: Parameter $user of __construct() has no value defined or guessable Full definition: Object ( class = app\src\test\GithubProfile lazy = false __construct( $client = get(app\src\test\ApiClient) $user = #UNDEFINED# ) ) in C:\htdocs\Container_Test\vendor\php-di\php-di\src\Definition\Exception\InvalidDefinition.php:18 Stack trace: #0 C:\htdocs\Container_Test\vendor\php-di\php-di\src\Definition\Resolver\ObjectCreator.php(156): DI\Definition\Exception\InvalidDefinition::create(Object(DI\Definition\ObjectDefinition), 'Entry "app\\src\\...') #1 C:\htdocs\Container_Test\vendor\php-di\php-di\src\Definition\Resolver\ObjectCreator.php(71): DI\Definition\Resolver\ObjectCreator->createInstance(Object(DI\Definition\ObjectDefinition), Array) #2 C:\htdocs\Container_Test\vendor\php-di\php-di\src\Definition\Resolver\ResolverDispatcher.php(71): DI\Definition\Resolver\ObjectCreator->re in C:\htdocs\Container_Test\vendor\php-di\php-di\src\Definition\Exception\InvalidDefinition.php on line 18`

**Comment by mnapoli** [comment]
Hi,

Yes, `make()` will not traverse the alias. Here the parameters are not forwarded to the constructor of the target object, but even then the `make()` will actually call `get(GithubProfile::class)` (it will not create a new instance).

That's how PHP-DI works: `make()` applies to `get()`, not the target.

**Comment by CharleysTante** [comment]
Thank you for your reply :-)
However, this should be included in the doc under "The make() method works like get() except it will resolve the entry every time it is called."
Is there any plan to add this feature?

Thanks Klemens

**Comment by mnapoli** [comment]
Technically it resolves the `get()` entry (the reference) every time it is called.

There is no plan to change that at the moment.

**Comment by CharleysTante** [comment]
Thanks :-)
