### ISSUE TITLE
Overriding array values recusrively

### ISSUE THREAD

**Issue by mareeo** [PHP-DI/PHP-DI#758]
Related to overriding array values as described [here](https://php-di.org/doc/definition-overriding.html#arrays):

This doesn't work if you're wanted to override a nested array. For example, I define default settings in one definition file...

```php
return [
    'settings' => [
        // Database settings
        'db' => [
            'host' => 'localhost',
            'user' => '',
            'pass' => '',
            'dbname' => 'test',
        ]
];
```

... and then environment specific settings in another file to override the default

```php
return [
    'settings' => DI\add([
        // Database settings
        'db' => [
            'user' => 'REALUSERNAME',
            'pass' => 'REALPASSWORD',
        ]
    ])
];
```

I'd expect to end up with 
```php
'settings' => [
   'db' => [
      'host' => 'localhost',
      'user' => 'REALUSERNAME',
      'pass' => 'REALPASSWORD',
      'dbname' => 'test',
   ]
]
```

But instead the second value just overwrites the first
```php
'settings' => [
   'db' => [
      'user' => 'REALUSERNAME',
      'pass' => 'REALPASSWORD'
   ]
]
```

I'm guessing the solution to this is modifying https://github.com/PHP-DI/PHP-DI/blob/master/src/Definition/ArrayDefinitionExtension.php#L28 to manually walk the array and merge the values of any nested `ArrayDefinition` instead of using `array_merge`. 

Or another solution would to be update the documentation to say overriding nested values isn't supported 😀. It's not difficult to switch to values such as `db.host` instead of actual nested arrays and the overriding works fine once I do this, I guess it just wasn't obvious for a newbie reading the documentation.

Thanks!

**Comment by mnapoli** [comment]
Hi, yes this is the intended behavior. Nested merging would be quick complex to understand, so I'd rather stay with the current behavior.

I'm 👍  for a PR that makes that more explicit in the documentation.
