### ISSUE TITLE
Autowiring performance

### ISSUE THREAD

**Issue by Chi-teck** [PHP-DI/PHP-DI#759]
The [documentation](https://php-di.org/doc/autowiring.html) states the following.
> Autowiring does not affect performances when compiling the container.

Is it really true? I am using PHP-DI in Slim framework. Seems like services that are not registred explicitly through `$builder->addDefinitions()` are never complied. So that autowired services always invlove full resolving process in runtime.

**Comment by mnapoli** [comment]
Hi, you're correct, please check out : https://php-di.org/doc/performances.html#optimizing-for-compilation
