### ISSUE TITLE
Error when using PHP 8 named parameters

### ISSUE THREAD

**Issue by Chi-teck** [PHP-DI/PHP-DI#760]
## Code example

```php
function hello(string $name): void {
    echo "Hello $name!";
}

$example = function () {
    hello(name: 'Foo');
};

$wrapper = new SerializableClosure($example);
$result = unserialize(serialize($wrapper));
```

## Result
```
PHP Parse error:  syntax error, unexpected token ":", expecting ")" in closure://function (): void {
    \hello(\name: 'Foo');
} on line 3
```

**Comment by mnapoli** [comment]
Hi, that could be a bug in https://github.com/opis/closure. AFAICT they support PHP 8, could you make sure you use their latest version?

If you still have the problem, I think you should open an issue there.

**Comment by Chi-teck** [comment]
Right, it this was supposed to be created in opis/closure issue queue.
