### ISSUE TITLE
Autowiring / resolving primitive / built-in types

### ISSUE THREAD

**Issue by mrmedicine** [PHP-DI/PHP-DI#765]
I've enjoyed working with PHP-DI, but now I'm running into the following scenario: 

I have a lot of services that have a debug boolean in their constructor. I would like to map / autowire this value  (by name?). 

Is this already possible / am I missing something? Or do I have to specify each service / repo etc that has a debug bool in the constructor? Is it outside the scope of this project?

e.g I have the follow definition:

```
 'debug' => true,
 ```

example of service contructor:
```
   public function __construct(
        SomeInterface $someInstance,
        SomeInterface $someInstance,
        SomeInterface $someInstance,
        bool $debug
    )
```

P.s my workaround would be to construct a wrapper class around the debug boolean which will be able to be resolved but this is not preferred.

**Comment by mnapoli** [comment]
Hi,

This is something that has indeed been suggested before, but it's still something not planned to be implemented (because it is a bit too magical).

Closing for now.
