### ISSUE TITLE
Definition file not being read

### ISSUE THREAD

**Issue by alanondra** [PHP-DI/PHP-DI#781]
OS: LMDE
PHP: 8.0.5
PHP-DI: 6.3.3 

Other relevant packages:
- `psr/http-message`
- `psr/http-factory`
- `guzzlehttp/psr7`
- `http-interop/http-factory-guzzle`

Building the container:

```php
$builder = new DI\ContainerBuilder();

$builder->useAutowiring(true);
$builder->useAnnotations(true);

// $context->path() renders the path to the given file relative to the application root
$builder->addDefinitions($context->path("etc/config/web.php"));

// $debug = true;
$container = ($debug)
	? $builder->buildDevContainer()
	: $builder->build();

// expected instance of Http\Factory\Guzzle\ResponseFactory
var_dump($container->get(Psr\Http\Message\ResponseFactoryInterface::class));
```

The definition file (`etc/config/web.php`):

```php
use Psr\Http\Message;
use Http\Factory\Guzzle;

return [
	Message\RequestFactoryInterface::class => DI\create(Guzzle\RequestFactory::class),
	Message\ResponseFactoryInterface::class => DI\create(Guzzle\ResponseFactory::class),
	Message\ServerRequestFactoryInterface::class => DI\create(Guzzle\ServerRequestFactory::class),
	Message\StreamFactoryInterface::class => DI\create(Guzzle\StreamFactory::class),
	Message\UploadedFileFactoryInterface::class => DI\create(Guzzle\UploadedFileFactory::class),
	Message\UriFactoryInterface::class => DI\create(Guzzle\UriFactory::class),
];

```

The error I'm getting:

	DI\Definition\Exception\InvalidDefinition: Entry "Psr\Http\Message\ResponseFactoryInterface" cannot be resolved: the class is not instantiable

I've dumped the resulting array from `require`ing the definition file and gotten an associative array of definitions so there's no parser error. It seems to just not be using the definition.

**Comment by SvenRtbg** [comment]
`addDefinitions()` requires the array of definitions, not a string to a file. See here: https://php-di.org/doc/php-definitions.html first section: 

    $containerBuilder->addDefinitions([
        // place your definitions here
    ]);

**Comment by SvenRtbg** [comment]
Ok, you need not feel dumb, but I might feel dumb. The source code states that you may also pass a string as a file name. That was news to me, and I personally do not see the benefit if the simplest thing instead would be to just `require` the file outside of PHP-DI.

This either is an error in the source code comments (even though it specifically checks for string, array or DefinitionSource instances) because the part about strings is not true anymore, or incomplete documentation omitting the part about strings. Anyway, I think you have found an issue. :)

**Comment by alanondra** [comment]
Right, I was confused because that same documentation also shows:

> Or by putting it into a file returning an array:
> 
> ```php
> <?php
> return [
>     // place your definitions here
> ];
> ```
> 
> ```php
> $containerBuilder->addDefinitions('config.php');
> ```

**Comment by mnapoli** [comment]
Hi both,

Regarding this issue, `buildDevContainer()` is a static method (you are calling it not statically). It completely ignores any config you may have done:

https://github.com/PHP-DI/PHP-DI/blob/master/src/ContainerBuilder.php#L111-L114

On a separate note, passing the file name is very valid: files are loaded lazily, sometimes when things are cached they are not even read.
