### ISSUE TITLE
Autowiring only defined Classes

### ISSUE THREAD

**Issue by philippzeuch** [PHP-DI/PHP-DI#782]
Hey everyone,

i want to use constructor and property injection but i want php-di to only use the definitions from my php class definition file when trying to inject a dependency. When I set `useAnnotations()` or `useAutowiring()` to true, the `DefinitionSource` class always tries to create any class I am trying to inject even though it is not defined in my FileDefinition.

I am a Java developer and I am used to the mechanism of "Spring DI", which throws an exception when a class is injected but not defined in the class definitions.

It looks like I cannot achieve what I am trying to do in combination with autowiring. Do I have to turn off autowiring and do I have to do everything by myself via the file definitions???

Thanks in advance!

**Comment by mnapoli** [comment]
Hi, yes this is what you would have to do in that case, that use case isn't really supported.

**Comment by philippzeuch** [comment]
okay thx!

**Comment by royvangeel** [comment]
like to see this feature also; autowire only the classes you register in the container
