### ISSUE TITLE
Creating compilation directory is not atomic

### ISSUE THREAD

**Issue by martin-heralecky** [PHP-DI/PHP-DI#785]
Creating the compilation directory for compiled file with definitions is not atomic and fails, if multiple instances of PHP are executed in parallel.

**How to reproduce:**

1) Create a sample script:
```php
<?php

require_once __DIR__ . "/vendor/autoload.php";

$builder = new DI\ContainerBuilder();
$builder->addDefinitions(['foo' => 'bar']);
$builder->enableCompilation(__DIR__ . "/tmp");
$builder->build();
```

2) Simulate slow disk by adding delay between `is_dir()` and `mkdir()` in `Compiler::createCompilationDirectory` (https://github.com/PHP-DI/PHP-DI/blob/master/src/Compiler/Compiler.php#L361):
```php
if (!is_dir($directory) && (sleep(1) || true) && !@mkdir($directory, 0777, true)) {
//                         ^^^^^^^^^^^^^^^^^^
```

3) Run the sample script multiple times in parallel:
```shell
rm -rf tmp/ && php script.php & php script.php && wait
```

Exception is thrown `Uncaught InvalidArgumentException: Compilation directory does not exist and cannot be created`.

If this is accepted as a bug, I am willing to create a patch for a fix.

**Comment by mnapoli** [comment]
> If this is accepted as a bug, I am willing to create a patch for a fix.

Hi! At first look that is indeed something that would be better fixed. If you can make a patch that's awesome!
