### ISSUE TITLE
No compilation/cache benefit

### ISSUE THREAD

**Issue by plasid** [PHP-DI/PHP-DI#788]
I'm trying to understand if there is truly a benefit to using ->enableCompilation(dir)?

1. addDefinitions(...) internally does not care if compilation is on or off, it will set the definitions from original source again.
2. With a cache/CompiledContainer.php PHP-DI still have the  disc I/O overhead to check/read the cached compiled file.
3. cache/CompiledContainer.php looks like a copy of the original definitions array and not much internal optimisation, I would have expected the it to return the results of definition factories/closures and not re-run logic inside them, or at least where scalars and arrays were returned.

Example:

I have a container definition closure that makes a database connection to load settings defined in a table, process them and returns an array of key/value pairs.
I do not want this database query to run on every page load, I expect the cached version of this closure to return the original/first array only.

**Comment by mnapoli** [comment]
> I have a container definition closure that makes a database connection to load settings defined in a table, process them and returns an array of key/value pairs.

I think you may be misunderstanding what the compilation/definition cache is about.

If your closure is a container entry, then it will never be cached. That's not the goal. PHP-DI does not cache your container entries.

PHP-DI will cache or compile the _definition_ of the container entries (i.e. "how to retrieve/create your entries").

For example, if you configure PHP-DI over 5 different PHP files, the compiled container will merge all of that and will optimize things like creating objects.

> With a cache/CompiledContainer.php PHP-DI still have the disc I/O overhead to check/read the cached compiled file.

FYI the compiled container is stored in opcache so there is no disc I/O.

**Comment by plasid** [comment]
Thank you for the explanation, but opCache is optional, else the file is read from disc location?

**Comment by mnapoli** [comment]
Opcache is built-in PHP by default. Not using it in production would make no sense, at this point talking about performances is pointless.

With opcache, the file is read from disk only once.

**Comment by plasid** [comment]
True, skipped my mind
