### ISSUE TITLE
php 8.1 support with opis/closure:4.x-dev

### ISSUE THREAD

**Issue by xpader** [PHP-DI/PHP-DI#791]
php-di now can't support closure serialize with php 8.1, need depend on opis/closure:4.x-dev.

**Comment by mnapoli** [comment]
Opis/closure 4 uses FFI: https://github.com/opis/closure/issues/59

I'm afraid this will not really work with PHP-DI as FFI is an extension that will not be installed everywhere. Laravel will probably get the same problem here.

**Comment by deleugpn** [comment]
Laravel has forked opis/closure: https://github.com/laravel/serializable-closure

**Comment by ldebrouwer** [comment]
Any update on this?

**Comment by shadowhand** [comment]
@mnapoli PR #808 created that applies the minimum changes required to resolve this.
