### ISSUE TITLE
Compilation with excludes

### ISSUE THREAD

**Issue by naletups** [PHP-DI/PHP-DI#798]
We are using PHP-DI for injection of classes, but also for some static and dynamic meta information.
```
A::class => autowire(),
"cfgFile" => loadFile('cfg/a'), // loads contents of cfg/a.php into the cfgFile "object" (an array)
"http.server" => $_SERVER,
// ...
```

An example of static meta information for a call is some static file contents, e.g. that of a configuration file. This works well. We also use it to load dynamic contents into classes, e.g. the content of `$_SERVER`. This works also well.

Yet, the problem with dynamic loading is that when we turn compilation on, the first request is used for compilation. This works for all the static contents fine, yet for the dynamic - obviously - not. In this case, the contents of the `$_SERVER` variable gets written into the compilation file and is used from now on. Is there some way to exclude a certain entry from compilation so it is always loaded a-new?

**Comment by mnapoli** [comment]
Hi, storing any kind of state in the container is something to avoid completely.

There are many similar issues on the topic, you can check them out (search for "stateless service" or similar).

So in short: never store stateful data (session, user data, request data…) in the container, whether it's compiled or not. PHP-DI (and most containers) are not meant to support that.
