### ISSUE TITLE
Create a new instance each time?

### ISSUE THREAD

**Issue by dirtside** [PHP-DI/PHP-DI#799]
Most of the time, I'm fine with PHP-DI's standard behavior of providing the same copy of an object each time it does injection; most of classes in my project contain no state. However sometimes I want to tell it that _every time_ it creates an object of a certain class, it should create a new one (for those cases where it's a stateful object, and I want each one to start out clean). I've read through the documentation and for the life of me can't figure out how to do this. Examples:
```
class Foo {
    public function __construct(private Alpha $alpha) {}
}

$di = new Container();
$foo1 = $di->get('Foo');
$foo2 = $di->get('Foo');
```
In this example, the `Alpha` object inside both `$foo1` and `$foo2` is the same object. But I want them to be different objects.

**Comment by SvenRtbg** [comment]
First of all, in your example you are getting the same Foo twice. It would be impossible for Foo to contain two different Alphas.

If you need new instances, dependency injection is not the way to get them. Either inject a factory object to create them, or call new.

**Comment by mnapoli** [comment]
Hi, check out other issues on the topic, e.g. https://github.com/PHP-DI/PHP-DI/issues/725 and #409 

You can use `$container->make()` instead of `get()`.
