### ISSUE TITLE
Is 6.3.5 compatible with PHP 8.1?

### ISSUE THREAD

**Issue by JimmyBanks** [PHP-DI/PHP-DI#803]
We are planning to move to PHP8.1 on our project, I see that 7.0 beta is intended for 8.0 features, but Is 6.3.5 stable with 8.1? (and 8.0?)

**Comment by someniatko** [comment]
It seems this project is abandoned a bit. Is author looking for funding?

**Comment by JimmyBanks** [comment]
@mnapoli just looking for some clarification

**Comment by mnapoli** [comment]
Hi, why would you assume the project is abandoned? I simply cannot just jump in every support request and question the minute it comes up.

Do you have any problem with 8.1? If you do, please report it.

**Comment by JimmyBanks** [comment]
Probably because the documentation hasn't been updated to reference 8.1 and you have a beta that specifically reference 8.0 that never released.

Well that rude reply has made it clear that I won't be sponsoring you.

**Comment by JimmyBanks** [comment]
> I simply cannot just jump in every support request and question the minute it comes up.

Then apologies if you feel rushed because I notified you; however, in my defence the question was asked 8 days ago

> Why would you assume the project is abandoned? 

What threw me off on whether 8.1 was supported was the 7.0 beta. I wanted to clarify that 6.3 is safe for 8.1, or if we should be waiting for 7, that is all.
