### ISSUE TITLE
Integration with Doctrine's RepositoryFactory

### ISSUE THREAD

**Issue by mnapoli** [PHP-DI/PHP-DI#81]
See https://github.com/doctrine/doctrine2/pull/695

It seems the feature will only be introduced in Doctrine 2.5 though.

**Comment by holtkamp** [comment]
:+1: 
This would be nice indeed. Some examples for the use with Doctrine Repositories as well

Got PHP-DI working with some ZendFramework 1 controllers. But now I am trying to inject Doctrine Repositories into my Domain Services. 

Because the Repositories need the Doctrine EntityManager during construction, this fails since the EntityManager is 'not instantiable'. 

For example, for my OrderDomainService, which depends on the OrderRepository:

```
Entry ProjectName\Domain\Service\Order cannot be resolved: 
Entry ProjectName\Domain\Repository\Entity\OrderRepository cannot be resolved: 
Entry Doctrine\ORM\EntityManager cannot be resolved:
class Doctrine\ORM\EntityManager is not instantiable

Full definition:
Object (
    class = #NOT INSTANTIABLE# Doctrine\ORM\EntityManager
    scope = singleton
    lazy = false
)
Full definition:
Object 
(
    class = Caos\Domain\Repository\Entity\OrderRepository
    scope = singleton
    lazy = false

    __construct(
        $em = link(Doctrine\ORM\EntityManager)
        $class = link(Doctrine\ORM\Mapping\ClassMetadata)
    )
)
Full definition:
Object (
    class = ProjectName\Domain\Service\Order
    scope = singleton
    lazy = false
    __construct(
        $orderRepository = link(ProjectName\Domain\Repository\Entity\OrderRepository)
    )
)
```

**Comment by mnapoli** [comment]
With the current approach you first need to store the entity manager in PHP-DI. Then you can get repositories from the entity manager:

```php
'Caos\Domain\Repository\Entity\OrderRepository' => DI\factory($c) {
    $em = $c->get('Doctrine\ORM\EntityManager');
    return $em->getRepository('Caos\Domain\Repository\Entity\Order');
},
```

**Comment by holtkamp** [comment]
Ok, thanks, and for the Entity Manager it would be okay to have the ```DI\factory``` fetch it from the Bootstrap?

```
'Doctrine\ORM\EntityManager' => DI\factory(
        function (\DI\Container $c) {
            $bootstrap = Zend_Registry::get('bootstrap');
            $bootstrap->bootstrap('Doctrine\ORM\EntityManager');
            return $bootstrap->getResource('Doctrine\ORM\EntityManager');
        }
    ),
```


Might it be an idea to handover the requested class name as second parameter to the factory?

```
'Doctrine\ORM\EntityManager' => DI\factory(
        function (\DI\Container $c, $classname) {
            $bootstrap = Zend_Registry::get('bootstrap');
            $bootstrap->bootstrap(classname);
            return $bootstrap->getResource(classname);
        }
    ),
```

**Comment by mnapoli** [comment]
Yes the first example is a good solution.

> Might it be an idea to handover the requested class name as second parameter to the factory?

This wouldn't work currently, and I don't know how it could work in theory: how would the container know what to pass for the `$classname` parameter?

By the way I did use PHP-DI in a ZF1 application and we slowly moved away from the Bootstrap and put everything into the container. It made everything a little simpler (and for example the connection to the database would only be done *if* it's actually used). But I guess that's a matter of taste, and if some other parts of the code rely of the Bootstrap then you don't have much of a choice.

**Comment by holtkamp** [comment]
>By the way I did use PHP-DI in a ZF1 application and we slowly moved away from the Bootstrap and put everything into the container.

Nice tip. Got some nice preliminary results related to this, it seems possible to:
- set up the Dependency Injection Container in index.php (as early as possible)
- use the DIC to fetch a (Zend) Config, to hand over to Zend_Application
- assign the container to Zend_Application's Bootstrap as main 'resource container'
- move one from there, gradually emptying Bootstrap.php and other ZF1-specific aspects

Will provide some documentation for the ZF1-Bridge when we got more results.

**Comment by mnapoli** [comment]
:+1: thanks that would be very useful (especially since some developers in the ZF1 world are not necessarily all familiar with the idea of DI containers).

**Comment by mnapoli** [comment]
Closing this 4 year old feature idea, let's reopen if we actually do something like this, I'm not even sure such a feature would be useful I've never tried it.

**Comment by fenric** [comment]
See how PHP-DI can be linked to Doctrine repositories:
https://github.com/autorusltd/doctrine-repository-factory
