### ISSUE TITLE
AnnotationBasedAutowiring::getAnnotationReader slow in big project

### ISSUE THREAD

**Issue by dmifedorenko** [PHP-DI/PHP-DI#815]
Good day.

According to profile I have performance issue with AnnotationBasedAutowiring in big project. getAnnotationReader method use SimpleAnnotationReader as ony way to get data, but SimpleAnnotationReader is very slow. It parses doc on every call.

Is there any chance to make optional ability to change `$this->annotationReader = new SimpleAnnotationReader();` to `$this->annotationReader = new PsrCachedReader($this->annotationReader, new ArrayAdapter());` inside `AnnotationBasedAutowiring`?

**Comment by mnapoli** [comment]
Hi, that exists, check out https://php-di.org/doc/performances.html

**Comment by dmifedorenko** [comment]
Thank you for answer. ACP extension was not configured in PHP.

By the way, on the Performances doc page there is no information about APC required.

**Comment by mnapoli** [comment]
Oh thanks, PR welcome to fix that!

**Comment by SvenRtbg** [comment]
It is mentioned in the section about caching (also explaining that any PSR for cache interfaces is explicitly not supported). Maybe you two were interpreting each others comments differently. 

Or in other words: Compiling the container always talks about storing results in a file that has to be given. Caching is using APCu (which is mentioned), and that extension is probably uncommon nowadays.

@dmifedorenko Note that for both strategies, you have to do cleanup of either the file or APCu once you deploy an update.
