### ISSUE TITLE
Unable to composer install with current master branch on PHP 8.1.5

### ISSUE THREAD

**Issue by opengeek** [PHP-DI/PHP-DI#818]
When attempting to run composer install on latest master branch, I am getting the following message…

```
Loading composer repositories with package information
 Updating dependencies
 Your requirements could not be resolved to an installable set of packages.
 
   Problem 1
     - ocramius/proxy-manager[2.11.2, ..., 2.13.1] require php ~7.4.1 || ~8.0.0 -> your php version (8.1.5) does not satisfy that requirement.
     - ocramius/proxy-manager[2.14.0, ..., 2.14.1] require php ~8.0.0 -> your php version (8.1.5) does not satisfy that requirement.
     - Root composer.json requires ocramius/proxy-manager ^2.11.2 -> satisfiable by ocramius/proxy-manager[2.11.2, ..., 2.14.1].
 
 Failed to install packages for  ./composer.json.
```

**Comment by SvenRtbg** [comment]
Have you tried `composer update` instead? I have the feeling somebody stated in a previous issue that the dependencies frozen into the lock file are incompatible with either 7.4 or 8.1, but I cannot find the source of that statement.

But the lack of requests to fix PHP-DI for 8.1 is a clear signal for me that it is working. You'd only clone the library and run `composer install` if you want to work on this library, usually consuming it somewhere else is in fact an implicit `update` operation. And if you work on this library, you should check it is still working with the minimum version required, i.e. 8.0 for the master branch/future 7.0 release, or 7.4 for any maintenance on the current 6.x releases.

**Comment by opengeek** [comment]
Same issue with composer update on a clean clone with PHP 8.1. Something is obviously wrong, as you can see from the messages that the version of proxy-manager does not support 8.1.

**Comment by opengeek** [comment]
To clarify, I am attempting to fork PHP-DI so I can use 6.x with psr/container 2.x versions, as I have several projects that need this support and I cannot wait for the 7.x versions to be released. But recent merges or dependency changes (perhaps?) seem to have broken working on master with PHP 8.1. I use actual releases of 6.x fine in PHP 8.1 where I can use psr/container 1.x, but this is causing me to be unable to get latest versions of other dependencies which require psr/container 2.x support.

**Comment by opengeek** [comment]
Is there some way to exclude the proxy-manager dependency and still develop for PHP-DI on PHP 8.1?

**Comment by opengeek** [comment]
Hello?

**Comment by mnapoli** [comment]
A PR is welcome

**Comment by opengeek** [comment]
If I remove proxy-manager, the unit tests seem to need a complete overhaul in various places. This is why I'm stuck. I'd be happy to work on that with a little assist getting started.

**Comment by mnapoli** [comment]
We don't want to get rid of proxy-manager, that would break some existing features.

**Comment by opengeek** [comment]
> We don't want to get rid of proxy-manager, that would break some existing features.
Then how do you run the tests for 8.1? It doesn't seem like the maintainer is in any hurry to support 8.1.

**Comment by mnapoli** [comment]
Please don't assume I am responsible for solving your problems, even if I own this GitHub repository. This is open-source, you are free to work on it.

https://github.com/PHP-DI/PHP-DI/blob/e0137dc1cd7aae476f3d14b815f11d6cd080b762/LICENSE#L14

And don't get me wrong, I would love to see this resolved. Just like you seem to want it resolved, but nobody is assuming this is your responsibility.

Note that I also won't allow further comments like this. Let's keep the discussion focused on the technical issue.

**Comment by SvenRtbg** [comment]
Curious what issue we are actually facing. The CI configuration explicitly uses `--ignore-platform-reqs` when installing dependencies, however the unit test execution is identical. So if any dependency states to have issues with PHP 8.1 but has not (or that part isn't used in PHP-DI), which dependency is it?

The `ci.yml` has two main changes - one is two years ago, introducing `--ignore-platform-reqs` for runs targeting PHP 8.0, and the most recent one from two months ago reworks the workflow, and only applies this exception to PHP 8.0.

I had the impression that raising the PHP requirement to 7.4 would allow using PHP 8.1. Any hints about reasons from anyones memory you can share?

**Comment by opengeek** [comment]
> Please don't assume I am responsible for solving your problems, even if I own this GitHub repository. This is open-source, you are free to work on it.
> 
> https://github.com/PHP-DI/PHP-DI/blob/e0137dc1cd7aae476f3d14b815f11d6cd080b762/LICENSE#L14
> 
> And don't get me wrong, I would love to see this resolved. Just like you seem to want it resolved, but nobody is assuming this is your responsibility.
> 
> Note that I also won't allow further comments like this. Let's keep the discussion focused on the technical issue.
> 
> To answer your question, tests would probably fail on my machine with 8.1 too. I don't know how to solve this because I haven't researched it yet.

My apologies if I was sounding in any way ungrateful or expecting you to solve this. That was not my intention. As an Open Source maintainer myself, I certainly was not directing any ill-will or malice in my message. And I was referring to the maintainer of proxy-manager regarding not being in a hurry to support 8.1. If I missed that there was some successful way to execute the unit tests on PHP 8.1, I am truly sorry. I am certainly glad to roll-up my sleeves and contribute here to get things moving along, but I'm not sure there is a solution to this without helping ocramius to the finish line or finding an alternative to the proxy-manager package. Any advice on this is certainly appreciated.

> Curious what issue we are actually facing.

@SvenRtbg — the issue we are facing is that ocramius/proxy-manager currently only supports 8.0.x (PHP is specified as ~8.0.0 in the requirements for that package). I did not see the --ignore-platform-reqs was set for 8.1 and I will take that into account now. I will continue investigating and see if there are actual problems with any of the features or tests running in 8.1 and report back. I will also try to find time to see if I can help ocramius in any way finish up support for 8.1 on that end.

**Comment by mnapoli** [comment]
Ah, my apologies then, it was me who jumped to conclusions!

Yeah, it seems we are currently stuck waiting for the 2.15 release of that dependency 🤔

**Comment by geek-merlin** [comment]
I currently don't need this, but here's my €0.05:
Why not add a soft dependency (like [so](https://github.com/symfony/http-client/blob/6.2/HttplugClient.php#L47))? Then the dep is only checked on invocation of the *lazy* feature, and the fraction of people that do not use that, are not going to dependency hell.

**Comment by mnapoli** [comment]
@geek-merlin this would be a breaking change, we can't do that for the active version of PHP-DI.

**Comment by geek-merlin** [comment]
@mnapoli We're doing that once in a while in some other projects i maintain. I don't see hot that might make a functioning prod instance non-functioning?

**Comment by mnapoli** [comment]
Going for a 7.0 release next week (see #726).

https://github.com/PHP-DI/PHP-DI/releases/tag/7.0.0-rc1
