### ISSUE TITLE
PHP 8.1 enum cannot be compiled

### ISSUE THREAD

**Issue by Ekimik** [PHP-DI/PHP-DI#825]
Hello,
I am using PHP-DI in my projects for quite some time and I am currently facing an issue with PHP enums. I am using [monolog](https://github.com/Seldaek/monolog) library for logging in my apps. Recently I have decided to update Monolog from  version `2.6.0` to `3.2.0`. Enum `Monolog\Level` was introduced in Monolog version > 3, which is now prefered way of how to set what messages should be logged. In one of my apps I am using container [compiling](https://php-di.org/doc/performances.html#compiling-the-container). After Monolog upgrade my app stop working with error
```
Fatal error: Uncaught DI\Definition\Exception\InvalidDefinition: Entry "Monolog\Handler\HandlerInterface" cannot be
compiled: An object was found but objects cannot be compiled
Full definition:
Object (
class = Monolog\Handler\StreamHandler
lazy = false
__construct(
$stream = get(app.log.options.target)
$level = Monolog\Level::Info
$bubble = (default value) true
$filePermission = (default value) NULL
$useLocking = (default value) false
)
setFormatter(
$formatter = get(Monolog\Formatter\JsonFormatter)
)
) in /var/www/vendor/php-di/php-di/src/Definition/Exception/InvalidDefinition.php:19
```
I was debugging the issue and end up in [Compiler](https://github.com/PHP-DI/PHP-DI/blob/master/src/Compiler/Compiler.php#L390) class, where it failed when `Monolog\Level` should be processed.

I can get rid of this issue by passing value of enum in my definitions (e.g. use `Monolog\Level::Info->value`). Is there something, I am missing or this is general issue for all enums? When compiling is off, everything works with enum just fine.

**Comment by elbakerino** [comment]
The issue is existing when using the `enum` as value and compiling the container.

As a workaround, directly specifying the value works:

```php
        Monolog\Handler\StreamHandler::class => autowire()
            ->constructor('php://stdout', 100), // `100` instead of `\Monolog\Level::Debug`
```

**Comment by ramsey** [comment]
I just ran into this issue, as well. Since compiling is "off" in my local dev environment, I didn't notice it until after deploying. 😳

**Comment by mnapoli** [comment]
👍 indeed that sucks.

Happy to merge a PR that fixes that!

**Comment by tobiascapin** [comment]
I have the same problem, show I remove all enums on my configs? Was it solved in a stable version? Thanks
