### ISSUE TITLE
Clarify maintenance status, and 7.x / php8 / psr/container:2

### ISSUE THREAD

**Issue by geek-merlin** [PHP-DI/PHP-DI#833]
This is an awesome package and even after a few days using it i'm really happy.
Then i wanted to upgrade packages, and what i saw...
- There is no non-dev release that is fine with psr/container:2 (required e.g. by current symfony/service-contracts v3.2.0)
- There is a 7.3-beta3 that is some commits behind 6.1 (sic).
- There is a dev-master and v7.x-dev, diverging, and a MR in #726

Tbh, this scares me a lot. Any help needed?

**Comment by mnapoli** [comment]
I apologize for dropping the ball. I have a lot on my plate and I made this a secondary priority.

I'll post an update on the thread for a release next week! I'll close this issue in the meantime, but don't take this as me closing the discussion :)

**Comment by geek-merlin** [comment]
I'm maintainer myself and it's open source after all. Thanks for setting this on your schedule.

And: Do not hesitate to ask for help if needed! I have a tight schedule, too, but in the end it's me (and others) that have an itch to scratch.
