### ISSUE TITLE
[v7] Enabling static analysis on definitions

### ISSUE THREAD

**Issue by szepeviktor** [PHP-DI/PHP-DI#834]
Using PHP generics (and array types) we can set key and value type of definitions throughout the code base.
Actually turning comments into code.
```php
/**
 * Keys are strings, values are `Definition` objects or null.
 *                    👇🏻
 * @var \ArrayIterator<string, \DI\Definition\Definition|null>`
 */
```

Now definitions may have a bug or two: their types are ignored.

@mnapoli Would you accept a PR?

**Comment by szepeviktor** [comment]
This would make our PHPStan baseline an almost empty file!

**Comment by mnapoli** [comment]
I would, but on the `v7` branch (because it will be merged to master next week). And v7 uses Psalm (a year ago it was ahead of phpstan).

**Comment by szepeviktor** [comment]
All right.
[I](https://packagist.org/packages/szepeviktor/phpstan-wordpress) let you ride the `psalm` way.
