### ISSUE TITLE
Supporting named arguments in PHP-DI 7 

### ISSUE THREAD

**Issue by ldebrouwer** [PHP-DI/PHP-DI#840]
I took the first release candidate for PHP-DI 7 for a spin on a large project, and it was a very smooth upgrade process, but I did notice a slight regression in terms of developer experience.

In PHP-DI 6 we could easily use the following;

```
    App\Service::class => autowire()
        ->constructor(
            enabled: fn() => Config::ENABLED,
            URL: fn() => Config::REDIRECT_URI,
            clientID: fn() => Config::CLIENT_ID,
            clientSecret: fn() => Config::CLIENT_SECRET,
        ),
 ```
 As you can see we could easily use PHP 8's named arguments, and it would work as intended.
 
 And with 7.0.0-rc1 we needed to update this to something like this;
 
```
    App\Service::class => autowire()
        ->constructorParameter('enabled', fn() => Config::ENABLED)
        ->constructorParameter('URL', fn() => Config::REDIRECT_URI)
        ->constructorParameter('clientID', fn() => Config::CLIENT_ID)
        ->constructorParameter('clientSecret', fn() => Config::CLIENT_SECRET),
 ```
 
 It's not a massive issue per se, but it _was_ really nice to be able to use named arguments.

**Comment by mnapoli** [comment]
Thanks for the report.

Could you clarify what happens if you use named arguments with PHP-DI 7?

**Comment by ldebrouwer** [comment]
It _works_, but PHPStan throws an error like the one below, because of the typehint;
```
Parameter ...$parameters of method DI\Definition\Helper\CreateDefinitionHelper::constructor() expects array, Closure given.
```

**Comment by mnapoli** [comment]
Ah ok so it's just a phpstan warning. Feel free to send a PR if you find out how to solve this.
