### ISSUE TITLE
Is there a way to collect Services based on Interface?

### ISSUE THREAD

**Issue by BlackScorp** [PHP-DI/PHP-DI#848]
Hello There.

i would like to use PHP-DI in similar way like tagged services in Symfony. Based on Interfaces. But iam not sure how to realize this.

I would like to get all Instances which implements an Interface. The usecase would be using PHPLeauge events.

Currently i have to pull manually all services which subscribe to a specific event.

```php
'eventList' => function(ContainerInterface $container){
    return [
      $container->get(Event1:class),
      $container->get(Event2::class),
    ];
```

and then i use a middleware to get them

```php
$events = $container->get('eventList');
foreach($events as $event){
$eventDispatcher->subscribeTo($event->getName(),$event);
}
```
but then everytime if i create a new event subscriber i have to extend manually the eventList. 

in symfony you can tag a service or fetch all services which implements a specific Interface.

something like $container->get(EventSubscriberInterface::class); //would return an iterable ServiceCollection 

is there something similar right now?

**Comment by mnapoli** [comment]
Hi, you would have to create the entry that returns all the implementations (e.g. an array or a factory).

Closing as duplicate, check out past discussions like #831 or #175
