### ISSUE TITLE
methodParameter() not working as expected

### ISSUE THREAD

**Issue by tlaugier** [PHP-DI/PHP-DI#852]
I am not able to use the `methodParameter()` helper as it is stated in the documentation.
Quoting the documentation:
> You can also define only specific parameters: it allows to define the parameters that couldn't be guessed by the autowiring using type-hints.

When I try to use it, PHP-DI becomes unable to resolve the rest of the method arguments although they are properly typed and it is able to resolve them correctly without the extra parameter.
Given the following method definition, autowiring works as expected:
`public function summary(Request $request, Response $response): Response`
Adding an extra parameter and using `methodParameter()` to teach PHP-DI what value to inject, it doesn't work anymore:
`public function summary(Request $request, Response $response, array $versions): Response`
In my definitions:
```php
[
    'versions': ['1.0.1', '1.2.0', '2.0.0'],
    SummaryController::class => DI\autowire()->methodParameter('summary', 'versions', DI\get('versions'))
]
```
The following error exception is raised:
```
Entry "App\Controllers\SummaryController" cannot be resolved: Parameter $request of summary() has no value defined or guessable Full definition: Object ( class = App\Controllers\SummaryController lazy = false __construct( $container = get(DI\Container) ) summary( $request = #UNDEFINED# $response = #UNDEFINED# $versions = get(versions) ) )
```
My PHP-DI version is 6.4.0

**Comment by mnapoli** [comment]
Interesting, that sounds like a bug indeed 👍 

Do you get the same error with v7?

**Comment by tlaugier** [comment]
I just tried with version 7.0.2 and I can reproduce the issue.

**Comment by mnapoli** [comment]
Thanks for confirming! Any contribution here (by anyone reading this) would be welcome 👍

**Comment by serge-kvashnin** [comment]
I might be wrong since some bits of information are missing, but it seems like there's a misunderstanding of the
documentation here.

Based on the description, I believe @tlaugier is trying to use PHP-DI's container to inject `versions` when calling
a `SummaryController` method, probably like this:

```php
$container->call([SummaryController::class, 'summary']);
```

However, using `methodParameter()` (which is similar to `method`) will actually attempt this call *after* creating an
instance of the callable (`SummaryController`). Its purpose is to inject dependencies into an instance using setters,
not during method invocation.

For illustration, the code below won't work according to the docs, but it shows what I think @tlaugier is actually
trying to do:

```php
    #[Inject]
    public function summary(#[Inject('versions')] array $versions): ResponseInterface
    {
        return new Response(body: implode(', ', $versions));
    }
```

I assume this issue can therefore be closed.

**Comment by tlaugier** [comment]
Hi @serge-kvashnin 

> Based on the description, I believe @tlaugier is trying to use PHP-DI's container to inject versions when calling
a SummaryController method, probably like this:
>
> ```php
> $container->call([SummaryController::class, 'summary']);
> ```

Indeed, this is something similar, `summary` in this case is a controller method called by Slim.

I did not understand your explanation however : 
> Its purpose is to inject dependencies into an instance using setters, not during method invocation
Does this mean that `methodParameter` would be used to set a `versions` instance property value before calling the method `summary` ?

If this function is working as expected, do I have another solution to do what I need? Which is injecting a single argument and have all the others be autowired?

**Comment by serge-kvashnin** [comment]
Given that your `versions` parameter is statically defined in the container, you could simply initialize your controller 
with this property and then use it in your method later on.

```php
return [
    'versions': ['1.0.1', '1.2.0', '2.0.0'],
    SummaryController::class => DI\autowire()
        ->constructorParameter('versions', DI\get('versions')),
];
```

```php
class SummaryController
{
    private array $versions;

    public function __construct(array $versions) {
        $this->versions = $versions;
    }
    
    public function summary(RequestInterface $request): ResponseInterface
    {
        // [...]
    }
}
```

If you're specifically looking for method parameter resolving, you can tweak your Slim app instantiation and add the
resolvers you need. You can use the [PHP-DI/Invoker](https://github.com/PHP-DI/Invoker#parameter-resolvers) library,
which is internally used by PHP-DI.

**Comment by tlaugier** [comment]
Ok, thank you @serge-kvashnin!

While I agree that docs could be a little clearer about what `methodParameter()` actually does, I believe this issue can be closed now.
