### ISSUE TITLE
Symfony 7 and php8 support

### ISSUE THREAD

**Issue by ivan1986** [PHP-DI/PHP-DI#871]
Hello

Oficial Symfony bridge not support new symfony and php8

Need add fork to documentation

https://github.com/TeknooSoftware/bridge-phpdi-symfony

**Comment by ivan1986** [comment]
Main project has not been updated, and this is a fork, then perhaps you should update the main project from the fork?

**Comment by mnapoli** [comment]
You can open an issue in the "bridge" project. Even better, send a pull request to fix the issue if you can.
