### ISSUE TITLE
Inject dependecy into Entity/Model class

### ISSUE THREAD

**Issue by tchari** [PHP-DI/PHP-DI#887]
I have a one-off use case where I have a dependency that I want to inject into a database Entity class. I can't really inject it into the constructor (I don't think anyway) and I tried using the #[Inject] attribute on a class property but it didn't seem to work - I'm guessing if you instatiate the class then it doesn't autowire the properly?

To exemplify the use case (note: my real-world use-case is different and significantly more complex than this one):
```
<?php

#[Entity()]
class Car
{
  #[Inject]
  private FuelEfficiencyCalculator $fuelEfficiencyCalculator;

  public function __construct(private User $owner, private string $make, private string $model, private string $vin): void
  {
  }

  public function getFuelEfficiency(): float
  {
     return $this->fuelEfficiencyCalculator->calculate($this->make, $this->model);
  }
}
```

and I have a service that looks like this
```
<?php

class CarService
{
  public function __construct(private EntityManagerInterface $entityManager)
  {
  }

  public function getAverageFuelEfficiency(array $carIds): float
  {
    $cars = $this->entityManager->getRepository(Car::class)->findBy(['id' => $carIds]);
    $numCars = count($cars);
    $total = array_reduce($cars, fn ($car) => $car->getFuelEfficiency(), 0);
    return $total/$numCars;
  }

  public function createCar(User $owner, array $props): array
  {
    $car = new Car($owner, $props['make'], $props['model'], $prop['vin']);
    $this->entityManager->persist($car);
    $this->entityManager->flush();
    $serialized = [
      'make' => $car->getMake(),
      'model' => $car->getModel(),
      'fuelEfficiency' => $car->getFuelEfficiency(),
    ];
  }
}
```

If I have a contoller that's calling CarService::getAverageFuelEfficiency or CarService::createCar I get an error saying that I cannot use `fuelEfficiencyCalculator` if I haven't initialized it yet. Which seems to me that the dependecy wasn't autowired using the attribute #[Inject] (since the docs say the autowiring happens after __construct).

So I have a couple questions:
1. Should I be able to autowire dependencies to models using the #[Inject] attribute on a property? This seems like a no give how I want to use it.
2. Is there a better paradigm or way of structuring this to do this? My workaround is to bail on autowiring and DI just pull the getFuelEfficiency method out of the Model class and stick it elsewhere - this is a functional solution but a bit clunky for my implementation.

Thanks in advance.

**Comment by mnapoli** [comment]
The class has to be created by the container, it cannot work otherwise.

**Comment by SvenRtbg** [comment]
Anything that you do for allowing PHP-DI to automagically inject things requires that you request an object from the DI object you get after you have configured it.

So you would get a properly filled and injected Car if you would call `$di->get(Car::class)`, and `$di` would be the DI container object you build during bootstrapping.

But your code does not call that method, nor does the code inside the entity manager.

`$cars = $this->entityManager->getRepository(Car::class)->findBy(['id' => $carIds]);`

This is most likely making the code inside analyse the constructor of `Car`, filling the fields from the database, but as there is no official way to populate the field for FuelEfficiencyCalculator, code usually doesn't do it, and if it would be exposed as part of the constructor or as a setter method, an entity manager usually doesn't know what to inject anyways.

On the other hand, I wonder what the design of this class relation is based on. Every car knows how to calculate it's own fuel efficiency, which would make sense if this calculation is different for every car. Then I would assume some fields in the database store the characteristics of the calculation, parameters of it, etc. However I suppose there may be some data points in the database, but the calculation is exactly the same formula, i.e. exactly the same code for every car. Consider restructuring your class dependencies in a way that allows to either inject the calculator after queried from the database (setter), or make the calculation be part of a wrapper class around Car, or inject the formula as a trait, or instatiate the calculator with `$this->fuelEfficiencyCalculator = new FuelEfficiencyCalculator()` and skip the dependency injection approach.

**Comment by tchari** [comment]
@mnapoli Thank you for your responses. I had figured this was the case but just wanted to make sure I didn't miss anything.

@SvenRtbg Yes, essentially, each car "knows" how to calculate it's own fuel efficiency and (in my real-world use-case) that depends on another service that pulls data in from another source. I wanted to use a factory method paradigm to accomplish this and have DI automagically inject the fuelEfficiency calculator. However, that's probably a bad practise anyway.

Thanks again.
